#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Add bulk C2 words to reach ~4000 total."""

FILE = r"D:\dev\DLZLAB\wordApp\app.html"
words = []
esc = lambda s: s.replace("'", "\\'")
W = lambda e,p,f,x: words.append(f"['{esc(e)}','{esc(p)}','{esc(f)}','{esc(x)}']")

# High-frequency C2 words in compact format
# Groups of 15 words each (one day's worth)
BULK = [
# Advanced Nouns
("aberration","n.","انحراف","an aberration from the norm"),("absolution","n.","آمرزش","grant absolution"),("abstinence","n.","پرهیز","total abstinence from alcohol"),("accolade","n.","تحسین","received accolades"),("acquiescence","n.","رضایت","passive acquiescence"),("adversary","n.","حریف","a formidable adversary"),("affinity","n.","قرابت","a natural affinity for music"),("alacrity","n.","اشتیاق","accepted with alacrity"),("allegiance","n.","وفاداری","pledge allegiance"),("allusion","n.","اشاره","make an allusion to"),("affluence","n.","ثروت","live in affluence"),("agenda","n.","دستور کار","political agenda"),("altruism","n.","نوع‌دوستی","genuine altruism"),("amnesty","n.","عفو عمومی","grant amnesty"),("animosity","n.","خصومت","old animosities"),
# Advanced Verbs
("appease","v.","آرام کردن","appease the angry crowd"),("arbitrate","v.","داوری کردن","arbitrate the dispute"),("ascertain","v.","تحقیق کردن","ascertain the truth"),("aspire","v.","آرزو داشتن","aspire to greatness"),("assimilate","v.","جذب شدن","assimilate into the culture"),("atrophy","v.","تحلیل رفتن","muscles atrophy"),("bolster","v.","تقویت کردن","bolster confidence"),("boycott","v.","تحریم کردن","boycott the product"),("capitulate","v.","تسلیم شدن","capitulate to demands"),("catalyze","v.","تسریع کردن","catalyze change"),("circumvent","v.","دور زدن","circumvent the rules"),("coerce","v.","اجبار کردن","coerced into signing"),("collaborate","v.","همکاری کردن","collaborate on the project"),("commemorate","v.","بزرگداشت","commemorate the event"),("compensate","v.","جبران کردن","compensate for losses"),
# Advanced Adjectives
("acrimonious","adj.","تلخ","acrimonious divorce"),("astute","adj.","زیرک","astute businessman"),("capricious","adj.","دمدمی","capricious weather"),("coercive","adj.","اجباری","coercive measures"),("complacent","adj.","خودراضی","complacent attitude"),("contemptuous","adj.","تحقیرآمیز","contemptuous look"),("contentious","adj.","جنجالی","contentious issue"),("corroborating","adj.","تأییدکننده","corroborating evidence"),("deferential","adj.","محترمانه","deferential behavior"),("diligent","adj.","سختکوش","diligent student"),("disdainful","adj.","متحقّر","disdainful tone"),("disparate","adj.","متفاوت","disparate groups"),("dogmatic","adj.","جزمی","dogmatic beliefs"),("dubious","adj.","مشکوک","dubious distinction"),("egregious","adj.","فاحش","egregious error"),
# Academic Verbs 2
("elucidate","v.","روشن ساختن","elucidate the concept"),("emancipate","v.","آزاد کردن","emancipate the slaves"),("embellish","v.","آراستن","embellish the truth"),("embezzle","v.","اختلاس کردن","embezzle funds"),("empower","v.","قدرت دادن","empower women"),("encompass","v.","در برگرفتن","encompass all aspects"),("engender","v.","ایجاد کردن","engender controversy"),("eradicate","v.","ریشه کن کردن","eradicate disease"),("exacerbate","v.","تشدید کردن","exacerbate tensions"),("expedite","v.","تسریع کردن","expedite the process"),("fabricate","v.","جعل کردن","fabricate evidence"),("facilitate","v.","تسهیل کردن","facilitate communication"),("falsify","v.","تحریف کردن","falsify records"),("fathom","v.","درک کردن","fathom the meaning"),("flourish","v.","شکوفا شدن","flourish in adversity"),
# More Adjectives
("eloquent","adj.","فصیح","eloquent speech"),("empirical","adj.","تجربی","empirical evidence"),("ephemeral","adj.","زودگذر","ephemeral beauty"),("equivocal","adj.","مبهم","equivocal answer"),("erratic","adj.","نامنظم","erratic behavior"),("esoteric","adj.","غامض","esoteric knowledge"),("exemplary","adj.","نمونه","exemplary conduct"),("exhaustive","adj.","جامع","exhaustive search"),("exorbitant","adj.","گزاف","exorbitant price"),("expedient","adj.","مصلحتی","politically expedient"),("explicit","adj.","صریح","explicit instructions"),("fastidious","adj.","وسواسی","fastidious about cleanliness"),("flagrant","adj.","آشکار","flagrant violation"),("fortuitous","adj.","اتفاقی","fortuitous encounter"),("frugal","adj.","صرفه‌جو","frugal lifestyle"),
# Advanced Verbs 3
("harness","v.","استفاده کردن","harness solar power"),("hinder","v.","مانع شدن","hinder progress"),("hypothesize","v.","فرضیه دادن","hypothesize about"),("illuminate","v.","روشن کردن","illuminate the subject"),("immerse","v.","غوطه ور شدن","immerse in study"),("impair","v.","مختل کردن","impair vision"),("impede","v.","مانع شدن","impede development"),("implement","v.","اجرا کردن","implement changes"),("implicate","v.","درگیر کردن","implicate in scandal"),("improvise","v.","بداهه گفتن","improvise a solution"),("inaugurate","v.","آغاز کردن","inaugurate a new era"),("incorporate","v.","ادغام کردن","incorporate feedback"),("indict","v.","کیفرخواست","indict for fraud"),("infringe","v.","نقض کردن","infringe upon rights"),("innovate","v.","نوآوری کردن","innovate in technology"),
# Nouns 2
("antithesis","n.","تضاد","the antithesis of"),("apathy","n.","بی‌تفاوتی","public apathy"),("apparatus","n.","دستگاه","political apparatus"),("apprehension","n.","نگرانی","feel apprehension"),("arbitration","n.","داوری","binding arbitration"),("archetype","n.","کهن‌الگو","the archetypal hero"),("aspersion","n.","تهمت","cast aspersions"),("auspices","n.","حمایت","under the auspices of"),("autonomy","n.","خودمختاری","regional autonomy"),("backlash","n.","واکنش منفی","political backlash"),("benevolence","n.","مهربانی","acts of benevolence"),("breach","n.","نقض","breach of contract"),("catalyst","n.","کاتالیزور","catalyst for change"),("censure","n.","انتقاد","vote of censure"),("coercion","n.","اجبار","by coercion"),
# Adjectives 3
("futile","adj.","بیهوده","futile attempt"),("gratuitous","adj.","رایگان","gratuitous violence"),("gregarious","adj.","خوش‌معاشرت","gregarious personality"),("heinous","adj.","نفرت‌انگیز","heinous crime"),("illicit","adj.","غیرقانونی","illicit drugs"),("imminent","adj.","قریب‌الوقوع","imminent danger"),("impartial","adj.","بی‌طرف","impartial judge"),("implicit","adj.","ضمنی","implicit trust"),("indelible","adj.","پاک‌نشدنی","indelible impression"),("indigenous","adj.","بومی","indigenous people"),("indispensable","adj.","ضروری","indispensable tool"),("infallible","adj.","خطاناپذیر","infallible logic"),("inherent","adj.","ذاتی","inherent risk"),("innocuous","adj.","بی‌آزار","innocuous remark"),("insidious","adj.","مکارانه","insidious influence"),
# Verbs 4
("intercede","v.","میانجیگری","intercede on behalf"),("interrogate","v.","بازجویی","interrogate suspects"),("intimidate","v.","ارعاب کردن","intimidate witnesses"),("intoxicate","v.","مست کردن","intoxicated by power"),("jeopardize","v.","به خطر انداختن","jeopardize safety"),("legitimize","v.","مشروعیت دادن","legitimize the regime"),("liquidate","v.","تصفیه کردن","liquidate assets"),("marginalize","v.","حاشیه راندن","marginalize minorities"),("mediate","v.","میانجیگری","mediate the conflict"),("mitigate","v.","کاهش دادن","mitigate risks"),("monopolize","v.","انحصار داشتن","monopolize the market"),("negate","v.","نفی کردن","negate the effect"),("neutralize","v.","خنثی کردن","neutralize the threat"),("obfuscate","v.","مبهم کردن","obfuscate the issue"),("optimize","v.","بهینه کردن","optimize performance"),
# Nouns 3
("collusion","n.","تبانی","collusion between parties"),("commodity","n.","کالا","precious commodities"),("complacency","n.","خودراضی بودن","danger of complacency"),("concession","n.","امتیاز","make concessions"),("consensus","n.","اجماع","reach consensus"),("conservatism","n.","محافظه‌کاری","political conservatism"),("consistency","n.","ثبات","lack of consistency"),("consortium","n.","کنسرسیوم","research consortium"),("contingency","n.","احتمال","contingency plan"),("contradiction","n.","تناقض","contradiction in terms"),("conundrum","n.","معما","a puzzling conundrum"),("convergence","n.","همگرایی","convergence of ideas"),("counterpart","n.","همتا","foreign counterpart"),("culmination","n.","اوج","the culmination of"),("catalyst","n.","کاتالیزور","act as a catalyst"),
# Verbs 5
("permeate","v.","نفوذ کردن","permeate every aspect"),("perpetuate","v.","تداوم بخشیدن","perpetuate stereotypes"),("polarize","v.","قطبی کردن","polarize opinions"),("precipitate","v.","ایجاد کردن","precipitate a crisis"),("predominate","v.","غالب بودن","predominate in the region"),("preempt","v.","پیشگیری کردن","preempt an attack"),("prescribe","v.","تجویز کردن","prescribe medication"),("presume","v.","فرض کردن","presume innocence"),("proliferate","v.","تکثیر شدن","proliferate rapidly"),("propagate","v.","گسترش دادن","propagate ideas"),("provoke","v.","برانگیختن","provoke a reaction"),("reconcile","v.","آشتی دادن","reconcile differences"),("rectify","v.","اصلاح کردن","rectify the error"),("rehabilitate","v.","بازپروری","rehabilitate offenders"),("reimburse","v.","بازپرداخت","reimburse expenses"),
# Adjectives 4
("intangible","adj.","ناملموس","intangible assets"),("integral","adj.","جدا نشدنی","integral part"),("integrity","n.","صداقت","moral integrity"),("intricate","adj.","پیچیده","intricate design"),("intrinsic","adj.","ذاتی","intrinsic value"),("intuitive","adj.","شهودی","intuitive understanding"),("invariable","adj.","تغییرناپذیر","invariable rule"),("invidious","adj.","ناخوشایند","invidious comparison"),("irrevocable","adj.","برگشت‌ناپذیر","irrevocable decision"),("itinerant","adj.","سیّار","itinerant worker"),("judicious","adj.","سنجیده","judicious use"),("lackluster","adj.","بی‌روح","lackluster performance"),("latent","adj.","نهفته","latent talent"),("laudable","adj.","ستودنی","laudable goal"),("legitimate","adj.","مشروع","legitimate concern"),
# Verbs 6
("reiterate","v.","تکرار کردن","reiterate key points"),("relinquish","v.","واگذار کردن","relinquish control"),("remunerate","v.","پاداش دادن","remunerate employees"),("repeal","v.","لغو کردن","repeal legislation"),("replenish","v.","پر کردن","replenish supplies"),("reprimand","v.","توبیخ کردن","reprimand the officer"),("repudiate","v.","انکار کردن","repudiate the claim"),("rescind","v.","لغو کردن","rescind the order"),("retaliate","v.","تلافی کردن","retaliate against"),("retract","v.","پس گرفتن","retract a statement"),("revitalize","v.","احیاء کردن","revitalize the economy"),("scrutinize","v.","موشکافی کردن","scrutinize the contract"),("stagnate","v.","رکود داشتن","stagnate economically"),("stimulate","v.","تحریک کردن","stimulate growth"),("substantiate","v.","اثبات کردن","substantiate claims"),
# Nouns 4
("deadlock","n.","بن‌بست","break the deadlock"),("debris","n.","آوار","clear the debris"),("decadence","n.","انحطاط","moral decadence"),("default","n.","عدم پرداخت","default on loan"),("defect","n.","نقص","birth defect"),("deficit","n.","کمبود","budget deficit"),("deliberation","n.","شور","after deliberation"),("delusion","n.","توهم","suffer from delusions"),("dependency","n.","وابستگی","drug dependency"),("depletion","n.","تخلیه","resource depletion"),("deterioration","n.","تخریب","environmental deterioration"),("dilemma","n.","دوراهی","moral dilemma"),("discrepancy","n.","ناهماهنگی","price discrepancy"),("disparity","n.","نابرابری","income disparity"),("disposition","n.","منش","cheerful disposition"),
# Verbs 7
("supplant","v.","جایگزین شدن","supplant the old guard"),("suppress","v.","سرکوب کردن","suppress dissent"),("surpass","v.","پیشی گرفتن","surpass expectations"),("sustain","v.","حفظ کردن","sustain growth"),("terminate","v.","خاتمه دادن","terminate the contract"),("transcend","v.","فراتر رفتن","transcend boundaries"),("unify","v.","متحد کردن","unify the country"),("undermine","v.","تضعیف کردن","undermine authority"),("uphold","v.","تأیید کردن","uphold the law"),("utilize","v.","استفاده کردن","utilize resources"),("vindicate","v.","تأیید کردن","vindicate the decision"),("waive","v.","صرف نظر کردن","waive the fee"),("yield","v.","تسلیم شدن","yield to pressure"),("zeal","n.","شور و شوق","religious zeal"),("zenith","n.","اوج","reach the zenith"),
# More adjectives
("magnanimous","adj.","بزرگوار","magnanimous gesture"),("malicious","adj.","بدخواهانه","malicious intent"),("mandatory","adj.","اجباری","mandatory requirement"),("manifest","adj.","آشکار","manifest injustice"),("marginal","adj.","حاشیه‌ای","marginal benefit"),("materialistic","adj.","مادی‌گرا","materialistic society"),("meticulous","adj.","موشکاف","meticulous planning"),("militant","adj.","مبارز","militant group"),("momentous","adj.","بسیار مهم","momentous decision"),("monotonous","adj.","یکنواخت","monotonous routine"),("mutual","adj.","متقابل","mutual respect"),("naive","adj.","ساده‌لوح","naive optimism"),("negligent","adj.","غفلت‌کار","negligent behavior"),("notorious","adj.","بدنام","notorious criminal"),("novel","adj.","بدیع","novel approach"),
# More academic nouns
("dogma","n.","جزم","religious dogma"),("dogmatism","n.","جزم‌گرایی","intellectual dogmatism"),("dominance","n.","سلطه","market dominance"),("drought","n.","خشکسالی","severe drought"),("dynamism","n.","پویایی","economic dynamism"),("edict","n.","فرمان","royal edict"),("egalitarianism","n.","برابری‌طلبی","political egalitarianism"),("eloquence","n.","فصاحت","speak with eloquence"),("emancipation","n.","رهایی","emancipation of slaves"),("embodiment","n.","تجسم","embodiment of virtue"),("eminence","n.","برجستگی","eminence in the field"),("empiricism","n.","تجربه‌گرایی","scientific empiricism"),("empowerment","n.","توانمندسازی","women empowerment"),("endeavor","n.","تلاش","scientific endeavor"),("enlightenment","n.","روشنگری","age of enlightenment"),
# Academic verbs 8
("accentuate","v.","برجسته کردن","accentuate the positive"),("accommodate","v.","سازگار کردن","accommodate differences"),("accumulate","v.","انباشتن","accumulate wealth"),("activate","v.","فعال کردن","activate the system"),("adjudicate","v.","داوری کردن","adjudicate claims"),("administer","v.","مدیریت کردن","administer the program"),("aggravate","v.","تشدید کردن","aggravate the situation"),("alienate","v.","بیگانه کردن","alienate supporters"),("alleviate","v.","تسکین دادن","alleviate poverty"),("amalgamate","v.","ادغام کردن","amalgamate companies"),("ameliorate","v.","بهبود بخشیدن","ameliorate conditions"),("amplify","v.","گسترش دادن","amplify the message"),("annihilate","v.","نابود کردن","annihilate the enemy"),("appease","v.","آرام کردن","appease critics"),("apportion","v.","تقسیم کردن","apportion blame"),
# Academic nouns 5
("equilibrium","n.","تعادل","maintain equilibrium"),("equity","n.","عدالت","social equity"),("erosion","n.","فرسایش","soil erosion"),("espionage","n.","جاسوسی","industrial espionage"),("etiquette","n.","آداب معاشرت","proper etiquette"),("evacuation","n.","تخلیه","emergency evacuation"),("evasion","n.","فرار","tax evasion"),("exaggeration","n.","اغراق","gross exaggeration"),("exaltation","n.","ستایش","exaltation of nature"),("excellence","n.","برتری","academic excellence"),("exemption","n.","معافیت","tax exemption"),("exertion","n.","تلاش","physical exertion"),("exile","n.","تبعید","live in exile"),("exploitation","n.","بهره‌کشی","labor exploitation"),("expulsion","n.","اخراج","expulsion from school"),
# More verbs
("consecrate","v.","تقدیس کردن","consecrate the church"),("console","v.","تسلی دادن","console the bereaved"),("conspire","v.","توطئه کردن","conspire against"),("constrain","v.","محدود کردن","constrained by budget"),("contemplate","v.","تأمل کردن","contemplate the future"),("contend","v.","ادعا کردن","contend with challenges"),("convene","v.","تشکیل جلسه دادن","convene a meeting"),("converge","v.","همگرا شدن","converge on a point"),("converse","v.","گفتگو کردن","converse in French"),("correlate","v.","همبسته بودن","correlate with income"),("corrode","v.","خوردگی کردن","metal corrodes"),("counsel","v.","مشاوره دادن","counsel the patient"),("counteract","v.","خنثی کردن","counteract the effects"),("curtail","v.","محدود کردن","curtail spending"),("deceive","v.","فریب دادن","deceive the public"),
# More adjectives 5
("oblique","adj.","مورب، غیرمستقیم","an oblique reference"),("obscure","adj.","مبهم","obscure origins"),("obsolescent","adj.","منسوخ‌شونده","obsolescent technology"),("obsolete","adj.","منسوخ","obsolete equipment"),("obstinate","adj.","لجباز","obstinate refusal"),("ominous","adj.","شوم","ominous silence"),("opaque","adj.","ناشفاف","opaque glass"),("opportunistic","adj.","فرصت‌طلب","opportunistic behavior"),("oppressive","adj.","سرکوبگر","oppressive regime"),("optimistic","adj.","خوش‌بین","optimistic outlook"),("orthodox","adj.","ارتدکس","orthodox view"),("ostentatious","adj.","پر زرق و برق","ostentatious display"),("outdated","adj.","قدیمی","outdated methods"),("outright","adj.","کامل","outright rejection"),("outspoken","adj.","صریح","outspoken critic"),
# Verbs - legal
("default","v.","عدم پرداخت","default on the loan"),("defraud","v.","کلاهبرداری","defraud investors"),("depose","v.","خلع کردن","depose the king"),("detain","v.","بازداشت کردن","detain suspects"),("disclaim","v.","انکار کردن","disclaim responsibility"),("divest","v.","واگذار کردن","divest holdings"),("enact","v.","تصویب کردن","enact legislation"),("exonerate","v.","تبرئه کردن","exonerate the accused"),("extradite","v.","استرداد کردن","extradite the fugitive"),("impeach","v.","استیضاح کردن","impeach the official"),("incriminate","v.","متهم کردن","incriminate oneself"),("indemnify","v.","غرامت دادن","indemnify against loss"),("interrogate","v.","بازجویی کردن","interrogate the prisoner"),("legislate","v.","قانونگذاری","legislate on matters"),("litigate","v.","شکایت کردن","litigate the case"),
# More nouns
("expenditure","n.","هزینه","government expenditure"),("expertise","n.","تخصص","technical expertise"),("exploitation","n.","بهره‌کشی","resource exploitation"),("extinction","n.","انقراض","species extinction"),("extravagance","n.","اسراف","financial extravagance"),("fabrication","n.","جعل","complete fabrication"),("faction","n.","جناح","political faction"),("famine","n.","قحطی","widespread famine"),("fatigue","n.","خستگی","chronic fatigue"),("feasibility","n.","عملی بودن","feasibility study"),("fidelity","n.","وفاداری","marital fidelity"),("fluctuation","n.","نوسان","price fluctuation"),("foresight","n.","آینده‌نگری","remarkable foresight"),("fortitude","n.","شجاعت","mental fortitude"),("fraud","n.","کلاهبرداری","insurance fraud"),
# Adjectives 6
("palatable","adj.","خوش‌طعم","palatable food"),("paltry","adj.","ناچیز","paltry sum"),("paramount","adj.","بسیار مهم","of paramount importance"),("partisan","adj.","حزبی","partisan politics"),("passionate","adj.","پرشور","passionate advocate"),("passive","adj.","منفعل","passive resistance"),("patronizing","adj.","تحقیرآمیز","patronizing tone"),("peculiar","adj.","عجیب","peculiar behavior"),("perilous","adj.","خطرناک","perilous journey"),("permanent","adj.","دائمی","permanent solution"),("permissible","adj.","مجاز","permissible limits"),("pernicious","adj.","مضر","pernicious influence"),("perplexing","adj.","گیج‌کننده","perplexing problem"),("persistent","adj.","مداوم","persistent cough"),("perverse","adj.","انحرافی","perverse logic"),
# Nouns 6
("gratitude","n.","سپاسگزاری","express gratitude"),("gravity","n.","جاذبه","gravity of the situation"),("grief","n.","اندوه","deep grief"),("groundwork","n.","زمینه‌سازی","lay the groundwork"),("guardian","n.","نگهبان","legal guardian"),("guideline","n.","دستورالعمل","follow guidelines"),("gullibility","n.","ساده‌لوحی","his gullibility"),("habitat","n.","زیستگاه","natural habitat"),("harassment","n.","آزار و اذیت","workplace harassment"),("hardship","n.","سختی","economic hardship"),("harmony","n.","هماهنگی","live in harmony"),("hazard","n.","خطر","health hazard"),("heritage","n.","میراث","cultural heritage"),("hierarchy","n.","سلسله مراتب","corporate hierarchy"),("humanitarian","adj.","بشردوستانه","humanitarian aid"),
# Nouns 7
("hypocrisy","n.","ریاکاری","political hypocrisy"),("hypothesis","n.","فرضیه","working hypothesis"),("idealism","n.","آرمان‌گرایی","youthful idealism"),("ideology","n.","ایدئولوژی","political ideology"),("ignorance","n.","نادانی","willful ignorance"),("illusion","n.","توهم","optical illusion"),("immaturity","n.","نابالغی","emotional immaturity"),("immensity","n.","عظمت","immensity of space"),("immigration","n.","مهاجرت","illegal immigration"),("immorality","n.","بداخلاقی","moral immorality"),("immunity","n.","مصونیت","diplomatic immunity"),("impairment","n.","مختلی","hearing impairment"),("impartiality","n.","بی‌طرفی","judicial impartiality"),("impediment","n.","مانع","speech impediment"),("imperative","n.","ضرورت","moral imperative"),
# More verbs 9
("decree","v.","فرمان دادن","decree a holiday"),("deem","v.","انگاشتن","deem necessary"),("deflect","v.","منحرف کردن","deflect criticism"),("delegate","v.","واگذار کردن","delegate tasks"),("deliberate","v.","شور کردن","deliberate carefully"),("denounce","v.","محکوم کردن","denounce violence"),("depict","v.","تصویر کردن","depict rural life"),("deplete","v.","تخلیه کردن","deplete resources"),("deploy","v.","مستقر کردن","deploy troops"),("depreciate","v.","کاهش ارزش","currency depreciates"),("designate","v.","تعیین کردن","designate as heritage"),("deter","v.","بازداشتن","deter crime"),("deviate","v.","منحرف شدن","deviate from plan"),("devise","v.","ابداع کردن","devise a strategy"),("diffuse","v.","پراکنده کردن","diffuse tension"),
# Adjectives - social
("precarious","adj.","ناپایدار","precarious situation"),("precautionary","adj.","احتیاطی","precautionary measures"),("precious","adj.","ارزشمند","precious resource"),("precipitous","adj.","سریع و ناگهانی","precipitous decline"),("precise","adj.","دقیق","precise measurement"),("predatory","adj.","غارتگر","predatory lending"),("predictable","adj.","قابل پیش‌بینی","predictable outcome"),("preeminent","adj.","سرآمد","preeminent scholar"),("preemptive","adj.","پیشگیرانه","preemptive strike"),("prejudicial","adj.","تبعیض‌آمیز","prejudicial statements"),("preliminary","adj.","مقدماتی","preliminary results"),("premature","adj.","زودرس","premature conclusion"),("premeditated","adj.","از پیش طراحی شده","premeditated murder"),("preponderant","adj.","برتر","preponderant influence"),("prerequisite","adj.","پیش‌نیاز","prerequisite course"),
# Verbs 10
("disband","v.","منحل کردن","disband the committee"),("discern","v.","تشخیص دادن","discern the pattern"),("discharge","v.","ترخیص کردن","discharge from hospital"),("discount","v.","نادیده گرفتن","discount the possibility"),("discriminate","v.","تبعیض قائل شدن","discriminate against"),("disintegrate","v.","فروپاشیدن","empire disintegrated"),("dismiss","v.","اخراج کردن","dismiss the idea"),("disperse","v.","پراکنده شدن","crowd dispersed"),("displace","v.","جابجا کردن","displace populations"),("dispose","v.","دفع کردن","dispose of waste"),("disregard","v.","نادیده گرفتن","disregard warnings"),("disrupt","v.","اختلال ایجاد کردن","disrupt the class"),("disseminate","v.","منتشر کردن","disseminate information"),("dissolve","v.","منحل کردن","dissolve parliament"),("distort","v.","تحریف کردن","distort the truth"),
# Nouns 8
("inauguration","n.","افتتاح","presidential inauguration"),("incentive","n.","انگیزه","financial incentive"),("incidence","n.","بروز","incidence of disease"),("inclusion","n.","شمول","social inclusion"),("indemnity","n.","غرامت","insurance indemnity"),("indication","n.","نشانه","clear indication"),("indifference","n.","بی‌تفاوتی","public indifference"),("indignation","n.","خشم","righteous indignation"),("indispensability","n.","ضرورت","indispensability of"),("individualism","n.","فردگرایی","rugged individualism"),("indulgence","n.","خودنمایی","excessive indulgence"),("inequality","n.","نابرابری","social inequality"),("inertia","n.","اینرسی","bureaucratic inertia"),("infancy","n.","نوزادی","in its infancy"),("infection","n.","عفونت","viral infection"),
# Adjectives 8
("prevalent","adj.","شایع","prevalent disease"),("prickly","adj.","خاردار","prickly personality"),("primitive","adj.","ابتدایی","primitive society"),("principal","adj.","اصلی","principal concern"),("prior","adj.","قبلی","prior engagement"),("proactive","adj.","پیش‌دستانه","proactive approach"),("probable","adj.","محتمل","probable cause"),("problematic","adj.","مشکل‌دار","problematic behavior"),("prodigious","adj.","شگفت‌انگیز","prodigious talent"),("productive","adj.","مولد","productive meeting"),("proficient","adj.","ماهر","proficient in"),("profound","adj.","عمیق","profound impact"),("progressive","adj.","ترقی‌خواه","progressive ideas"),("prohibitive","adj.","بازدارنده","prohibitive cost"),("prolific","adj.","پرکار","prolific writer"),
# Verbs 11
("divert","v.","منحرف کردن","divert resources"),("document","v.","مستند کردن","document the process"),("domesticate","v.","اهلی کردن","domesticate animals"),("dominate","v.","تسلط داشتن","dominate the market"),("donate","v.","اهداء کردن","donate to charity"),("downgrade","v.","کاهش دادن","downgrade the rating"),("drain","v.","تخلیه کردن","drain resources"),("duplicate","v.","کپی کردن","duplicate efforts"),("economize","v.","صرفه‌جویی کردن","economize on fuel"),("edit","v.","ویرایش کردن","edit the manuscript"),("electrify","v.","برقدار کردن","electrify the audience"),("elevate","v.","بالا بردن","elevate standards"),("eliminate","v.","حذف کردن","eliminate waste"),("embark","v.","آغاز کردن","embark on a journey"),("embed","v.","کار گذاشتن","embed in concrete"),
# Nouns 9
("inflation","n.","تورم","control inflation"),("influence","n.","نفوذ","under the influence"),("influx","n.","هجوم","massive influx"),("infrastructure","n.","زیرساخت","infrastructure investment"),("ingenuity","n.","نبوغ","human ingenuity"),("inhibition","n.","بازداری","social inhibition"),("initiative","n.","ابتکار","take initiative"),("injustice","n.","بی‌عدالتی","social injustice"),("innovation","n.","نوآوری","technological innovation"),("insight","n.","بینش","valuable insight"),("inspection","n.","بازرسی","safety inspection"),("instability","n.","ناپایداری","political instability"),("institution","n.","نهاد","financial institution"),("insufficiency","n.","نارسایی","cardiac insufficiency"),("insurgency","n.","شورش","quell the insurgency"),
# Verbs 12
("emphasize","v.","تأکید کردن","emphasize the point"),("empower","v.","قدرت دادن","empower communities"),("enact","v.","تصویب کردن","enact reforms"),("encompass","v.","دربرگرفتن","encompass everything"),("encounter","v.","مواجه شدن","encounter difficulties"),("endanger","v.","به خطر انداختن","endanger species"),("endow","v.","وقف کردن","endow a scholarship"),("enforce","v.","اجرا کردن","enforce the law"),("engage","v.","مشغول کردن","engage students"),("enhance","v.","بهبود بخشیدن","enhance performance"),("enlighten","v.","آگاه ساختن","enlighten the public"),("enrich","v.","غنی ساختن","enrich the mind"),("ensure","v.","تضمین کردن","ensure safety"),("entail","v.","مستلزم","entail risks"),("enumerate","v.","شمردن","enumerate the items"),
# Verbs 13
("equate","v.","یکسان دانستن","equate wealth with happiness"),("erode","v.","فرسایش دادن","erode confidence"),("escalate","v.","تشدید شدن","escalate the conflict"),("establish","v.","تأسیس کردن","establish relations"),("estimate","v.","تخمین زدن","estimate the cost"),("evaluate","v.","ارزیابی کردن","evaluate options"),("evoke","v.","برانگیختن","evoke memories"),("exaggerate","v.","اغراق کردن","exaggerate the truth"),("examine","v.","بررسی کردن","examine evidence"),("exceed","v.","تجاوز کردن","exceed expectations"),("excel","v.","برتری داشتن","excel at math"),("excerpt","v.","گزیده کردن","excerpt from the book"),("exchange","v.","مبادله کردن","exchange ideas"),("exclaim","v.","فریاد زدن","exclaim in surprise"),("exclude","v.","محروم کردن","exclude from consideration"),
# Adjectives 9
("promising","adj.","امیدوارکننده","promising results"),("prompt","adj.","به‌موقع","prompt response"),("prone","adj.","مستعد","prone to error"),("proper","adj.","مناسب","proper procedure"),("proportional","adj.","متناسب","proportional representation"),("proprietary","adj.","اختصاصی","proprietary technology"),("prosperous","adj.","مرفه","prosperous nation"),("protective","adj.","محافظ","protective measures"),("protracted","adj.","طولانی","protracted negotiations"),("provincial","adj.","استانی","provincial government"),("provisional","adj.","موقت","provisional government"),("provocative","adj.","تحریک‌آمیز","provocative statement"),("prudent","adj.","محتاط","prudent decision"),("psychic","adj.","روحی","psychic trauma"),("punctual","adj.","خوش‌وقت","punctual arrival"),
# Nouns 10
("integrity","n.","صداقت","moral integrity"),("intellect","n.","عقل","sharp intellect"),("intensity","n.","شدت","emotional intensity"),("intent","n.","قصد","letter of intent"),("interaction","n.","تعامل","social interaction"),("interdependence","n.","وابستگی متقابل","economic interdependence"),("interim","n.","موقت","in the interim"),("intervention","n.","مداخله","military intervention"),("intimacy","n.","صمیمیت","emotional intimacy"),("intolerance","n.","نابردباری","religious intolerance"),("intrigue","n.","دسیسه","political intrigue"),("intuition","n.","شهود","feminine intuition"),("invasion","n.","تهاجم","military invasion"),("inventory","n.","فهرست","take inventory"),("investigation","n.","تحقیق","criminal investigation"),
# Verbs 14
("execute","v.","اجرا کردن","execute the plan"),("exempt","v.","معاف کردن","exempt from tax"),("exert","v.","اعمال کردن","exert pressure"),("exhaust","v.","خسته کردن","exhaust resources"),("exhibit","v.","نشان دادن","exhibit symptoms"),("expand","v.","گسترش دادن","expand operations"),("expedite","v.","تسریع کردن","expedite delivery"),("expel","v.","اخراج کردن","expel diplomats"),("experiment","v.","آزمایش کردن","experiment with methods"),("expire","v.","منقضی شدن","passport expires"),("exploit","v.","بهره‌برداری کردن","exploit resources"),("explore","v.","کاوش کردن","explore options"),("export","v.","صادر کردن","export goods"),("expose","v.","نمایان کردن","expose corruption"),("extend","v.","تمدید کردن","extend the deadline"),
# Adjectives 10
("punitive","adj.","تنبیهی","punitive measures"),("puritanical","adj.","سختگیر","puritanical values"),("purposeful","adj.","هدفمند","purposeful action"),("puzzling","adj.","گیج‌کننده","puzzling question"),("qualified","adj.","واجد شرایط","qualified candidate"),("quantifiable","adj.","قابل اندازه‌گیری","quantifiable results"),("querulous","adj.","بدخلق","querulous tone"),("questionable","adj.","مشکوک","questionable motives"),("rabid","adj.","شدید","rabid fan"),("radiant","adj.","درخشان","radiant smile"),("radical","adj.","رادیکال","radical change"),("rampant","adj.","همه‌گیر","rampant corruption"),("random","adj.","تصادفی","random sample"),("rancid","adj.","گندیده","rancid butter"),("rapacious","adj.","طماع","rapacious greed"),
# Nouns 11
("investor","n.","سرمایه‌گذار","foreign investor"),("irony","n.","کنایه","dramatic irony"),("irrelevance","n.","نامربوطی","complete irrelevance"),("isolation","n.","انزوا","social isolation"),("jargon","n.","اصطلاحات تخصصی","legal jargon"),("jeopardy","n.","خطر","in jeopardy"),("jubilation","n.","شادمانی","widespread jubilation"),("judgment","n.","قضاوت","poor judgment"),("jurisdiction","n.","صلاحیت","federal jurisdiction"),("justification","n.","توجیه","reasonable justification"),("know-how","n.","دانش فنی","technical know-how"),("label","n.","برچسب","designer label"),("laboratory","n.","آزمایشگاه","research laboratory"),("labyrinth","n.","لابیرنت","labyrinth of rules"),("lament","n.","ناله","a lament for"),
# More verbs
("extract","v.","استخراج کردن","extract information"),("extricate","v.","رهایی بخشیدن","extricate from debt"),("fabricate","v.","جعل کردن","fabricate evidence"),("facilitate","v.","تسهیل کردن","facilitate access"),("familiarize","v.","آشنا کردن","familiarize oneself"),("fathom","v.","درک کردن","fathom the depths"),("finalize","v.","نهایی کردن","finalize the deal"),("flourish","v.","شکوفا شدن","flourish in adversity"),("fluctuate","v.","نوسان داشتن","prices fluctuate"),("forecast","v.","پیش‌بینی کردن","forecast demand"),("forfeit","v.","از دست دادن","forfeit the deposit"),("formulate","v.","تدوین کردن","formulate policy"),("fortify","v.","تقویت کردن","fortify defenses"),("foster","v.","پرورش دادن","foster development"),("frustrate","v.","ناامید کردن","frustrate efforts"),
# Adjectives 11
("raucous","adj.","پر سر و صدا","raucous laughter"),("reactionary","adj.","ارتجاعی","reactionary politics"),("realistic","adj.","واقع‌بین","realistic goals"),("reasonable","adj.","معقول","reasonable price"),("reassuring","adj.","اطمینان‌بخش","reassuring words"),("rebellious","adj.","طغیانگر","rebellious teenager"),("receptive","adj.","پذیرا","receptive audience"),("reciprocal","adj.","متقابل","reciprocal agreement"),("reckless","adj.","بی‌پروا","reckless driving"),("reclusive","adj.","گوشه‌گیر","reclusive lifestyle"),("recognizable","adj.","قابل تشخیص","recognizable features"),("redeemable","adj.","قابل بازخرید","redeemable shares"),("redundant","adj.","اضافی","redundant staff"),("referential","adj.","ارجاعی","referential meaning"),("reflective","adj.","بازتابنده","reflective surface"),
# Nouns 12
("legacy","n.","میراث","cultural legacy"),("legality","n.","قانونیت","question the legality"),("legislation","n.","قانون‌گذاری","proposed legislation"),("legitimacy","n.","مشروعیت","challenge legitimacy"),("leniency","n.","گذشت","show leniency"),("leverage","n.","اهرم","financial leverage"),("levy","n.","مالیات","impose a levy"),("liability","n.","مسئولیت","limited liability"),("liberalization","n.","آزادسازی","trade liberalization"),("likelihood","n.","احتمال","strong likelihood"),("limitation","n.","محدودیت","statute of limitations"),("liquidity","n.","نقدینگی","market liquidity"),("litigation","n.","دعوی قضایی","pending litigation"),("logistics","n.","تدارکات","event logistics"),("longevity","n.","طول عمر","human longevity"),
# Verbs - more
("gather","v.","جمع کردن","gather information"),("generalize","v.","تعمیم دادن","generalize from data"),("generate","v.","تولید کردن","generate revenue"),("govern","v.","حکومت کردن","govern wisely"),("guarantee","v.","تضمین کردن","guarantee quality"),("harbor","v.","پناه دادن","harbor suspicions"),("harmonize","v.","هماهنگ کردن","harmonize standards"),("hasten","v.","تسریع کردن","hasten the process"),("heighten","v.","افزایش دادن","heighten awareness"),("hesitate","v.","تردید کردن","hesitate to act"),("hypothesize","v.","فرضیه دادن","hypothesize about"),("idealize","v.","ایده‌آل کردن","idealize the past"),("ignite","v.","آتش زدن","ignite passion"),("illustrate","v.","نشان دادن","illustrate the point"),("immigrate","v.","مهاجرت کردن","immigrate legally"),
# Adjectives 12
("regal","adj.","شاهانه","regal bearing"),("regenerative","adj.","بازسازنده","regenerative medicine"),("regional","adj.","منطقه‌ای","regional cooperation"),("regressive","adj.","پس‌رونده","regressive tax"),("regulatory","adj.","نظارتی","regulatory framework"),("rehabilitative","adj.","توانبخشی","rehabilitative services"),("relentless","adj.","بی‌امان","relentless pursuit"),("relevant","adj.","مرتبط","relevant information"),("reliable","adj.","قابل اعتماد","reliable source"),("reluctant","adj.","مردد","reluctant agreement"),("remarkable","adj.","شگفت‌انگیز","remarkable achievement"),("remedial","adj.","درمانی","remedial action"),("reminiscent","adj.","یادآور","reminiscent of"),("remorseful","adj.","پشیمان","remorseful apology"),("remote","adj.","دورافتاده","remote village"),
# Nouns 13
("magnitude","n.","بزرگی","magnitude of the problem"),("maintenance","n.","نگهداری","maintenance costs"),("malfunction","n.","اختلال","system malfunction"),("malice","n.","بدخواهی","without malice"),("management","n.","مدیریت","senior management"),("mandate","n.","دستور","electoral mandate"),("maneuver","n.","مانور","political maneuver"),("manifestation","n.","تجلی","external manifestation"),("manipulation","n.","دستکاری","genetic manipulation"),("manufacturing","n.","تولید","manufacturing industry"),("marginalization","n.","حاشیه‌رانی","social marginalization"),("materialism","n.","ماده‌گرایی","crass materialism"),("maturation","n.","بلوغ","emotional maturation"),("maxim","n.","اصل","golden maxim"),("mediation","n.","میانجیگری","successful mediation"),
# Verbs more
("immunize","v.","واکسینه کردن","immunize children"),("impair","v.","مختل کردن","impair judgment"),("impart","v.","بخشیدن","impart knowledge"),("impede","v.","مانع شدن","impede progress"),("implement","v.","اجرا کردن","implement changes"),("implicate","v.","درگیر کردن","implicate in crime"),("import","v.","وارد کردن","import goods"),("impose","v.","تحمیل کردن","impose sanctions"),("impoverish","v.","فقیر کردن","impoverish the nation"),("imprison","v.","زندانی کردن","imprison criminals"),("inaugurate","v.","افتتاح کردن","inaugurate the museum"),("incite","v.","برانگیختن","incite violence"),("incline","v.","تمایل داشتن","incline toward"),("incorporate","v.","ادغام کردن","incorporate feedback"),("incur","v.","متحمل شدن","incur losses"),
# Adjectives 13
("renowned","adj.","مشهور","renowned author"),("repetitive","adj.","تکراری","repetitive tasks"),("reprehensible","adj.","نکوهیده","reprehensible conduct"),("reproductive","adj.","تولید مثلی","reproductive rights"),("repugnant","adj.","مشمئزکننده","morally repugnant"),("reputable","adj.","خوشنام","reputable firm"),("residual","adj.","باقی‌مانده","residual effects"),("resilient","adj.","تاب‌آور","resilient economy"),("resolute","adj.","مصمم","resolute determination"),("resonant","adj.","طنین‌انداز","resonant voice"),("resourceful","adj.","زرنگ","resourceful problem-solver"),("respective","adj.","مربوط به هر یک","respective roles"),("responsible","adj.","مسئول","responsible citizen"),("restless","adj.","بی‌قرار","restless night"),("restorative","adj.","بازگرداننده","restorative justice"),
# Nouns 14
("memorandum","n.","یادداشت","internal memorandum"),("menace","n.","تهدید","public menace"),("mentality","n.","ذهنیت","competitive mentality"),("mentorship","n.","راهنمایی","mentorship program"),("merchandise","n.","کالا","retail merchandise"),("mercy","n.","رحمت","show mercy"),("merger","n.","ادغام","corporate merger"),("meritocracy","n.","شایسته‌سالاری","true meritocracy"),("metabolism","n.","متابولیسم","speed up metabolism"),("metaphor","n.","استعاره","powerful metaphor"),("methodology","n.","روش‌شناسی","research methodology"),("migration","n.","مهاجرت","bird migration"),("militancy","n.","مبارزه‌گری","political militancy"),("misconception","n.","باور غلط","common misconception"),("misdemeanor","n.","جنحه","minor misdemeanor"),
# More verbs
("induce","v.","القا کردن","induce sleep"),("inflict","v.","وارد کردن","inflict pain"),("inform","v.","اطلاع دادن","inform the public"),("infringe","v.","نقض کردن","infringe rights"),("inhabit","v.","سکونت کردن","inhabit the area"),("initiate","v.","شروع کردن","initiate proceedings"),("inject","v.","تزریق کردن","inject capital"),("innovate","v.","نوآوری کردن","innovate constantly"),("inspect","v.","بازرسی کردن","inspect premises"),("inspire","v.","الهام بخشیدن","inspire change"),("install","v.","نصب کردن","install equipment"),("instigate","v.","تحریک کردن","instigate a riot"),("institute","v.","برپا کردن","institute reforms"),("integrate","v.","ادغام کردن","integrate systems"),("intensify","v.","تشدید کردن","intensify efforts"),
# More adjectives
("restrictive","adj.","محدودکننده","restrictive policies"),("retaliatory","adj.","تلافی‌جویانه","retaliatory measures"),("retentive","adj.","نگهدارنده","retentive memory"),("retiring","adj.","گوشه‌گیر","retiring personality"),("retroactive","adj.","عطف به گذشته","retroactive pay"),("retrospective","adj.","گذشته‌نگر","retrospective review"),("reverent","adj.","محترمانه","reverent attitude"),("revolutionary","adj.","انقلابی","revolutionary ideas"),("rewarding","adj.","پاداش‌دهنده","rewarding experience"),("rhetorical","adj.","بلاغی","rhetorical device"),("rigid","adj.","سخت","rigid structure"),("rigorous","adj.","دقیق","rigorous testing"),("robust","adj.","قوی","robust system"),("rudimentary","adj.","ابتدایی","rudimentary knowledge"),("ruthless","adj.","بی‌رحم","ruthless efficiency"),
# Nouns 15
("misunderstanding","n.","سو تفاهم","clear misunderstanding"),("mobility","n.","تحرک","social mobility"),("mobilization","n.","بسیج","mass mobilization"),("moderation","n.","اعتدال","in moderation"),("modernization","n.","نوسازی","industrial modernization"),("modification","n.","تغییر","behavior modification"),("momentum","n.","تکانه","gain momentum"),("monopoly","n.","انحصار","state monopoly"),("moratorium","n.","توقف","declare moratorium"),("mortality","n.","مرگ و میر","infant mortality"),("motivation","n.","انگیزه","intrinsic motivation"),("motive","n.","انگیزه","ulterior motive"),("multitude","n.","تعداد زیاد","a multitude of"),("mutation","n.","جهش","genetic mutation"),("mutual","n.","متقابل","mutual fund"),
# Verbs 17
("interact","v.","تعامل داشتن","interact socially"),("intercept","v.","رهگیری","intercept messages"),("interfere","v.","مداخله کردن","interfere with"),("interject","v.","پریدن به حرف","interject a comment"),("interpret","v.","تفسیر کردن","interpret the law"),("interrogate","v.","بازجویی","interrogate suspects"),("interrupt","v.","قطع کردن","interrupt the flow"),("intervene","v.","مداخله کردن","intervene in crisis"),("intimidate","v.","ارعاب کردن","intimidate voters"),("intoxicate","v.","مست کردن","intoxicated by fame"),("intrigue","v.","کنجکاو کردن","intrigue the audience"),("introduce","v.","معرفی کردن","introduce reforms"),("intrude","v.","مزاحمت کردن","intrude on privacy"),("invade","v.","حمله کردن","invade privacy"),("invalidate","v.","باطل کردن","invalidate results"),
# Adjectives 15
("sacred","adj.","مقدس","sacred duty"),("sacrificial","adj.","قربانی","sacrificial offering"),("salient","adj.","برجسته","salient points"),("salutary","adj.","مفید","salutary effect"),("sanctimonious","adj.","قدیس‌مآب","sanctimonious tone"),("sarcastic","adj.","طعنه‌آمیز","sarcastic remark"),("saturate","adj.","اشباع","saturate the market"),("scandalous","adj.","رسوا","scandalous behavior"),("scant","adj.","اندک","scant evidence"),("scathing","adj.","سوزاننده","scathing criticism"),("skeptical","adj.","شکاک","skeptical view"),("slippery","adj.","لغزنده","slippery slope"),("sluggish","adj.","کند","sluggish economy"),("solemn","adj.","جدی","solemn occasion"),("solidarity","n.","همبستگی","show solidarity"),
# Nouns 16
("narrative","n.","روایت","compelling narrative"),("nationalism","n.","ملی‌گرایی","extreme nationalism"),("necessity","n.","ضرورت","basic necessity"),("negligence","n.","سهل‌انگاری","medical negligence"),("negotiation","n.","مذاکره","negotiation skills"),("neutrality","n.","بی‌طرفی","political neutrality"),("nobility","n.","اشراف","the landed nobility"),("nomination","n.","نامزدی","presidential nomination"),("nonchalance","n.","بی‌اعتنایی","feigned nonchalance"),("norm","n.","هنجار","social norm"),("notoriety","n.","بدنامی","gain notoriety"),("novelty","n.","تازگی","novelty value"),("nuance","n.","تفاوت ظریف","cultural nuance"),("nurture","n.","پرورش","nature vs nurture"),("nutrient","n.","ماده مغذی","essential nutrients"),
# Verbs 18
("invest","v.","سرمایه‌گذاری","invest in education"),("investigate","v.","تحقیق کردن","investigate claims"),("invoke","v.","به کار بردن","invoke authority"),("isolate","v.","جدا کردن","isolate variables"),("jeopardize","v.","به خطر انداختن","jeopardize chances"),("justify","v.","توجیه کردن","justify expenses"),("launch","v.","راه انداختن","launch campaign"),("legislate","v.","قانونگذاری","legislate morality"),("liberate","v.","آزاد کردن","liberate the city"),("licence","v.","مجوز دادن","licence technology"),("liquidate","v.","تصفیه کردن","liquidate assets"),("lobby","v.","لابی کردن","lobby congress"),("localize","v.","محدود کردن","localize infection"),("magnify","v.","بزرگنمایی","magnify the issue"),("maintain","v.","حفظ کردن","maintain order"),
# Adjectives 16
("sonorous","adj.","پرطنین","sonorous voice"),("sophisticated","adj.","پیچیده","sophisticated technology"),("spacious","adj.","وسیع","spacious room"),("sparse","adj.","پراکنده","sparse population"),("spontaneous","adj.","خودجوش","spontaneous applause"),("sporadic","adj.","گاه‌به‌گاه","sporadic fighting"),("stagnant","adj.","راکد","stagnant economy"),("stark","adj.","شدید","stark contrast"),("staunch","adj.","استوار","staunch supporter"),("steadfast","adj.","پایدار","steadfast determination"),("steep","adj.","شیب‌دار","steep increase"),("sterling","adj.","عالی","sterling reputation"),("stifling","adj.","خفه‌کننده","stifling heat"),("strenuous","adj.","پر زحمت","strenuous exercise"),("stringent","adj.","سختگیرانه","stringent regulations"),
# Nouns 17
("obligation","n.","تعهد","legal obligation"),("obscurity","n.","گمنامی","live in obscurity"),("obsession","n.","وسواس","unhealthy obsession"),("obstacle","n.","مانع","overcome obstacles"),("occupation","n.","شغل","dangerous occupation"),("offspring","n.","فرزند","raise offspring"),("omen","n.","نشانه","good omen"),("onset","n.","آغاز","onset of winter"),("onslaught","n.","حمله","verbal onslaught"),("opacity","n.","تیرگی","market opacity"),("operation","n.","عملیات","rescue operation"),("opinion","n.","نظر","public opinion"),("opponent","n.","حریف","political opponent"),("oppression","n.","ظلم","racial oppression"),("optimism","n.","خوش‌بینی","cautious optimism"),
# Verbs 19
("manipulate","v.","دستکاری","manipulate data"),("manufacture","v.","ساخت","manufacture goods"),("marginalize","v.","حاشیه راندن","marginalize minorities"),("maximize","v.","حداکثر کردن","maximize profit"),("mechanize","v.","مکانیزه کردن","mechanize farming"),("mediate","v.","میانجیگری","mediate disputes"),("memorize","v.","حفظ کردن","memorize facts"),("merge","v.","ادغام شدن","merge companies"),("migrate","v.","مهاجرت کردن","migrate south"),("minimize","v.","کمترین کردن","minimize risks"),("misinterpret","v.","بد فهمیدن","misinterpret signals"),("mislead","v.","گمراه کردن","mislead consumers"),("moderate","v.","اعتدال کردن","moderate debate"),("modernize","v.","مدرن کردن","modernize infrastructure"),("modify","v.","تغییر دادن","modify behavior"),
# Nouns 18
("orientation","n.","جهت‌گیری","sexual orientation"),("originality","n.","اصالت","artistic originality"),("orthodoxy","n.","ارتدکس","religious orthodoxy"),("oscillation","n.","نوسان","price oscillation"),("ostracism","n.","طرد","social ostracism"),("outbreak","n.","شیوع","disease outbreak"),("outcome","n.","نتیجه","positive outcome"),("outcry","n.","اعتراض","public outcry"),("outlook","n.","چشم‌انداز","positive outlook"),("output","n.","خروجی","production output"),("outrage","n.","خشم","public outrage"),("outsider","n.","غریبه","feel like outsider"),("overhaul","n.","تعمیرات اساسی","complete overhaul"),("overlap","n.","همپوشانی","significant overlap"),("oversight","n.","نظارت","regulatory oversight"),
# Verbs 20
("monitor","v.","نظارت کردن","monitor progress"),("monopolize","v.","انحصار","monopolize market"),("motivate","v.","انگیزه دادن","motivate employees"),("negotiate","v.","مذاکره","negotiate terms"),("neutralize","v.","خنثی کردن","neutralize threats"),("normalize","v.","عادی کردن","normalize ties"),("notify","v.","اطلاع دادن","notify authorities"),("nullify","v.","باطل کردن","nullify agreement"),("obey","v.","اطاعت کردن","obey orders"),("object","v.","اعتراض","object strongly"),("obligate","v.","مکلّف کردن","obligate by contract"),("observe","v.","مشاهده کردن","observe behavior"),("obstruct","v.","مسدود کردن","obstruct justice"),("obtain","v.","به دست آوردن","obtain permission"),("occupy","v.","اشغال کردن","occupy territory"),
# Nouns 19
("oversight","n.","نظارت","congressional oversight"),("overture","n.","پیشنهاد","peace overtures"),("overview","n.","نمای کلی","provide overview"),("ownership","n.","مالکیت","home ownership"),("pacifism","n.","صلح‌طلبی","commitment to pacifism"),("pamphlet","n.","جزوه","political pamphlet"),("panacea","n.","داروی همه‌کاره","not a panacea"),("pandemic","n.","همه‌گیری جهانی","global pandemic"),("panic","n.","وحشت","mass panic"),("parable","n.","تمثیل","biblical parable"),("parade","n.","رژه","victory parade"),("paradigm","n.","الگو","paradigm shift"),("paradox","n.","تناقض","logical paradox"),("parallel","n.","موازی","historical parallel"),("parameter","n.","پارامتر","define parameters"),
# Verbs 21
("offend","v.","رنجاندن","offend sensibilities"),("operate","v.","عمل کردن","operate machinery"),("oppose","v.","مخالفت کردن","oppose vigorously"),("orchestrate","v.","هماهنگ کردن","orchestrate campaign"),("organize","v.","سازماندهی","organize event"),("originate","v.","سرچشمه گرفتن","originate from"),("outlaw","v.","غیرقانونی اعلام کردن","outlaw discrimination"),("outline","v.","طرح‌ریزی","outline plans"),("outweigh","v.","برتری داشتن","benefits outweigh risks"),("overcome","v.","غلبه کردن","overcome obstacles"),("overestimate","v.","بیش از حد برآورد","overestimate ability"),("overlap","v.","همپوشانی","roles overlap"),("overlook","v.","نادیده گرفتن","overlook details"),("overrule","v.","لغو کردن","overrule objection"),("oversee","v.","نظارت","oversee operations"),
# More adjectives
("stubborn","adj.","لجباز","stubborn resistance"),("stunning","adj.","خیره‌کننده","stunning view"),("sturdy","adj.","محکم","sturdy construction"),("subdued","adj.","ملایم","subdued lighting"),("subjective","adj.","ذهنی","subjective opinion"),("sublime","adj.","عالی","sublime beauty"),("submissive","adj.","تسلیم","submissive attitude"),("subordinate","adj.","فرعی","subordinate role"),("subsequent","adj.","بعدی","subsequent events"),("substantial","adj.","قابل توجه","substantial increase"),("substantive","adj.","ماهوی","substantive issue"),("subversive","adj.","خرابکارانه","subversive activities"),("successive","adj.","متوالی","successive generations"),("succinct","adj.","موجز","succinct summary"),("sufficient","adj.","کافی","sufficient evidence"),
# Nouns 20
("parity","n.","برابری","gender parity"),("parody","n.","هجو","a parody of justice"),("participation","n.","مشارکت","civic participation"),("partisanship","n.","جانب‌داری","political partisanship"),("passion","n.","شور","speak with passion"),("patent","n.","حق اختراع","file a patent"),("pathology","n.","آسیب‌شناسی","clinical pathology"),("patriotism","n.","میهن‌پرستی","blind patriotism"),("patronage","n.","حمایت","political patronage"),("peacekeeping","n.","حفظ صلح","UN peacekeeping"),("penalty","n.","مجازات","death penalty"),("penetration","n.","نفوذ","market penetration"),("perception","n.","ادراک","public perception"),("perfection","n.","کمال","strive for perfection"),("performance","n.","عملکرد","job performance"),
# Verbs 22
("overthrow","v.","سرنگون کردن","overthrow regime"),("overwhelm","v.","غرق کردن","overwhelm with emotion"),("participate","v.","شرکت کردن","participate actively"),("perceive","v.","درک کردن","perceive threat"),("perfect","v.","بهبود بخشیدن","perfect skills"),("perform","v.","اجرا کردن","perform duties"),("permit","v.","اجازه دادن","permit access"),("persevere","v.","استقامت کردن","persevere through"),("persist","v.","ادامه دادن","symptoms persist"),("persuade","v.","متقاعد کردن","persuade voters"),("pertain","v.","مربوط بودن","documents pertaining to"),("pioneer","v.","پیشگام بودن","pioneer research"),("placate","v.","آرام کردن","placate critics"),("polish","v.","صیقل دادن","polish skills"),("portray","v.","به تصویر کشیدن","portray accurately"),
# Adjectives 18
("superficial","adj.","سطحی","superficial wound"),("superfluous","adj.","زائد","superfluous details"),("superior","adj.","برتر","superior quality"),("supersonic","adj.","مافوق صوت","supersonic speed"),("superstitious","adj.","خرافاتی","superstitious beliefs"),("supple","adj.","منعطف","supple leather"),("supportive","adj.","حامی","supportive environment"),("suppressive","adj.","سرکوبگر","suppressive regime"),("supreme","adj.","عالی","supreme authority"),("sure","adj.","مطمئن","sure evidence"),("surging","adj.","در حال افزایش","surging demand"),("surplus","adj.","مازاد","surplus value"),("surprising","adj.","غافلگیرکننده","surprising result"),("surreal","adj.","سوررئال","surreal experience"),("susceptible","adj.","مستعد","susceptible to"),
# Nouns 21
("perimeter","n.","محیط","security perimeter"),("periphery","n.","حاشیه","on the periphery"),("permanence","n.","دوام","sense of permanence"),("permeability","n.","نفوذپذیری","membrane permeability"),("permission","n.","اجازه","grant permission"),("perpetuation","n.","تداوم","perpetuation of myths"),("perseverance","n.","استقامت","human perseverance"),("persistence","n.","پافشاری","dogged persistence"),("persona","n.","شخصیت","public persona"),("personality","n.","شخصیت","charismatic personality"),("perspective","n.","دیدگاه","gain perspective"),("persuasion","n.","متقاعدسازی","powers of persuasion"),("pervasiveness","n.","گستردگی","pervasiveness of"),("petition","n.","دادخواست","sign a petition"),("phenomenon","n.","پدیده","natural phenomenon"),
# Verbs 23
("postpone","v.","به تعویق انداختن","postpone decision"),("precede","v.","پیشی گرفتن","precede the event"),("predict","v.","پیش‌بینی کردن","predict outcome"),("predominate","v.","غالب بودن","predominate in"),("prefer","v.","ترجیح دادن","prefer option"),("preoccupy","v.","مشغول کردن","preoccupy mind"),("prepare","v.","آماده کردن","prepare report"),("prescribe","v.","تجویز کردن","prescribe treatment"),("preserve","v.","حفظ کردن","preserve heritage"),("preside","v.","ریاست کردن","preside over meeting"),("press","v.","فشار آوردن","press charges"),("presume","v.","فرض کردن","presume innocence"),("prevail","v.","غالب شدن","justice prevailed"),("prevent","v.","جلوگیری کردن","prevent disease"),("proceed","v.","ادامه دادن","proceed carefully"),
# Adjectives 19
("sustainable","adj.","پایدار","sustainable growth"),("swift","adj.","سریع","swift response"),("symbolic","adj.","نمادین","symbolic gesture"),("sympathetic","adj.","همدل","sympathetic ear"),("symptomatic","adj.","نشانه‌دار","symptomatic of"),("tactical","adj.","تاکتیکی","tactical retreat"),("tangible","adj.","ملموس","tangible results"),("technical","adj.","فنی","technical expertise"),("temperate","adj.","معتدل","temperate climate"),("temporary","adj.","موقتی","temporary solution"),("tenacious","adj.","سرسخت","tenacious grip"),("tentative","adj.","آزمایشی","tentative steps"),("terminally","adv.","نهایی","terminally ill"),("territorial","adj.","سرزمینی","territorial dispute"),("terse","adj.","خلاصه","terse reply"),
# Nouns 22
("philanthropy","n.","نیکوکاری","corporate philanthropy"),("philosophy","n.","فلسفه","political philosophy"),("phony","n.","جعلی","expose as phony"),("physique","n.","جثه","athletic physique"),("plagiarism","n.","سرقت ادبی","accused of plagiarism"),("plight","n.","وضعیت بد","plight of refugees"),("pluralism","n.","کثرت‌گرایی","political pluralism"),("poetry","n.","شعر","modern poetry"),("polarity","n.","قطبیت","political polarity"),("polemic","n.","جدل","engage in polemic"),("policy","n.","سیاست","foreign policy"),("polish","n.","صیقل","add polish"),("popularity","n.","محبوبیت","widespread popularity"),("populism","n.","پوپولیسم","right-wing populism"),("portfolio","n.","سبد","investment portfolio"),
# Verbs 24
("proclaim","v.","اعلام کردن","proclaim victory"),("produce","v.","تولید کردن","produce results"),("prohibit","v.","منع کردن","prohibit smoking"),("project","v.","پیش‌بینی کردن","project growth"),("proliferate","v.","گسترش یافتن","proliferate rapidly"),("promote","v.","ترویج کردن","promote equality"),("promulgate","v.","اعلام کردن","promulgate regulations"),("propagate","v.","گسترش دادن","propagate ideas"),("propel","v.","به جلو راندن","propel forward"),("propose","v.","پیشنهاد دادن","propose changes"),("prosecute","v.","تعقیب قانونی","prosecute offenders"),("protect","v.","حفاظت کردن","protect environment"),("protest","v.","اعتراض کردن","protest decision"),("provide","v.","ارائه کردن","provide services"),("provoke","v.","برانگیختن","provoke reaction"),
# Nouns 23
("portfolio","n.","سبد","investment portfolio"),("pragmatism","n.","عمل‌گرایی","political pragmatism"),("precaution","n.","احتیاط","safety precautions"),("precedent","n.","سابقه","legal precedent"),("precision","n.","دقت","surgical precision"),("predator","n.","شکارچی","sexual predator"),("predicament","n.","بن‌بست","in a predicament"),("prediction","n.","پیش‌بینی","accurate prediction"),("predominance","n.","غلبه","cultural predominance"),("preference","n.","ترجیح","personal preference"),("prejudice","n.","تعصب","racial prejudice"),("prelude","n.","پیش‌درآمد","prelude to war"),("premise","n.","مقدمه","basic premise"),("preoccupation","n.","دغدغه","main preoccupation"),("prerequisite","n.","پیش‌نیاز","necessary prerequisite"),
# Adjectives 20
("therapeutic","adj.","درمانی","therapeutic benefits"),("thorough","adj.","دقیق","thorough investigation"),("thought-provoking","adj.","تفکربرانگیز","thought-provoking film"),("thrifty","adj.","صرفه‌جو","thrifty shopper"),("thrilling","adj.","هیجان‌انگیز","thrilling experience"),("tolisome","adj.","خسته‌کننده","tolisome journey"),("tolerable","adj.","قابل تحمل","tolerable pain"),("topical","adj.","موضوع روز","topical issue"),("totalitarian","adj.","تمامیت‌خواه","totalitarian regime"),("tough","adj.","سخت","tough decision"),("toxic","adj.","سمی","toxic relationship"),("tragic","adj.","غمگین","tragic accident"),("tranquil","adj.","آرام","tranquil setting"),("transformative","adj.","دگرگون‌کننده","transformative power"),("transient","adj.","گذرا","transient population"),
# Nouns 24
("preservation","n.","حفظ","historical preservation"),("prestige","n.","پرستیژ","social prestige"),("presumption","n.","فرض","presumption of innocence"),("prevalence","n.","شیوع","prevalence of"),("prevention","n.","پیشگیری","crime prevention"),("prey","n.","شکار","fall prey to"),("principle","n.","اصل","moral principle"),("priority","n.","اولویت","top priority"),("probe","n.","کاوشگر","space probe"),("procedure","n.","روش","standard procedure"),("proceeds","n.","عواید","sale proceeds"),("processing","n.","پردازش","data processing"),("proclamation","n.","اعلامیه","royal proclamation"),("prodigy","n.","نابغه","child prodigy"),("productivity","n.","بهره‌وری","workplace productivity"),
# Verbs 25
("publicize","v.","تبلیغ کردن","publicize the event"),("purchase","v.","خریداری کردن","purchase property"),("purify","v.","تصفیه کردن","purify water"),("pursue","v.","دنبال کردن","pursue justice"),("qualify","v.","واجد شرایط","qualify for"),("quantify","v.","کمی کردن","quantify impact"),("question","v.","زیر سؤال بردن","question authority"),("rally","v.","جمع شدن","rally support"),("ratify","v.","تصویب کردن","ratify treaty"),("rationalize","v.","توجیه منطقی","rationalize behavior"),("reactivate","v.","دوباره فعال کردن","reactivate account"),("reassess","v.","دوباره ارزیابی","reassess strategy"),("rebuke","v.","سرزنش کردن","rebuke sharply"),("recall","v.","به یاد آوردن","recall details"),("reckon","v.","محاسبه کردن","reckon with"),
# Adjectives 21
("transparent","adj.","شفاف","transparent process"),("traumatic","adj.","تروماتیک","traumatic experience"),("treacherous","adj.","خائنانه","treacherous road"),("tremendous","adj.","عظیم","tremendous success"),("trenchant","adj.","برنده","trenchant analysis"),("trivial","adj.","پیش‌پاافتاده","trivial matter"),("tumultuous","adj.","پرآشوب","tumultuous relationship"),("typical","adj.","معمولی","typical example"),("ubiquitous","adj.","همه‌جا","ubiquitous technology"),("ultimate","adj.","نهایی","ultimate goal"),("unambiguous","adj.","بی‌ابهام","unambiguous answer"),("unanimous","adj.","یک‌صدا","unanimous decision"),("unavoidable","adj.","گریزناپذیر","unavoidable delay"),("unbearable","adj.","غیرقابل تحمل","unbearable pain"),("unbiased","adj.","بی‌طرف","unbiased opinion"),
# Nouns 25
("proficiency","n.","مهارت","language proficiency"),("profitability","n.","سودآوری","long-term profitability"),("prognosis","n.","پیش‌آگهی","bleak prognosis"),("progression","n.","پیشرفت","disease progression"),("prohibition","n.","منع","prohibition of"),("projection","n.","پیش‌بینی","economic projection"),("proliferation","n.","گسترش","nuclear proliferation"),("propaganda","n.","تبلیغات","war propaganda"),("propensity","n.","تمایل","propensity for"),("proportion","n.","نسبت","in proportion to"),("proposition","n.","پیشنهاد","business proposition"),("prosecution","n.","تعقیب","face prosecution"),("prospect","n.","چشم‌انداز","job prospects"),("prosperity","n.","رفاه","economic prosperity"),("protection","n.","حفاظت","environmental protection"),
# More verbs
("recognize","v.","شناختن","recognize achievement"),("recommend","v.","توصیه کردن","recommend changes"),("reconcile","v.","آشتی دادن","reconcile differences"),("reconstruct","v.","بازسازی","reconstruct events"),("recount","v.","بازگو کردن","recount story"),("recover","v.","بهبود یافتن","recover losses"),("rectify","v.","اصلاح کردن","rectify mistake"),("redeem","v.","بازخرید کردن","redeem voucher"),("redirect","v.","تغییر مسیر","redirect resources"),("reduce","v.","کاهش دادن","reduce emissions"),("reestablish","v.","دوباره برقرار","reestablish relations"),("refine","v.","تصفیه کردن","refine process"),("reform","v.","اصلاح کردن","reform system"),("refrain","v.","خودداری کردن","refrain from"),("refresh","v.","تازه کردن","refresh memory"),
# Adjectives 22
("uncommon","adj.","نادر","uncommon occurrence"),("uncompromising","adj.","سختگیر","uncompromising stance"),("unconscious","adj.","ناخودآگاه","unconscious bias"),("unconstitutional","adj.","غیرقانونی اساسی","unconstitutional law"),("uncontrolled","adj.","کنترل‌نشده","uncontrolled growth"),("unconventional","adj.","غیرمتعارف","unconventional approach"),("undeniable","adj.","غیرقابل انکار","undeniable truth"),("underdeveloped","adj.","توسعه‌نیافته","underdeveloped region"),("underlying","adj.","زمینه‌ای","underlying cause"),("undermined","adj.","تضعیف‌شده","undermined authority"),("underprivileged","adj.","محروم","underprivileged children"),("understandable","adj.","قابل فهم","understandable concern"),("undesirable","adj.","نامطلوب","undesirable effects"),("undisputed","adj.","مسلم","undisputed champion"),("unemployed","adj.","بیکار","unemployed workers"),
# Nouns 26
("protocol","n.","پروتکل","safety protocol"),("prototype","n.","نمونه اولیه","working prototype"),("provocation","n.","تحریک","under provocation"),("prowess","n.","مهارت","athletic prowess"),("proximity","n.","نزدیکی","geographic proximity"),("prudence","n.","احتیاط","financial prudence"),("psychology","n.","روانشناسی","human psychology"),("publication","n.","انتشار","peer-reviewed publication"),("publicity","n.","تبلیغات","negative publicity"),("punctuality","n.","وقت‌شناسی","demand punctuality"),("punishment","n.","مجازات","capital punishment"),("pupil","n.","شاگرد","teacher and pupil"),("purchasing","n.","خرید","purchasing power"),("purification","n.","تصفیه","water purification"),("pursuit","n.","دنبال","pursuit of happiness"),
# More adjectives
("unethical","adj.","غیراخلاقی","unethical behavior"),("uneven","adj.","ناهموار","uneven distribution"),("unexpected","adj.","غیرمنتظره","unexpected twist"),("unfair","adj.","ناعادلانه","unfair advantage"),("unfavorable","adj.","نامساعد","unfavorable conditions"),("unforgettable","adj.","فراموش‌نشدنی","unforgettable experience"),("unforeseen","adj.","پیش‌بینی‌نشده","unforeseen consequences"),("unfortunate","adj.","تأسف‌بار","unfortunate incident"),("unified","adj.","متحد","unified approach"),("unilateral","adj.","یک‌جانبه","unilateral action"),("unimaginable","adj.","غیرقابل تصور","unimaginable horror"),("unimportant","adj.","بی‌اهمیت","unimportant details"),("uninformed","adj.","ناآگاه","uninformed opinion"),("uninhabited","adj.","غیرمسکونی","uninhabited island"),("unintelligible","adj.","غیرقابل فهم","unintelligible speech"),
# Nouns 27
("qualification","n.","صلاحیت","professional qualification"),("quantum","n.","کوانتوم","quantum physics"),("quarantine","n.","قرنطینه","in quarantine"),("questionnaire","n.","پرسشنامه","fill questionnaire"),("quota","n.","سهمیه","import quota"),("quotation","n.","نقل قول","direct quotation"),("racism","n.","نژادپرستی","institutional racism"),("radiance","n.","درخشندگی","sun's radiance"),("radiation","n.","تشعشع","nuclear radiation"),("radicalism","n.","رادیکالیسم","political radicalism"),("rally","n.","تجمع","political rally"),("ramification","n.","پیامد","legal ramifications"),("rapport","n.","ارتباط خوب","build rapport"),("ratification","n.","تصویب","treaty ratification"),("rationale","n.","دلیل منطقی","explain rationale"),
# Adjectives 24
("unilateral","adj.","یک‌جانبه","unilateral decision"),("unique","adj.","منحصر به فرد","unique opportunity"),("universal","adj.","جهانی","universal values"),("unjust","adj.","ناعادلانه","unjust laws"),("unlimited","adj.","نامحدود","unlimited potential"),("unload","v.","تخلیه کردن","unload cargo"),("unnecessary","adj.","غیرضروری","unnecessary risk"),("unorthodox","adj.","غیرمتعارف","unorthodox methods"),("unpopular","adj.","نامحبوب","unpopular opinion"),("unprecedented","adj.","بی‌سابقه","unprecedented crisis"),("unpredictable","adj.","غیرقابل پیش‌بینی","unpredictable weather"),("unprofessional","adj.","غیرحرفه‌ای","unprofessional conduct"),("unqualified","adj.","غیرمجاز","unqualified teacher"),("unquestionable","adj.","غیرقابل تردید","unquestionable integrity"),("unrealistic","adj.","غیرواقعی","unrealistic expectations"),
]

# Process all bulk entries
for en, pos, fa, ex in BULK:
    W(en, pos, fa, ex)

# Now insert into the file
with open(FILE, 'r', encoding='utf-8') as f:
    content = f.read()

target = "];\n\nconst WORDS_PER_DAY"
if target in content:
    idx = content.rfind(target)
    before = content[:idx]
    after = content[idx:]
    
    new_words = ",\n".join(words)
    new_content = before + new_words + "\n" + after
    
    with open(FILE, 'w', encoding='utf-8') as f:
        f.write(new_content)
    
    initial_count = content.count("['")
    added = len(words)
    print(f"Added {added} new words")
    print(f"Estimated total: ~{initial_count + added}")
else:
    print(f"Could not find insertion point")
    # Debug: show end of file
    print(content[-300:])
