#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Add more words to the existing word database."""

FILE = r"D:\dev\DLZLAB\wordApp\app.html"

def esc(s):
    return s.replace("\\", "\\\\").replace("'", "\\'").replace('"', '\\"')

def entry(en, pos, fa, ex):
    return f"['{esc(en)}','{pos}','{esc(fa)}','{esc(ex)}']"

words = []
W = lambda en, pos, fa, ex: words.append(entry(en, pos, fa, ex))

# ===== More C2 words organized by theme =====
# (continuing where gen.py left off)

# Advanced Communication
W("articulate","adj.","خوش‌بیان","She is an articulate and persuasive speaker.")
W("convey","v.","انتقال دادن، رساندن","The poem conveys a profound sense of loss and longing.")
W("eloquence","n.","فصاحت، شیوایی","She spoke with great eloquence and passion.")
W("florid","adj.","پرگل، پرزرق و برق","The author's florid prose style was not to everyone's taste.")
W("garrulous","adj.","وراج، پرحرف","The garrulous old man kept everyone entertained with his stories.")
W("grandiloquent","adj.","پرمغز، مبالغه‌آمیز","His grandiloquent speech failed to impress the audience.")
W("grave","adj.","جدی، مهم","The situation is becoming increasingly grave.")
W("laconic","adj.","کم‌گفتار، موجز","His laconic reply was typical of his no-nonsense attitude.")
W("loquacious","adj.","پرحرف، خوش‌صحبت","The loquacious tour guide kept up a steady stream of chatter.")
W("orator","n.","سخنور، خطیب","Cicero was one of the greatest orators in history.")
W("pithy","adj.","مغزدار، پرمعنی","The journalist was known for her pithy commentary.")
W("ponderous","adj.","سنگین، کسالت‌بار","The lecture was ponderous and difficult to follow.")
W("prolix","adj.","طولانی، ملال‌آور","His prolix writing style tries the patience of the reader.")
W("succinct","adj.","موجز، کوتاه و مفید","Please keep your report succinct and to the point.")
W("tirade","n.","سخنرانی تند، بدگویی","He launched into a lengthy tirade against the government.")
W("utter","v.","بر زبان آوردن، ادا کردن","She didn't utter a single word during the entire meeting.")
W("vociferous","adj.","پر سر و صدا، فریادزن","The vociferous protests eventually led to change.")
W("voluble","adj.","روان‌گو، خوش‌صحبت","He was a voluble and engaging conversationalist.")
W("discursive","adj.","حاشیه‌رو، نامرتبط","The essay was too discursive and lacked focus.")
W("truism","n.","بدیهی‌گویی","It is a truism that hard work leads to success.")

# Advanced emotion and psychology
W("affliction","n.","مصیبت، رنج","She bore her affliction with remarkable dignity.")
W("angst","n.","اضطراب، نگرانی عمیق","The novel captures the existential angst of modern life.")
W("apathy","n.","بی‌تفاوتی، بی‌حسی","The election was marked by widespread voter apathy.")
W("capricious","adj.","دمدمی‌مزاج، متغیر","The weather in spring can be quite capricious.")
W("contrition","n.","پشیمانی، ندامت","He expressed deep contrition for his actions.")
W("deference","n.","احترام، تکریم","In deference to local customs, they removed their shoes.")
W("deprecate","v.","نکوهش کردن، اعتراض کردن","The teacher deprecated the student's lazy attitude.")
W("despondent","adj.","ناامید، دلسرد","She felt despondent after failing the exam.")
W("disdain","n.","تحقیر، بی‌اعتنایی","She looked at the offer with obvious disdain.")
W("dread","n.","ترس شدید، هراس","He lived in constant dread of being discovered.")
W("elation","n.","شادی و هیجان شدید","The crowd was filled with elation at the news of victory.")
W("ennui","n.","احساس ملال، کسالت","The wealthy aristocrat suffered from a sense of profound ennui.")
W("enrapture","v.","مجذوب کردن، مسحور کردن","The audience was enraptured by the performance.")
W("epiphany","n.","آشکارشدن، درک ناگهانی","The idea came to him in a sudden epiphany.")
W("frenzy","n.","هیجان شدید، جنون","The crowd reached a frenzy of excitement.")
W("gratitude","n.","سپاسگزاری، شکرگزاری","She expressed her sincere gratitude to the staff.")
W("hubris","n.","غرور، تکبر","His hubris eventually led to his downfall.")
W("indignation","n.","خشم، عصبانیت از بی‌عدالتی","The new law provoked widespread public indignation.")
W("ire","n.","خشم، غضب","The decision provoked the ire of local residents.")
W("jubilant","adj.","شادمان، مسرور","The fans were jubilant after the team's victory.")
W("lassitude","n.","خستگی، کسالت","A feeling of lassitude overcame her in the afternoon heat.")
W("malice","n.","بدخواهی، کینه","There was no malice intended in his remark.")
W("nostalgia","n.","دلتنگی، نوستالژی","She was filled with nostalgia for her childhood home.")
W("pathos","n.","اندوه، ترحم‌انگیزی","The film's final scene was full of pathos.")
W("penchant","n.","گرایش، علاقه شدید","She has a penchant for expensive jewelry.")
W("procrastinate","v.","به تعویق انداختن، تنبلی کردن","Stop procrastinating and get on with your work!")
W("rancor","n.","کینه، دشمنی","They parted without any rancor.")
W("reprehensible","adj.","سرزنش‌آمیز، نکوهیده","His behavior was morally reprehensible.")
W("repugnance","n.","انزجار، بیزاری","She felt a deep repugnance at the sight of cruelty.")
W("resignation","n.","تسلیم، پذیرش","He accepted his fate with quiet resignation.")
W("reverie","n.","خیال‌پردازی، رویا","She was lost in a pleasant reverie.")
W("sagacity","n.","خرد، دوراندیشی","The old man was known for his sagacity and sound judgment.")
W("solicitous","adj.","نگران، مراقب","The solicitous nurse checked on the patient every hour.")
W("stoic","adj.","رواقی، بی‌احساس","He bore the pain with stoic calm.")
W("trepidation","n.","ترس و لرز، نگرانی","She approached the interview with some trepidation.")
W("wistful","adj.","دل‌تنگی، حسرت‌بار","She cast a wistful glance at the departing train.")
W("zeal","n.","شور و شوق، غیرت","The young missionary preached with religious zeal.")
W("ardor","n.","شور، حرارت","His political ardor was unmistakable.")
W("fervor","n.","حرارت، شوریدگی","The crowd sang with patriotic fervor.")
W("vehemence","n.","شدت، تندی","He argued with great vehemence.")

# Advanced intellectual / academic
W("acumen","n.","تیزبینی، زیرکی","Her business acumen was widely respected.")
W("astute","adj.","زیرک، باهوش","He was an astute observer of human nature.")
W("perspicacious","adj.","تیزبین، نکته‌سنج","She made a perspicacious comment about the situation.")
W("erudite","adj.","دانشمند، باسواد","The erudite professor was an expert on ancient history.")
W("sagacious","adj.","خردمند، دوراندیش","The sagacious leader avoided a potentially disastrous conflict.")
W("cerebral","adj.","مغزی، فکری","The film was more cerebral than emotional.")
W("conjecture","n.","حدس، گمان","The origin of the ancient artifact is a matter of conjecture.")
W("cognizant","adj.","آگاه، مطلع","We must remain cognizant of the risks involved.")
W("dubious","adj.","مشکوک، تردیدآمیز","The claim is of dubious validity.")
W("equivocal","adj.","مبهم، دوپهلو","His equivocal answer satisfied no one.")
W("esoteric","adj.","غامض، پیچیده","The subject matter was too esoteric for the general audience.")
W("fathom","v.","عمیقاً فهمیدن","I still cannot fathom why she left.")
W("fallacious","adj.","غلط، گمراه‌کننده","The argument is based on fallacious reasoning.")
W("meticulous","adj.","موشکاف، دقیق","The meticulous craftsman paid attention to every detail.")
W("pedantic","adj.","خودنما، فضل‌فروش","His pedantic corrections annoyed everyone.")
W("profound","adj.","عمیق، ژرف","The article offers a profound analysis of the problem.")
W("recondite","adj.","عمیق، دیریاب","The subject is recondite and not easily understood.")
W("sage","n.","حکیم، فرزانه","The village elders were regarded as sages.")
W("sophistry","n.","مغالطه‌آمیز، سفسطه","The politician's argument was pure sophistry.")
W("vindicate","v.","تأیید کردن، ثابت کردن","The evidence vindicated her completely.")
W("amplify","v.","گسترش دادن، تقویت کردن","We need to amplify our efforts to reach the target.")
W("apportion","v.","تقسیم کردن، سهم‌بندی","The funds were apportioned among the various departments.")
W("assimilate","v.","جذب کردن، هضم کردن","It took time to assimilate all the new information.")
W("chronicle","v.","ثبت کردن، وقایع‌نگاری","The book chronicles the history of the region.")
W("collate","v.","مقایسه و مرتب‌سازی","The data needs to be collated before analysis.")
W("delineate","v.","ترسیم کردن، تشریح کردن","The report clearly delineates the steps we need to take.")
W("disseminate","v.","منتشر کردن، اشاعه دادن","The organization's mission is to disseminate knowledge.")
W("elucidate","v.","روشن ساختن، توضیح دادن","The teacher elucidated the difficult passage for the students.")
W("embroil","v.","گرفتار کردن، درگیر کردن","He found himself embroiled in a heated argument.")
W("expedite","v.","تسریع کردن، سرعت بخشیدن","We must expedite the delivery of supplies.")
W("extrapolate","v.","برون‌یابی کردن","We can extrapolate future trends from current data.")
W("fathom","v.","عمیقاً درک کردن","It is hard to fathom the scale of the universe.")
W("forebode","v.","پیش‌گویی کردن، شوم بودن","The dark clouds forebode a violent storm.")
W("impart","v.","بخشیدن، انتقال دادن","A good teacher imparts wisdom as well as facts.")
W("indict","v.","کیفرخواست دادن، متهم کردن","The grand jury indicted the senator on corruption charges.")
W("infer","v.","استنتاج کردن، نتیجه گرفتن","What can we infer from the available evidence?")
W("presage","v.","نشانه بودن، پیش‌گویی کردن","The economic indicators presage a downturn.")
W("purport","v.","ادعا کردن، نشان دادن","The document purports to be an official government report.")
W("ratify","v.","تصویب کردن، تأیید کردن","The treaty was ratified by all member states.")
W("substantiate","v.","اثبات کردن، تأیید کردن","Can you substantiate your claims with evidence?")

# Advanced ethics and morality
W("altruism","n.","نوع‌دوستی، ایثار","His actions were motivated by pure altruism.")
W("amoral","adj.","غیراخلاقی (بدون حس اخلاقی)","Young children are considered amoral.")
W("beneficent","adj.","خیررسان، نیکوکار","The beneficent donor funded the new hospital wing.")
W("benevolent","adj.","خیرخواه، مهربان","The benevolent ruler was loved by his people.")
W("conscientious","adj.","باوجدان، وظیفه‌شناس","She is a conscientious and reliable employee.")
W("decorum","n.","اخلاق، نجابت","The ceremony was conducted with great decorum.")
W("dissolute","adj.","فاسد، هرزه","He led a dissolute life of pleasure and excess.")
W("edify","v.","آموختن، پرورش دادن","The documentary was both entertaining and edifying.")
W("equitable","adj.","عادلانه، منصفانه","We need an equitable distribution of resources.")
W("ethical","adj.","اخلاقی","The company is committed to ethical business practices.")
W("frivolous","adj.","سطحی، سبک","The lawsuit was dismissed as frivolous.")
W("impeccable","adj.","بی‌نقص، معصوم","Her taste in art is impeccable.")
W("impiety","n.","بی‌دینی، ناپرهیزگاری","The act was considered an act of impiety.")
W("impunity","n.","مصونیت از مجازات","He seemed to break the rules with impunity.")
W("iniquitous","adj.","ناعادلانه، ستمگرانه","The iniquitous system oppressed the poor.")
W("malevolent","adj.","بدخواه، کینه‌توز","He gave her a malevolent stare.")
W("mendacious","adj.","دروغگو، ناراست","The mendacious politician lost all credibility.")
W("mercenary","adj.","مزدور، پول‌پرست","His motives were purely mercenary.")
W("nepotism","n.","خویشاوندسالاری","The company was rife with nepotism.")
W("noble","adj.","شریف، بزرگوار","It was a noble gesture to donate his winnings.")
W("perfidious","adj.","خیانتکار، بدعهد","The perfidious ally betrayed the agreement.")
W("pious","adj.","متقی، پرهیزگار","She was a pious woman who attended church regularly.")
W("probity","n.","درستی، صداقت","The judge was known for his probity and integrity.")
W("propriety","n.","شایستگی، اخلاق","She behaved with the utmost propriety.")
W("remorse","n.","پشیمانی، ندامت","He showed no remorse for his actions.")
W("reprobate","n.","بدکار، فاسد","The old reprobate had a reputation for womanizing.")
W("righteous","adj.","عادل، دادگر","She was filled with righteous indignation.")
W("sanctimony","n.","قدیس‌مآبی، ریا","I'm tired of his sanctimony and self-righteousness.")
W("scrupulous","adj.","بسیار دقیق، باوجدان","She is scrupulous about maintaining ethical standards.")
W("unscrupulous","adj.","بی‌وجدان، بی‌پروا","The unscrupulous salesman lied to make a sale.")
W("venerate","v.","بزرگ داشتن، احترام گذاشتن","The ancient Egyptians venerated the cat.")
W("virtuous","adj.","پرهیزگار، درستکار","She strives to live a virtuous life.")
W("volition","n.","اراده، اختیار","She left of her own volition.")

# Advanced social and political
W("abdicate","v.","کناره‌گیری کردن، استعفا دادن","The king was forced to abdicate the throne.")
W("abolition","n.","لغو، الغا","The abolition of slavery was a landmark event.")
W("absolutism","n.","استبداد، حکومت مطلقه","The country was ruled by absolutism for centuries.")
W("anachronism","n.","نابه‌نگام، چیزی از گذشته","The monarchy is considered an anachronism by some.")
W("anarchy","n.","هرج و مرج، آشوب","The country descended into anarchy after the coup.")
W("annex","v.","ضمیمه کردن، الحاق کردن","The territory was annexed by the neighboring country.")
W("autocracy","n.","حکومت خودکامه","The autocracy suppressed all forms of dissent.")
W("bureaucrat","n.","دیوان‌سالار، کارمند دولت","The bureaucrat insisted on following every rule.")
W("cacophony","n.","ناهنجاری صوتی، سروصدا","There was a cacophony of car horns in the street.")
W("cartel","n.","کارتل، اتحادیه","The drug cartel controlled the illegal trade.")
W("coerce","v.","اجبار کردن، مجبور ساختن","They were coerced into signing the agreement.")
W("oligarchy","n.","الیگارشی، حکومت عدّه‌ای","The country was ruled by a wealthy oligarchy.")
W("plutocracy","n.","حکومت ثروتمندان","The critics accused the government of being a plutocracy.")
W("propaganda","n.","تبلیغات سیاسی","The regime used propaganda to control the population.")
W("suffrage","n.","حق رأی","The fight for women's suffrage was a long struggle.")
W("theocracy","n.","حکومت دینی","The country functioned as a theocracy.")
W("totalitarian","adj.","تمامیت‌خواه","The totalitarian regime suppressed all opposition.")
W("demagogue","n.","عوام‌فریب","The demagogue used fear and hatred to gain power.")

# Advanced science and nature
W("accrue","v.","انباشته شدن، افزایش یافتن","Interest will accrue on the account.")
W("amalgamate","v.","ادغام شدن، ترکیب شدن","The two companies amalgamated to form a new corporation.")
W("configration","n.","آتش‌سوزی بزرگ، شعله‌ور","The configration destroyed several city blocks.")
W("congenial","adj.","خوشایند، سازگار","We found the atmosphere very congenial.")
W("detriment","n.","آسیب، زیان","He worked long hours to the detriment of his health.")
W("dormant","adj.","خفته، نهفته","The volcano has been dormant for centuries.")
W("effervescent","adj.","جوشان، پرخروش","Her effervescent personality lit up the room.")
W("effluent","n.","فاضلاب، پساب","Industrial effluent polluted the river.")
W("embryonic","adj.","جنینی، ابتدایی","The plan is still in its embryonic stage.")
W("equilibrium","n.","تعادل","The body strives to maintain a state of equilibrium.")
W("erosion","n.","فرسایش","Coastal erosion is a serious problem.")
W("ethereal","adj.","روحانی، لطیف","The music had an ethereal quality.")
W("fauna","n.","جانوران","The island is known for its unique fauna.")
W("flora","n.","گیاهان","The region's rich flora includes many rare species.")
W("germinate","v.","جوانه زدن، سبز شدن","The seeds will germinate in the spring.")
W("habitat","n.","زیستگاه","The rainforest is the natural habitat of many species.")
W("incandescent","adj.","سفیدگوی","The incandescent light bulb was invented by Edison.")
W("indigenous","adj.","بومی","The indigenous people have lived here for thousands of years.")
W("inert","adj.","بی‌حرکت، خنثی","The gas is chemically inert.")
W("luminous","adj.","درخشان، نورانی","The luminous stars filled the night sky.")
W("metamorphosis","n.","دگردیسی، تغییر شکل","The caterpillar undergoes a metamorphosis into a butterfly.")
W("opaque","adj.","تیره، ناشفاف","The reasons for the decision remain opaque.")
W("osmosis","n.","اسمز، جذب تدریجی","She learned by osmosis, just by being in that environment.")
W("photosynthesis","n.","فتوسنتز","Plants use photosynthesis to convert sunlight into energy.")
W("precipitate","v.","شتاب بخشیدن، ایجاد کردن","The announcement precipitated a crisis.")
W("proliferate","v.","تکثیر شدن، رشد سریع","Social media platforms have proliferated in recent years.")
W("sedentary","adj.","نشسته، کم‌تحرک","A sedentary lifestyle can lead to health problems.")
W("synthesis","n.","ترکیب، تلفیق","The work is a synthesis of various artistic traditions.")
W("toxic","adj.","سمی","The waste is highly toxic and must be disposed of carefully.")
W("volatile","adj.","فرار، ناپایدار","The political situation is highly volatile.")

# More C2 verbs
W("abscond","v.","گریختن، فرار کردن","The treasurer absconded with the company's funds.")
W("adjudicate","v.","داوری کردن، حکم کردن","The case will be adjudicated in court.")
W("admonish","v.","تذکر دادن، نصیحت کردن","The teacher admonished the student for being late.")
W("amass","v.","انباشتن، جمع کردن","Over the years, he amassed a great fortune.")
W("appall","v.","وحشت زده کردن، شوکه کردن","The violence in the film appalled the audience.")
W("atone","v.","جبران کردن، کفاره دادن","He tried to atone for his past mistakes.")
W("beguile","v.","فریب دادن، مجذوب کردن","The beauty of the landscape beguiled the travelers.")
W("berate","v.","سرزنش کردن، توبیخ کردن","The manager berated his team for the failure.")
W("beseech","v.","التماس کردن، خواهش کردن","She beseeched him to stay.")
W("capitulate","v.","تسلیم شدن","The army finally capitulated after a long siege.")
W("castigate","v.","تنبیه کردن، نکوهش کردن","The article castigated the government's inaction.")
W("circumvent","v.","دور زدن، فریب دادن","They managed to circumvent the regulations.")
W("commiserate","v.","همدردی کردن","I commiserated with my friend over his loss.")
W("complacent","adj.","خودراضی، غافل","We must not become complacent about our success.")
W("concur","v.","موافق بودن","The judges concurred with the verdict.")
W("condescend","v.","تفضل فرمودن، خود را پایین آوردن","The celebrity condescended to sign a few autographs.")
W("connive","v.","تبانی کردن، چشم‌پوشی کردن","The official connived with the criminals.")
W("consort","v.","معاشرت کردن، همنشینی کردن","He was known to consort with unsavory characters.")
W("contravene","v.","نقض کردن، تخلف کردن","The new law contravenes international agreements.")
W("convoke","v.","جمع کردن، دعوت به جلسه","The president convoked an emergency meeting.")
W("debase","v.","تنزل دادن، بی‌ارزش کردن","Inflation debased the currency.")
W("debilitate","v.","ضعیف کردن، ناتوان ساختن","The disease debilitated him for months.")
W("defame","v.","تهمت زدن، بدنام کردن","The article defamed the celebrity.")
W("defraud","v.","کلاهبرداری کردن","She was convicted of trying to defraud the bank.")
W("delude","v.","فریب دادن","Delude yourself into thinking everything is fine.")
W("denigrate","v.","بدگویی کردن، تحقیر کردن","He constantly denigrates his colleagues' work.")
W("depose","v.","خلع کردن، برکنار کردن","The king was deposed by a military coup.")
W("disenfranchise","v.","محروم کردن از حقوق","The law disenfranchised certain groups.")
W("disparage","v.","تحقیر کردن، کم‌اهمیت جلوه دادن","She disparaged his efforts in front of everyone.")
W("dissemble","v.","تظاهر کردن، پنهان کاری","He dissembled his true intentions.")
W("dissent","v.","مخالفت کردن، اختلاف نظر","Several members dissented from the majority opinion.")
W("dissipate","v.","پراکنده شدن، هدر دادن","The energy was dissipated as heat.")
W("domineer","v.","تحکم کردن، زورگویی","The boss had a domineering personality.")
W("embellish","v.","آراستن، زینت دادن","She embellished the dress with beads.")
W("embezzle","v.","اختلاس کردن","The accountant embezzled company funds.")
W("enamor","v.","عاشق شدن، شیفته شدن","He was completely enamored with her.")
W("encroach","v.","تجاوز کردن، دست‌اندازی","Development is encroaching on the wilderness.")
W("engross","v.","جذب کردن، مجذوب ساختن","The novel engrossed her completely.")
W("entice","v.","فریب دادن، وسوسه کردن","The store tried to entice customers with discounts.")
W("entreat","v.","التماس کردن، تضرع کردن","She entreated him to change his mind.")
W("exhort","v.","ترغیب کردن، تشویق کردن","The general exhorted his troops to fight bravely.")
W("fabricate","v.","ساختن، جعل کردن","The evidence was fabricated to frame the defendant.")
W("fester","v.","چرک کردن، عفونی شدن","The wound began to fester.")
W("flagellate","v.","شلاق زدن، تازیانه زدن","The monk flagellated himself as a form of penance.")
W("flaunt","v.","خودنمایی کردن، به رخ کشیدن","He flaunted his wealth ostentatiously.")
W("forsake","v.","رها کردن، ترک کردن","She forsook her family for the sake of her career.")
W("fulminate","v.","اعتراض شدید کردن، غرش کردن","The editorial fulminated against the government.")
W("gainsay","v.","انکار کردن، مخالفت کردن","No one could gainsay the truth of the statement.")
W("garner","v.","جمع کردن، انباشتن","The film garnered critical acclaim.")
W("goad","v.","تحریک کردن، واداشتن","They goaded him into a fight.")
W("gratify","v.","راضی کردن، لذت بخشیدن","It gratified him to see his students succeed.")
W("guile","n.","فریب، نیرنگ","He used guile to achieve his objectives.")
W("gullible","adj.","ساده‌لوح، زودباور","The gullible tourist was cheated out of his money.")
W("haggle","v.","چانه زدن","They haggled over the price of the rug.")
W("hamper","v.","ممانعت کرد، مختل کردن","The search was hampered by bad weather.")
W("harangue","v.","سخنرانی خسته‌کننده، موعظه","The politician harangued the crowd for an hour.")
W("imperil","v.","به خطر انداختن","His reckless behavior imperiled the entire expedition.")
W("implore","v.","التماس کردن، خواهش کردن","She implored the king to show mercy.")
W("impugn","v.","زیر سؤال بردن، خدشه وارد کردن","The lawyer impugned the witness's credibility.")
W("incite","v.","برانگیختن، تحریک کردن","His speech incited the crowd to violence.")
W("ingratiate","v.","خود را چاپلوسانه جا زدن","He tried to ingratiate himself with the boss.")
W("insinuate","v.","کنایه زدن، تلویحاً گفتن","Are you insinuating that I'm dishonest?")
W("intercede","v.","میانجیگری کردن، شفاعت کردن","She interceded on behalf of the prisoner.")
W("inundate","v.","غرق کردن، سرازیر شدن","The office was inundated with phone calls.")
W("jeopardize","v.","به خطر انداختن","The scandal jeopardized her political career.")
W("lambaste","v.","سرزنش کردن، انتقاد تند کردن","The critics lambasted the film.")
W("languish","v.","پژمرده شدن، بیحال شدن","He languished in prison for years.")
W("lavish","adj.","مبذول داشتن، فراوان","They live in a lavish mansion.")
W("litigate","v.","دعوی قضایی کردن","The two parties agreed to settle rather than litigate.")
W("malign","v.","بدگویی کردن، تهمت زدن","She was maligned by the press.")
W("malinger","v.","تنبلی کردن، خود را به مریضی زدن","He was accused of malingering to avoid work.")
W("meditate","v.","مراقبه کردن، تفکر کردن","She meditates for twenty minutes every day.")
W("menace","n.","تهدید، خطر","The escaped prisoner was considered a menace to society.")
W("obfuscate","v.","مبهم کردن، گمراه کردن","The politician deliberately obfuscated the issue.")
W("obliterate","v.","محو کردن، نابود کردن","The bomb obliterated the entire village.")
W("obtrude","v.","تحمیل کردن، مزاحمت ایجاد کردن","I don't wish to obtrude upon your privacy.")
W("opportune","adj.","به‌موقع، مناسب","We waited for an opportune moment to act.")
W("ostracize","v.","طرد کردن، منزوی ساختن","She was ostracized by the community.")
W("perpetrate","v.","مرتکب شدن","The crime was perpetrated by a group of teenagers.")
W("perpetuate","v.","تداوم بخشیدن، جاودانه کردن","The myth was perpetuated by the media.")
W("perplex","v.","متحیر کردن، گیج کردن","The question perplexed the students.")
W("persevere","v.","استقامت کردن، پایداری کردن","Despite the setbacks, she persevered.")
W("pertain","v.","مربوط بودن، متعلق بودن","The documents pertaining to the case were missing.")
W("petrify","v.","سنگ شدن، ترسانده شدن","She was petrified with fear.")
W("pillage","v.","غارت کردن، تاراج کردن","The Vikings pillaged the coastal villages.")
W("placate","v.","آرام کردن، تسکین دادن","The manager tried to placate the angry customer.")
W("plagiarize","v.","سرقت ادبی کردن","He was accused of plagiarizing the article.")
W("ponder","v.","تعمق کردن، سنجیدن","She pondered the meaning of the poem.")
W("prevaricate","v.","دور زدن، طفره رفتن","Stop prevaricating and give me a straight answer!")
W("pry","v.","فضولی کردن، کنجکاوی کردن","I don't mean to pry, but where are you going?")
W("quandary","n.","دو راهی، سرگشتگی","I am in a quandary about which job to take.")
W("querulous","adj.","نالان، نق‌نقو","The querulous old man complained about everything.")
W("quibble","v.","ایرادگیری کردن، سخت‌گیری","Let's not quibble over minor details.")
W("quiescent","adj.","ساکت، بیحرکت","The volcano is currently quiescent.")
W("rally","v.","تجمع کردن، متحد شدن","The community rallied to support the family.")
W("rancid","adj.","گندیده، بدبو","The butter had gone rancid.")
W("raucous","adj.","پر سر و صدا، گوشخراش","The raucous laughter could be heard from outside.")
W("rebuke","v.","توبیخ کردن، ملامت کردن","The manager rebuked him for his carelessness.")
W("recalcitrant","adj.","نافرمان، سرکش","The recalcitrant student refused to obey the rules.")
W("reciprocate","v.","متقابل کردن، جبران کردن","She did not reciprocate his feelings.")
W("recluse","n.","گوشه‌گیر، عزلت‌نشین","The reclusive author rarely gave interviews.")
W("redress","v.","جبران کردن، اصلاح کردن","The company sought to redress the grievance.")
W("refrain","v.","خودداری کردن، پرهیز کردن","Please refrain from smoking in the building.")
W("relent","v.","نرم شدن، دست کشیدن","The storm finally relented.")
W("relinquish","v.","واگذار کردن، رها کردن","She relinquished her claim to the throne.")
W("remiss","adj.","سهل‌انگار، غافل","He was remiss in his duties.")
W("remonstrate","v.","اعتراض کردن، انتقاد کردن","The students remonstrated against the new rules.")
W("replenish","v.","پر کردن، تجدید کردن","We need to replenish our food supplies.")
W("reprehensible","adj.","سرزنش‌آمیز، نکوهیده","His behavior was absolutely reprehensible.")
W("reprimand","v.","توبیخ کردن، سرزنش کردن","The officer was reprimanded for his conduct.")
W("reproach","v.","سرزنش کردن، ملامت کردن","She reproached him for forgetting their anniversary.")
W("repudiate","v.","رد کردن، انکار کردن","He repudiated the allegations against him.")
W("rescind","v.","لغو کردن، فسخ کردن","The contract was rescinded by mutual agreement.")
W("respite","n.","مهلت، فرصت استراحت","The cold weather provided a brief respite from the heat.")
W("resplendent","adj.","درخشان، مجلل","The queen appeared resplendent in her coronation robes.")
W("retaliate","v.","تلافی کردن","If we attack them, they will retaliate.")
W("retort","v.","پاسخ تند دادن، جواب دادن","She retorted sharply to the insult.")
W("retract","v.","پس گرفتن، عقب کشیدن","The newspaper retracted the false story.")
W("revamp","v.","نوسازی کردن، دگرگون ساختن","The company revamped its corporate image.")
W("revere","v.","بزرگ داشتن، احترام عمیق","The ancient philosopher was revered for his wisdom.")
W("revoke","v.","لغو کردن، باطل کردن","His driver's license was revoked.")
W("ruminate","v.","تعمق کردن، نشخوار فکری","She lay awake ruminating on the problem.")
W("sabotage","v.","خرابکاری کردن، تخریب","They sabotaged the enemy's supply lines.")
W("sanction","v.","مجاز دانستن، تحریم کردن","The government sanctioned the use of force.")
W("saturate","v.","اشباع کردن، خیس کردن","The market is saturated with similar products.")
W("scintillating","adj.","درخشان، جذاب","The conversation was scintillating and witty.")
W("secrete","v.","ترشح کردن، پنهان کردن","The gland secretes hormones into the bloodstream.")
W("secular","adj.","سکولار، غیردینی","India is a secular state.")
W("sedentary","adj.","نشسته، بی‌تحرک","She has a sedentary office job.")
W("servile","adj.","چاپلوس، برده‌صفت","His servile attitude disgusted his colleagues.")
W("sever","v.","قطع کردن، بریدن","The storm severed the power lines.")
W("subjugate","v.","تحت سلطه درآوردن، مغلوب کردن","The invaders subjugated the native population.")
W("subordinate","adj.","فرعی، تابع","He was in a subordinate role in the company.")
W("subpoena","n.","احضاریه دادگاه","The witness was issued a subpoena.")
W("substantive","adj.","اساسی، ماهوی","There are substantive differences between the two proposals.")
W("subterfuge","n.","حیله، فریب","He obtained the information by subterfuge.")
W("succumb","v.","تسلیم شدن، درگذشتن","He succumbed to his injuries.")
W("sullen","adj.","غمگین، ترشرو","The sullen teenager refused to speak.")
W("superfluous","adj.","اضافی، زائد","The extra details were superfluous.")
W("supersede","v.","جایگزین شدن، برتری یافتن","The old system was superseded by newer technology.")
W("surreptitious","adj.","مخفیانه، پنهانی","He cast a surreptitious glance at his watch.")
W("susceptible","adj.","مستعد، حساس","Older people are more susceptible to the disease.")
W("tacit","adj.","ضمنی، ناگفته","There was a tacit understanding between them.")
W("tangential","adj.","حاشیه‌ای، انحرافی","The issue is tangential to our main discussion.")
W("tedious","adj.","خسته‌کننده، ملال‌آور","The work was repetitive and tedious.")
W("temerity","n.","گستاخی، بی‌پروایی","He had the temerity to question my authority.")
W("temperate","adj.","مختصر، ملایم","The region has a temperate climate.")
W("temporal","adj.","دنیوی، فانی","The painting deals with both temporal and spiritual matters.")
W("tenacious","adj.","سرسخت، محکم","The dog had a tenacious grip on its bone.")
W("tender","v.","ارائه کردن، تقدیم کردن","The contractor tendered his resignation.")
W("tepid","adj.","ولرم، بی‌حرارت","The response to the proposal was tepid at best.")
W("terse","adj.","موجز، کوتاه","His terse reply suggested he was annoyed.")
W("transgress","v.","تجاوز کردن، گناه کردن","He transgressed the boundaries of acceptable behavior.")
W("transient","adj.","گذرا، موقت","The beauty of cherry blossoms is transient.")
W("travesty","n.","مسخره، کاریکاتور بد","The trial was a travesty of justice.")
W("tumult","n.","غوغا، هیاهو","The country was in a state of tumult.")
W("turpitude","n.","بدذاتی، فساد","Moral turpitude is grounds for disbarment.")
W("umbrage","n.","رنجش، دلخوری","He took umbrage at her comments.")
W("unassuming","adj.","متواضع، بی‌آلایش","The millionaire was surprisingly unassuming.")
W("unequivocal","adj.","بدون ابهام، صریح","The evidence is unequivocal.")
W("unilateral","adj.","یک‌جانبه","The decision was taken unilaterally.")
W("unprecedented","adj.","بی‌سابقه","The pandemic was an unprecedented event.")
W("unscrupulous","adj.","بی‌وجدان","The unscrupulous company exploited its workers.")
W("upbraid","v.","سرزنش کردن، توبیخ کردن","She upbraided him for his carelessness.")
W("usurp","v.","غصب کردن، تصاحب کردن","He attempted to usurp the throne.")
W("utmost","adj.","بسیار زیاد، نهایت","It is of the utmost importance.")
W("vacillate","v.","مردد بودن، دودل بودن","She vacillated between accepting and refusing.")
W("vapid","adj.","بی‌مزه، بی‌روح","The conversation was vapid and boring.")
W("vehement","adj.","پر شور، شدید","He delivered a vehement defense of his actions.")
W("verbose","adj.","پرحرف، پرگویی","The verbose report could have been much shorter.")
W("vicarious","adj.","غیرمستقیم، به نیابت از","He got vicarious pleasure from watching his son play.")
W("vigilant","adj.","هوشیار، مراقب","We must remain vigilant against cyber attacks.")
W("virile","adj.","مردانه، قوی","He was a virile and energetic young man.")
W("virtuoso","n.","نوازنده ماهر، استاد","The violinist was a true virtuoso.")
W("vitriolic","adj.","زهرآگین، سوزان","The article was full of vitriolic attacks on the government.")
W("vituperate","v.","دشنام دادن، فحش دادن","The angry customer vituperated the staff.")
W("vivacious","adj.","پر جنب و جوش، سرزنده","She was a vivacious and charming young woman.")
W("vociferous","adj.","پر سر و صدا، بلند","There were vociferous protests outside the embassy.")
W("volatile","adj.","فرار, ناپایدار","The situation remains highly volatile.")
W("voluble","adj.","روان‌گو، خوش‌صحبت","He was a voluble and engaging speaker.")
W("voracious","adj.","حریص، سیریناپذیر","She was a voracious reader of detective novels.")
W("warrant","n.","دلیل، مجوز","There is no warrant for such behavior.")
W("wary","adj.","احتیاط، محتاط","Investors remain wary of the stock market.")
W("whimsical","adj.","دمدمی، غیرمنتظره","The artist had a whimsical sense of humor.")
W("wistful","adj.","غمگین، حسرت‌بار","She gave a wistful sigh as she looked at old photos.")
W("zealot","n.","متعصب، غیور","The religious zealot was unwilling to compromise.")
W("zenith","n.","اوج، نقطه اوج","The empire was at its zenith in the 16th century.")
W("zephyr","n.","باد ملایم","A gentle zephyr blew through the valley.")


# Read current file
with open(FILE, 'r', encoding='utf-8') as f:
    content = f.read()

# Find the position to insert new words
# The word array ends with "];" then the rest of the code
# We need to find the last entry and add our words before "];"

target = "];\n\nconst WORDS_PER_DAY"
if target in content:
    idx = content.rfind(target)
    before = content[:idx]
    after = content[idx:]
    
    # Add a comma before the closing bracket if needed
    # The last entry already ends with "]," so we need to make sure there are no issues
    # Actually, the array ends with "];" so we just insert our words + commas before "];"
    
    new_words = ",\n".join(words)
    new_content = before + new_words + "\n" + after
    
    with open(FILE, 'w', encoding='utf-8') as f:
        f.write(new_content)
    
    # Count total words in the file
    total = content.count("['") + new_words.count("['")
    print(f"Added {len(words)} new words")
    print(f"Total words in database: ~{total}")
else:
    print(f"Could not find target marker '{target}'")
    print("Checking file...")
    print(f"File length: {len(content)}")
    # Find what's near the end
    n = content.rfind("];")
    if n > 0:
        print(f"Found ';' at position {n}")
        print(f"Context: ...{content[n-50:n+50]}...")
