#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Add ~1900+ more C2 words to reach ~4000 total."""

FILE = r"D:\dev\DLZLAB\wordApp\app.html"
words = []
esc = lambda s: s.replace("'", "\\'")
W = lambda e,p,f,x: words.append(f"['{esc(e)}','{esc(p)}','{esc(f)}','{esc(x)}']")

# ~127 groups of 15 = 1905 words, compact format
BULK = [
# Group 1-15: Science & Research
("abiotic","adj.","غیرزیستی","abiotic factors"),("abrasion","n.","ساییدگی","skin abrasion"),("absorption","n.","جذب","nutrient absorption"),("abstraction","n.","انتزاع","theoretical abstraction"),("acceleration","n.","شتاب","economic acceleration"),("accretion","n.","افزایش","ice accretion"),("accuracy","n.","دقت","measurement accuracy"),("acidification","n.","اسیدی شدن","ocean acidification"),("activation","n.","فعالسازی","neural activation"),("adaptation","n.","سازگاری","evolutionary adaptation"),("adhesion","n.","چسبندگی","cellular adhesion"),("adjacency","n.","مجاورت","matrix adjacency"),("administration","n.","مدیریت","public administration"),("advancement","n.","پیشرفت","technological advancement"),("advection","n.","همرفت","heat advection"),
# Group 2
("aeration","n.","هوادهی","soil aeration"),("aerosol","n.","هواگن","aerosol particles"),("afforestation","n.","جنگل‌کاری","large-scale afforestation"),("aggregation","n.","تجمع","platelet aggregation"),("agitation","n.","تهییج","thermal agitation"),("algorithm","n.","الگوریتم","sorting algorithm"),("alignment","n.","هم‌راستایی","strategic alignment"),("allocation","n.","تخصیص","resource allocation"),("alteration","n.","تغییر","genetic alteration"),("altitude","n.","ارتفاع","high altitude"),("amplitude","n.","دامنه","wave amplitude"),("anaerobic","adj.","بی‌هوازی","anaerobic bacteria"),("analgesic","n.","مسکن","powerful analgesic"),("analogous","adj.","مشابه","structurally analogous"),("annealing","n.","بازپخت","thermal annealing"),
# Group 3: Business & Economics
("amortization","n.","استهلاک","loan amortization"),("appraisal","n.","ارزیابی","property appraisal"),("appreciation","n.","افزایش ارزش","currency appreciation"),("appropriation","n.","تخصیص بودجه","budget appropriation"),("arbitrage","n.","آربیتراژ","financial arbitrage"),("assessment","n.","ارزیابی","risk assessment"),("asset","n.","دارایی","fixed assets"),("audit","n.","حسابرسی","external audit"),("austerity","n.","ریاضت اقتصادی","fiscal austerity"),("backlog","n.","انباشت کار","order backlog"),("bankruptcy","n.","ورشکستگی","file for bankruptcy"),("bargaining","n.","چانه‌زنی","collective bargaining"),("benchmark","n.","شاخص","industry benchmark"),("bidding","n.","مناقصه","competitive bidding"),("bond","n.","اوراق قرضه","government bond"),
# Group 4
("bookkeeping","n.","حسابداری","double-entry bookkeeping"),("boycott","n.","تحریم","trade boycott"),("branding","n.","برندسازی","corporate branding"),("brokerage","n.","کارگزاری","stock brokerage"),("budgeting","n.","بودجه‌بندی","capital budgeting"),("bureaucracy","n.","دیوان‌سالاری","government bureaucracy"),("calibration","n.","کالیبراسیون","instrument calibration"),("capitalization","n.","سرمایه‌گذاری","market capitalization"),("cartel","n.","کارتل","drug cartel"),("cashflow","n.","جریان نقدی","positive cashflow"),("commodity","n.","کالا","commodity prices"),("compensation","n.","غرامت","executive compensation"),("competition","n.","رقابت","market competition"),("conglomerate","n.","شرکت بزرگ","media conglomerate"),("consolidation","n.","ادغام","debt consolidation"),
# Group 5: Law & Justice
("acquittal","n.","تبرئه","complete acquittal"),("adjudication","n.","داوری","administrative adjudication"),("affidavit","n.","اظهارنامه","swear an affidavit"),("allegation","n.","ادعا","unsubstantiated allegation"),("appellate","adj.","استینافی","appellate court"),("arbitration","n.","داوری","binding arbitration"),("arraignment","n.","احضار","arraignment hearing"),("bailiff","n.","مأمور دادگاه","bailiff escorted"),("bankruptcy","n.","ورشکستگی","bankruptcy protection"),("breach","n.","نقض","material breach"),("brief","n.","لایحه","legal brief"),("certiorari","n.","فرجام‌خواهی","writ of certiorari"),("claimant","n.","مدعی","the claimant argued"),("codicil","n.","الحاقیه","add a codicil"),("commutation","n.","تخفیف","sentence commutation"),
# Group 6
("complaint","n.","شکایت","file a complaint"),("confiscation","n.","مصادره","asset confiscation"),("contempt","n.","اهانت","contempt of court"),("contractual","adj.","قراردادی","contractual obligation"),("conviction","n.","محکومیت","criminal conviction"),("custodial","adj.","نگهبانی","custodial sentence"),("damages","n.","خسارت","punitive damages"),("deceased","n.","متوفی","the deceased"),("decree","n.","حکم","court decree"),("defamation","n.","افترا","sue for defamation"),("defendant","n.","متهم","the defendant pleaded"),("deposition","n.","شهادت","videotaped deposition"),("disclaimer","n.","سلب مسئولیت","legal disclaimer"),("disclosure","n.","افشا","full disclosure"),("discretion","n.","اختیار","judicial discretion"),
# Group 7: Medicine & Health
("abstinence","n.","پرهیز","alcohol abstinence"),("acute","adj.","حاد","acute pain"),("adrenal","adj.","فوق کلیوی","adrenal glands"),("adverse","adj.","ناخواسته","adverse reaction"),("allergen","n.","آلرژن","common allergen"),("ambulatory","adj.","سرپایی","ambulatory care"),("analgesia","n.","بی‌دردی","epidural analgesia"),("anaphylaxis","n.","شوک آنافیلاکسی","severe anaphylaxis"),("anemia","n.","کم‌خونی","iron deficiency anemia"),("anesthetic","n.","بیهوشی","general anesthetic"),("aneurysm","n.","آنوریسم","brain aneurysm"),("angina","n.","آنژین","angina pectoris"),("antibiotic","n.","آنتی‌بیوتیک","broad-spectrum antibiotic"),("antibody","n.","آنتی‌بادی","monoclonal antibodies"),("anticoagulant","n.","ضد انعقاد","oral anticoagulant"),
# Group 8
("antidepressant","n.","ضد افسردگی","tricyclic antidepressant"),("antihistamine","n.","ضد حساسیت","antihistamine tablets"),("antiseptic","n.","ضد عفونی کننده","antiseptic solution"),("antitoxin","n.","پادزهر","botulinum antitoxin"),("aorta","n.","آئورت","aortic aneurysm"),("arrhythmia","n.","آریتمی","cardiac arrhythmia"),("arthroscopic","adj.","آرتروسکوپی","arthroscopic surgery"),("asthma","n.","آسم","bronchial asthma"),("asymptomatic","adj.","بدون علامت","asymptomatic carrier"),("atherosclerosis","n.","آترواسکلروز","coronary atherosclerosis"),("atrophy","n.","آتروفی","muscular atrophy"),("auscultation","n.","سمع","chest auscultation"),("autoimmune","adj.","خودایمن","autoimmune disorder"),("bacterial","adj.","باکتریایی","bacterial infection"),("benign","adj.","خوش‌خیم","benign tumor"),
# Group 9: Psychology & Mind
("abnormal","adj.","غیرعادی","abnormal behavior"),("ambivalence","n.","دوسوگرایی","emotional ambivalence"),("amnesia","n.","فراموشی","retrograde amnesia"),("amplification","n.","تشدید","sensory amplification"),("analytical","adj.","تحلیلی","analytical thinking"),("antisocial","adj.","ضداجتماعی","antisocial personality"),("anxiety","n.","اضطراب","generalized anxiety"),("apraxia","n.","آپراکسی","speech apraxia"),("arousal","n.","برانگیختگی","sexual arousal"),("attachment","n.","دلبستگی","attachment theory"),("attention","n.","توجه","selective attention"),("attitude","n.","نگرش","cognitive attitude"),("attribution","n.","اسناد","causal attribution"),("autism","n.","اوتیسم","autism spectrum"),("aversion","n.","بیزاری","risk aversion"),
# Group 10
("behavioral","adj.","رفتاری","behavioral therapy"),("bias","n.","سوگیری","cognitive bias"),("bipolar","adj.","دوقطبی","bipolar disorder"),("catharsis","n.","پالایش","emotional catharsis"),("cognition","n.","شناخت","social cognition"),("compulsion","n.","اجبار","obsessive compulsion"),("conditioning","n.","شرطی‌سازی","classical conditioning"),("conformity","n.","همنوایی","social conformity"),("consciousness","n.","هوشیاری","stream of consciousness"),("coping","n.","مقابله","coping mechanism"),("delusion","n.","هذیان","delusion of grandeur"),("dementia","n.","زوال عقل","vascular dementia"),("denial","n.","انکار","in denial"),("depression","n.","افسردگی","clinical depression"),("dissociation","n.","گسستگی","traumatic dissociation"),
# Group 11: Politics & Government
("absolute","adj.","مطلقه","absolute monarchy"),("abstention","n.","رأی ممتنع","abstention from voting"),("accountability","n.","پاسخگویی","democratic accountability"),("administration","n.","دولت","Obama administration"),("advocacy","n.","حمایت","policy advocacy"),("affirmative","adj.","ایجابی","affirmative action"),("alliance","n.","اتحاد","military alliance"),("amendment","n.","اصلاحیه","constitutional amendment"),("anarchism","n.","آنارشیسم","philosophical anarchism"),("annexation","n.","الحاق","territorial annexation"),("appropriation","n.","تصویب بودجه","appropriation bill"),("aristocracy","n.","اشراف","landed aristocracy"),("authoritarian","adj.","اقتدارگرا","authoritarian regime"),("autocracy","n.","خودکامگی","benevolent autocracy"),("bicaneral","adj.","دو مجلسی","bicameral legislature"),
# Group 12
("bipartisan","adj.","دو حزبی","bipartisan support"),("bureaucratic","adj.","دیوان‌سالار","bureaucratic red tape"),("cabinet","n.","کابینه","cabinet minister"),("campaign","n.","کمپین","presidential campaign"),("candidacy","n.","نامزدی","announce candidacy"),("caucus","n.","گردهمایی حزبی","Iowa caucus"),("censorship","n.","سانسور","government censorship"),("chancellor","n.","صدراعظم","German chancellor"),("citizenship","n.","شهروندی","dual citizenship"),("coalition","n.","ائتلاف","governing coalition"),("colony","n.","مستعمره","penal colony"),("committee","n.","کمیته","standing committee"),("commonwealth","n.","مشترک‌المنافع","British commonwealth"),("communism","n.","کمونیسم","collapse of communism"),("confederation","n.","کنفدراسیون","Swiss confederation"),
# Group 13: Environment & Ecology
("adaptation","n.","سازگاری","climate adaptation"),("afforestation","n.","جنگل‌کاری","mass afforestation"),("algae","n.","جلبک","toxic algae bloom"),("biodiversity","n.","تنوع زیستی","loss of biodiversity"),("biomass","n.","زیست‌توده","biomass energy"),("biosphere","n.","زیست‌کره","global biosphere"),("carbon","n.","کربن","carbon emissions"),("carnivore","n.","گوشت‌خوار","top carnivore"),("catchment","n.","آبگیر","catchment area"),("conservation","n.","حفاظت","wildlife conservation"),("contaminant","n.","آلاینده","chemical contaminant"),("deforestation","n.","جنگل‌زدایی","Amazon deforestation"),("desertification","n.","بیابان‌زایی","combat desertification"),("detritus","n.","آوار","organic detritus"),("dioxide","n.","دی‌اکسید","carbon dioxide"),
# Group 14
("ecosystem","n.","اکوسیستم","fragile ecosystem"),("effluent","n.","پساب","industrial effluent"),("emission","n.","انتشار","greenhouse emissions"),("endangered","adj.","در خطر انقراض","endangered species"),("erosion","n.","فرسایش","coastal erosion"),("eutrophication","n.","یوتریفیکاسیون","lake eutrophication"),("evaporation","n.","تبخیر","water evaporation"),("extinction","n.","انقراض","mass extinction"),("fossil","n.","سوخت فسیلی","fossil fuels"),("glacier","n.","یخچال طبیعی","glacial retreat"),("greenhouse","n.","گلخانه‌ای","greenhouse gas"),("groundwater","n.","آب زیرزمینی","groundwater depletion"),("habitat","n.","زیستگاه","habitat destruction"),("herbicide","n.","علف‌کش","toxic herbicide"),("incineration","n.","سوزاندن","waste incineration"),
# Group 15: Technology
("acceleration","n.","شتاب","hardware acceleration"),("algorithm","n.","الگوریتم","search algorithm"),("allocation","n.","تخصیص","memory allocation"),("annotation","n.","حاشیه‌نویسی","data annotation"),("asynchronous","adj.","ناهمزمان","asynchronous communication"),("authentication","n.","احراز هویت","two-factor authentication"),("automation","n.","خودکارسازی","industrial automation"),("bandwidth","n.","پهنای باند","high bandwidth"),("binary","adj.","دودویی","binary code"),("bitmap","n.","نقشه بیتی","bitmap image"),("bootstrap","v.","راه‌اندازی","bootstrap the system"),("broadband","n.","پهن‌باند","broadband connection"),("buffer","n.","بافر","buffer overflow"),("cache","n.","نهان","cache memory"),("calibration","n.","کالیبراسیون","sensor calibration"),
# Group 16
("encryption","n.","رمزنگاری","end-to-end encryption"),("iteration","n.","تکرار","software iteration"),("latency","n.","تأخیر","network latency"),("malware","n.","بدافزار","malware detection"),("modular","adj.","ماژوالر","modular design"),("optimization","n.","بهینه‌سازی","performance optimization"),("protocol","n.","پروتکل","communication protocol"),("redundancy","n.","افزونگی","system redundancy"),("scalability","n.","مقیاس‌پذیری","horizontal scalability"),("synchronization","n.","همگام‌سازی","data synchronization"),("throughput","n.","توان عملیاتی","network throughput"),("virtualization","n.","مجازی‌سازی","server virtualization"),("vulnerability","n.","آسیب‌پذیری","security vulnerability"),("debugging","n.","اشکال‌زدایی","kernel debugging"),("deployment","n.","استقرار","continuous deployment"),
# Group 17: Philosophy & Thought
("aesthetics","n.","زیبایی‌شناسی","modern aesthetics"),("altruism","n.","نوع‌دوستی","ethical altruism"),("autonomy","n.","خودمختاری","moral autonomy"),("causality","n.","علیت","principle of causality"),("conceptual","adj.","مفهومی","conceptual framework"),("consciousness","n.","آگاهی","phenomenal consciousness"),("deontology","n.","وظیفه‌گرایی","kantian deontology"),("dialectic","n.","دیالکتیک","hegelian dialectic"),("dualism","n.","دوگانه‌انگاری","mind-body dualism"),("empiricism","n.","تجربه‌گرایی","logical empiricism"),("epistemology","n.","شناخت‌شناسی","social epistemology"),("essentialism","n.","ذات‌گرایی","gender essentialism"),("existentialism","n.","اگزیستانسیالیسم","french existentialism"),("fallibilism","n.","خطاپذیری","scientific fallibilism"),("fatalism","n.","تقدیرگرایی","oriental fatalism"),
# Group 18
("hermeneutics","n.","هرمنوتیک","textual hermeneutics"),("idealism","n.","آرمان‌گرایی","transcendental idealism"),("materialism","n.","ماده‌گرایی","dialectical materialism"),("metaphysics","n.","متافیزیک","analytic metaphysics"),("nihilism","n.","پوچ‌گرایی","existential nihilism"),("nominalism","n.","نام‌گرایی","medieval nominalism"),("ontology","n.","هستی‌شناسی","social ontology"),("phenomenology","n.","پدیدارشناسی","existential phenomenology"),("pragmatism","n.","عمل‌گرایی","american pragmatism"),("rationalism","n.","عقل‌گرایی","continental rationalism"),("relativism","n.","نسبی‌گرایی","moral relativism"),("scholasticism","n.","مدرسی","medieval scholasticism"),("solipsism","n.","خودتنهاانگاری","epistemological solipsism"),("stoicism","n.","رواقی‌گری","ancient stoicism"),("teleology","n.","غایت‌شناسی","aristotelian teleology"),
# Group 19: Military & Strategy
("advance","n.","پیشروی","military advance"),("airpower","n.","قدرت هوایی","strategic airpower"),("alliance","n.","اتحاد","defensive alliance"),("ammunition","n.","تسلیحات","live ammunition"),("armistice","n.","آتش‌بس","armistice agreement"),("arsenal","n.","زرادخانه","nuclear arsenal"),("artillery","n.","توپخانه","heavy artillery"),("assault","n.","حمله","frontal assault"),("asymmetric","adj.","نامتقارن","asymmetric warfare"),("battalion","n.","گردان","infantry battalion"),("blockade","n.","محاصره","naval blockade"),("brigade","n.","تیپ","armored brigade"),("camouflage","n.","استتار","military camouflage"),("casualty","n.","تلفات","civilian casualties"),("cavalry","n.","سواره‌ظامی","light cavalry"),
# Group 20
("ceasefire","n.","آتش‌بس","humanitarian ceasefire"),("coalition","n.","ائتلاف","coalition forces"),("combatant","n.","جنگنده","enemy combatant"),("command","n.","فرماندهی","chain of command"),("conscription","n.","سربازی اجباری","military conscription"),("counterattack","n.","ضد حمله","launch counterattack"),("deployment","n.","استقرار","troop deployment"),("detonation","n.","انفجار","nuclear detonation"),("disarmament","n.","خلع سلاح","nuclear disarmament"),("embargo","n.","تحریم","arms embargo"),("fortification","n.","استحکامات","defensive fortifications"),("guerrilla","n.","چریک","guerrilla warfare"),("insurgency","n.","شورش","counter insurgency"),("intervention","n.","مداخله","military intervention"),("logistics","n.","تدارکات","military logistics"),
# Group 21: Sociology & Culture
("acculturation","n.","فرهنگ‌پذیری","forced acculturation"),("assimilation","n.","همسان‌سازی","cultural assimilation"),("bureaucratization","n.","دیوان‌سالارشدن","organizational bureaucratization"),("categorization","n.","طبقه‌بندی","social categorization"),("collectivism","n.","جمع‌گرایی","cultural collectivism"),("commodification","n.","کالایی‌سازی","commodification of art"),("cosmopolitanism","n.","جهان‌وطن‌ی","cultural cosmopolitanism"),("creolization","n.","آمیختگی","linguistic creolization"),("democratization","n.","دموکراتیزاسیون","political democratization"),("deviance","n.","انحراف","social deviance"),("differentiation","n.","تمایز","social differentiation"),("discourse","n.","گفتمان","political discourse"),("diversification","n.","تنوع‌بخشی","cultural diversification"),("egalitarianism","n.","برابری‌طلبی","radical egalitarianism"),("elitism","n.","نخبه‌گرایی","cultural elitism"),
# Group 22
("ethnocentrism","n.","قوم‌مداری","naive ethnocentrism"),("factionalism","n.","جناح‌بندی","internal factionalism"),("feudalism","n.","فئودالیسم","european feudalism"),("globalization","n.","جهانی‌شدن","economic globalization"),("hegemony","n.","هژمونی","cultural hegemony"),("hybridity","n.","دورگگی","cultural hybridity"),("imperialism","n.","امپریالیسم","western imperialism"),("industrialization","n.","صنعتی‌شدن","rapid industrialization"),("institutionalization","n.","نهادینه‌شدن","social institutionalization"),("marginalization","n.","حاشیه‌رانی","social marginalization"),("militarism","n.","نظامی‌گری","japanese militarism"),("modernization","n.","نوسازی","societal modernization"),("multiculturalism","n.","چندفرهنگی","canadian multiculturalism"),("nationalism","n.","ملی‌گرایی","extreme nationalism"),("patriarchy","n.","پدرسالاری","institutional patriarchy"),
# Group 23: Geography & Geology
("alluvial","adj.","آبرفتی","alluvial plain"),("altitude","n.","ارتفاع","altitude sickness"),("amphibious","adj.","دوزیست","amphibious vehicle"),("aquifer","n.","سفره آب زیرزمینی","underground aquifer"),("archipelago","n.","مجمع‌الجزایر","malay archipelago"),("atoll","n.","آب‌سنگ حلقوی","coral atoll"),("badland","n.","بدبوم","eroded badlands"),("basin","n.","حوضه","drainage basin"),("boulder","n.","تخته‌سنگ","granite boulder"),("butte","n.","تپه","desolate butte"),("caldera","n.","کالدرا","volcanic caldera"),("canyon","n.","دره","grand canyon"),("cataract","n.","آبشار بزرگ","nile cataracts"),("cavern","n.","غار","limestone cavern"),("climate","n.","اقلیم","arid climate"),
# Group 24
("continent","n.","قاره","african continent"),("cordillera","n.","رشته کوه","andean cordillera"),("crater","n.","دهانه","impact crater"),("crust","n.","پوسته","earth's crust"),("delta","n.","دلتا","river delta"),("deposit","n.","رسوب","mineral deposits"),("dormant","adj.","خاموش","dormant volcano"),("dune","n.","تپه شنی","sand dune"),("elevation","n.","ارتفاع","high elevation"),("equator","n.","استوا","equatorial region"),("erosion","n.","فرسایش","wind erosion"),("escarpment","n.","پرتگاه","rocky escarpment"),("estuary","n.","خور","tidal estuary"),("fault","n.","گسل","tectonic fault"),("fjord","n.","فیورد","norwegian fjord"),
# Group 25: Mathematics & Logic
("abscissa","n.","طول","x-axis abscissa"),("axiom","n.","اصل","mathematical axiom"),("binomial","n.","دو جمله‌ای","binomial expansion"),("calculus","n.","حساب دیفرانسیل","integral calculus"),("coefficient","n.","ضریب","correlation coefficient"),("commutative","adj.","جابجایی","commutative property"),("congruence","n.","هم‌نهشتی","modular congruence"),("conjecture","n.","حدس","goldbach conjecture"),("convergence","n.","همگرایی","series convergence"),("corollary","n.","نتیجه","obvious corollary"),("covariance","n.","کوواریانس","sample covariance"),("determinant","n.","دترمینان","matrix determinant"),("differentiation","n.","مشتق‌گیری","numerical differentiation"),("eigenvalue","n.","مقدار ویژه","complex eigenvalue"),("ellipse","n.","بیضی","focal ellipse"),
# Group 26
("extrapolation","n.","برون‌یابی","linear extrapolation"),("fraction","n.","کسر","proper fraction"),("gradient","n.","شیب","steep gradient"),("hypotenuse","n.","وتر","right triangle hypotenuse"),("induction","n.","استقرا","mathematical induction"),("integral","n.","انتگرال","definite integral"),("interpolation","n.","درون‌یابی","spline interpolation"),("isomorphism","n.","یک‌ریختی","graph isomorphism"),("logarithm","n.","لگاریتم","natural logarithm"),("orthogonal","adj.","متعامد","orthogonal vectors"),("permutation","n.","جایگشت","random permutation"),("polynomial","n.","چندجمله‌ای","quadratic polynomial"),("probability","n.","احتمال","conditional probability"),("recursion","n.","بازگشت","infinite recursion"),("stochastic","adj.","تصادفی","stochastic process"),
# Group 27: Linguistics & Language
("affix","n.","وند","derivational affix"),("alliteration","n.","واج‌آرایی","poetic alliteration"),("anaphora","n.","ارجاع","discourse anaphora"),("articulation","n.","تلفظ","manner of articulation"),("assonance","n.","تجنیس","vowel assonance"),("bilabial","adj.","دو لبی","bilabial consonant"),("cognate","n.","هم‌ریشه","french cognate"),("conjugation","n.","صرف","verb conjugation"),("consonant","n.","صامت","voiced consonant"),("deixis","n.","ارجاع بافتی","temporal deixis"),("diphthong","n.","دوواکه","falling diphthong"),("etymology","n.","ریشه‌شناسی","folk etymology"),("fricative","n.","سایشی","voiceless fricative"),("gerund","n.","مصدر","gerund phrase"),("glottal","adj.","چاکنایی","glottal stop"),
# Group 28
("grammar","n.","دستور زبان","generative grammar"),("hyperbole","n.","اغراق","rhetorical hyperbole"),("idiom","n.","اصطلاح","idiomatic expression"),("inflection","n.","تصریف","nominal inflection"),("intonation","n.","آهنگ","rising intonation"),("lexicon","n.","واژگان","mental lexicon"),("morpheme","n.","تکواژ","bound morpheme"),("morphology","n.","صرف و نحو","linguistic morphology"),("onomatopoeia","n.","نام‌آوا","onomatopoeic word"),("palatal","adj.","کامی","palatal sound"),("phoneme","n.","واج","distinctive phoneme"),("phonetics","n.","آواشناسی","acoustic phonetics"),("pragmatics","n.","کاربردشناسی","linguistic pragmatics"),("semantics","n.","معناشناسی","formal semantics"),("syntax","n.","نحو","generative syntax"),
# Group 29: Art & Literature
("abstract","adj.","انتزاعی","abstract painting"),("aesthetic","adj.","زیبایی‌شناختی","aesthetic value"),("allegory","n.","تمثیل","political allegory"),("arabesque","n.","اسلیمی","intricate arabesque"),("avant-garde","n.","پیشرو","russian avant-garde"),("baroque","adj.","باروک","baroque architecture"),("bildungsroman","n.","رمان تربیتی","german bildungsroman"),("calligraphy","n.","خوشنویسی","japanese calligraphy"),("catharsis","n.","تزکیه","aristotelian catharsis"),("chiaroscuro","n.","سایه‌روشن","renaissance chiaroscuro"),("classical","adj.","کلاسیک","classical music"),("collage","n.","کلاژ","photomontage collage"),("cubism","n.","کوبیسم","analytic cubism"),("dadaism","n.","دادائیسم","dadaist movement"),("expressionism","n.","اکسپرسیونیسم","german expressionism"),
# Group 30
("fresco","n.","دیوارنگاره","renaissance fresco"),("genre","n.","ژانر","literary genre"),("iconography","n.","شمایل‌نگاری","byzantine iconography"),("impressionism","n.","امپرسیونیسم","french impressionism"),("melodrama","n.","ملودرام","victorian melodrama"),("metaphor","n.","استعاره","extended metaphor"),("minimalism","n.","مینیمالیسم","architectural minimalism"),("modernism","n.","مدرنیسم","literary modernism"),("motif","n.","درون‌مایه","recurring motif"),("narrative","n.","روایت","nonlinear narrative"),("neoclassicism","n.","نئوکلاسیسیسم","art neoclassicism"),("nonfiction","n.","غیرداستانی","creative nonfiction"),("opera","n.","اپرا","grand opera"),("oratorio","n.","اوراتوریو","bach oratorio"),("parable","n.","مَثَل","biblical parable"),
# Group 31: Chemistry & Physics
("adsorption","n.","جذب سطحی","gas adsorption"),("alkaline","adj.","قلیایی","alkaline solution"),("allotrope","n.","دگرشکل","carbon allotrope"),("anion","n.","آنیون","negative anion"),("atom","n.","اتم","hydrogen atom"),("catalyst","n.","کاتالیزور","heterogeneous catalyst"),("cathode","n.","کاتد","cathode ray"),("covalent","adj.","کووالانسی","covalent bond"),("diffusion","n.","نفوذ","gaseous diffusion"),("electrode","n.","الکترود","inert electrode"),("entropy","n.","آنتروپی","entropy increase"),("fission","n.","شکافت","nuclear fission"),("fusion","n.","گداخت","thermonuclear fusion"),("hydraulic","adj.","هیدرولیک","hydraulic system"),("isotope","n.","ایزوتوپ","radioactive isotope"),
# Group 32
("kinetic","adj.","جنبشی","kinetic energy"),("molecule","n.","مولکول","organic molecule"),("neutron","n.","نوترون","neutron star"),("oxidation","n.","اکسیداسیون","oxidation state"),("photon","n.","فوتون","single photon"),("polymer","n.","پلیمر","synthetic polymer"),("proton","n.","پروتون","proton decay"),("quantum","n.","کوانتوم","quantum mechanics"),("radioactive","adj.","رادیواکتیو","radioactive decay"),("solvent","n.","حلال","polar solvent"),("spectrum","n.","طیف","electromagnetic spectrum"),("synthesis","n.","سنتز","chemical synthesis"),("thermal","adj.","حرارتی","thermal energy"),("valence","n.","ظرفیت","electron valence"),("viscosity","n.","گرانروی","fluid viscosity"),
# Group 33: Architecture & Urban
("acropolis","n.","آکروپولیس","ancient acropolis"),("amphitheater","n.","آمفی‌تئاتر","roman amphitheater"),("aqueduct","n.","آبراه","roman aqueduct"),("arcade","n.","طاق‌دار","shopping arcade"),("arch","n.","طاق","triumphal arch"),("atrium","n.","دهلیز","central atrium"),("balustrade","n.","نرده","marble balustrade"),("basilica","n.","بازیلیکا","byzantine basilica"),("cantilever","n.","طره","steel cantilever"),("colonnade","n.","ستون‌دار","neoclassical colonnade"),("cornice","n.","کتیبه","decorated cornice"),("cupola","n.","گنبدک","renaissance cupola"),("facade","n.","نما","building facade"),("frieze","n.","حاشیه","ionic frieze"),("gable","n.","شیروانی","triangular gable"),
# Group 34
("gazebo","n.","آلاچیق","wooden gazebo"),("lintel","n.","نعل درگاه","stone lintel"),("loggia","n.","ایوان","vatican loggia"),("mansion","n.","عمارت","georgian mansion"),("minaret","n.","مناره","tall minaret"),("pagoda","n.","پاگودا","japanese pagoda"),("parapet","n.","جان پناه","stone parapet"),("pediment","n.","سقف مثلثی","greek pediment"),("pillar","n.","ستون","stone pillar"),("portico","n.","رواق","columned portico"),("rotunda","n.","دایره‌وار","domed rotunda"),("spire","n.","گلدسته","church spire"),("stucco","n.","گچ‌بری","ornate stucco"),("terrace","n.","تراس","rooftop terrace"),("transept","n.","شبستان","cathedral transept"),
# Group 35: Music
("accelerando","n.","تندی","play accelerando"),("adagio","n.","آهسته","adagio movement"),("allegro","n.","تند","allegro tempo"),("arpeggio","n.","آرپژ","broken arpeggio"),("cadence","n.","آکورد پایانی","perfect cadence"),("crescendo","n.","اوج","gradual crescendo"),("diminuendo","n.","کاهش","diminuendo passage"),("fortissimo","n.","بسیار بلند","fortissimo section"),("fugue","n.","فوگ","bach fugue"),("harmony","n.","هماهنگی","vocal harmony"),("improvisation","n.","بداهه‌نوازی","jazz improvisation"),("legato","n.","متصل","play legato"),("melody","n.","ملودی","haunting melody"),("modulation","n.","مدولاسیون","key modulation"),("nocturne","n.","شب‌آهنگ","chopin nocturne"),
# Group 36
("obbligato","n.","اجباری","violin obbligato"),("orchestra","n.","ارکستر","symphony orchestra"),("overture","n.","اورتور","operatic overture"),("pizzicato","n.","پیتزیکاتو","string pizzicato"),("polyphony","n.","چندصدایی","renaissance polyphony"),("prelude","n.","پرلود","piano prelude"),("rhapsody","n.","رپسودی","hungarian rhapsody"),("sonata","n.","سونات","piano sonata"),("staccato","n.","قطع","staccato notes"),("symphony","n.","سمفونی","beethoven symphony"),("tempo","n.","ضرب‌آهنگ","slow tempo"),("timbre","n.","طنین","vocal timbre"),("vibrato","n.","لرزش","sing with vibrato"),("virtuoso","n.","استاد","violin virtuoso"),("aria","n.","آریا","operatic aria"),
# Group 37: Theater & Film
("antagonist","n.","ضدقهرمان","main antagonist"),("backdrop","n.","پس‌زمینه","scenic backdrop"),("catharsis","n.","تزکیه","emotional catharsis"),("climax","n.","اوج","dramatic climax"),("comedy","n.","کمدی","situational comedy"),("denouement","n.","گره‌گشایی","unexpected denouement"),("dialogue","n.","دیالوگ","witty dialogue"),("dramaturgy","n.","درام‌نویسی","modern dramaturgy"),("epilogue","n.","پایان‌سخن","emotional epilogue"),("farce","n.","مسخره","political farce"),("flashback","n.","بازگشت به گذشته","narrative flashback"),("genre","n.","ژانر","film genre"),("matinee","n.","نمایش عصر","matinee show"),("melodrama","n.","ملودرام","sentimental melodrama"),("mise-en-scene","n.","صحنه‌آرایی","elaborate mise-en-scene"),
# Group 38
("monologue","n.","تک‌گویی","internal monologue"),("montage","n.","تدوین","film montage"),("narrative","n.","روایت","compelling narrative"),("pathos","n.","احساسات","greek pathos"),("protagonist","n.","قهرمان","tragic protagonist"),("scenario","n.","سناریو","worst-case scenario"),("screenplay","n.","فیلمنامه","original screenplay"),("soliloquy","n.","تک‌گویی","hamlet soliloquy"),("staging","n.","صحنه‌آرایی","theatrical staging"),("subplot","n.","داستان فرعی","romantic subplot"),("tragedy","n.","تراژدی","greek tragedy"),("trilogy","n.","سه‌گانه","fantasy trilogy"),("vignette","n.","صحنه کوتاه","dramatic vignette"),("spectacle","n.","نمایش عظیم","hollywood spectacle"),("improvisation","n.","بداهه","comic improvisation"),
# Group 39: Cooking & Cuisine
("al dente","adj.","نرم و سفت","pasta al dente"),("appetizer","n.","پیش‌غذا","seafood appetizer"),("basting","n.","چرب‌کاری","turkey basting"),("bouillon","n.","آب گوشت","chicken bouillon"),("braising","n.","آب‌پز سرخ کرده","beef braising"),("brochette","n.","سیخی","shrimp brochette"),("caramelize","v.","کارامل کردن","onions caramelize"),("chiffonade","n.","سبزی خرد شده","basil chiffonade"),("confit","n.","کونفیت","duck confit"),("consomme","n.","آبگوشت صاف","clear consomme"),("deglaze","v.","لعابگیری","deglaze the pan"),("emulsion","n.","امولسیون","stable emulsion"),("fillet","n.","فیله","salmon fillet"),("flan","n.","فلان","caramel flan"),("gratin","n.","گراتن","potato gratin"),
# Group 40
("infusion","n.","دم‌کرده","herbal infusion"),("marinade","n.","مرینیت","zesty marinade"),("mousse","n.","موس","chocolate mousse"),("paella","n.","پائیا","spanish paella"),("puree","n.","پوره","tomato puree"),("ragout","n.","خورشت","vegetable ragout"),("risotto","n.","ریزوتو","mushroom risotto"),("roux","n.","رو","butter roux"),("sauté","v.","تفت دادن","sauté garlic"),("sous-vide","adj.","زیر خلأ","sous-vide cooking"),("soufflé","n.","سوفله","cheese soufflé"),("stock","n.","عصاره","beef stock"),("tapenade","n.","تاپناد","olive tapenade"),("terrine","n.","ترین","pork terrine"),("veloute","n.","ولوت","cream veloute"),
# Group 41: Fashion & Textiles
("brocade","n.","زربفت","silk brocade"),("chiffon","n.","شیفون","flowing chiffon"),("couture","n.","خیاطی","haute couture"),("denim","n.","جین","faded denim"),("embroidery","n.","گلدوزی","intricate embroidery"),("grosgrain","n.","گروگرین","grosgrain ribbon"),("knitwear","n.","بافتنی","cashmere knitwear"),("lamé","n.","براق","gold lamé"),("linen","n.","کتان","white linen"),("mannequin","n.","مانکن","dress mannequin"),("millinery","n.","کلاه‌دوزی","fashion millinery"),("organza","n.","ارگانزا","sheer organza"),("pleat","n.","چین","accordion pleat"),("satin","n.","ساتن","smooth satin"),("sequin","n.","پولک","sparkling sequin"),
# Group 42
("silk","n.","ابریشم","pure silk"),("taffeta","n.","تافته","crisp taffeta"),("tulle","n.","تول","bridal tulle"),("twill","n.","تویل","cotton twill"),("velvet","n.","مخمل","soft velvet"),("viscose","n.","ویسکوز","viscose rayon"),("weave","n.","بافت","tight weave"),("wool","n.","پشم","merino wool"),("jersey","n.","جرسی","cotton jersey"),("lace","n.","تور","delicate lace"),("applique","n.","چسبان","fabric applique"),("beading","n.","منجوق","intricate beading"),("crochet","n.","قلاب‌بافی","hand crochet"),("darning","n.","رفو","invisible darning"),("felting","n.","نمد","wool felting"),
# Group 43: Sports & Athletics
("acrobatics","n.","آکروباتیک","aerial acrobatics"),("archery","n.","تیراندازی با کمان","competitive archery"),("biathlon","n.","بیاتلون","winter biathlon"),("bobsleigh","n.","باب‌اسلژ","olympic bobsleigh"),("curling","n.","کرلینگ","canadian curling"),("decathlon","n.","دهگانه","olympic decathlon"),("equestrian","n.","سوارکاری","equestrian event"),("fencing","n.","شمشیربازی","olympic fencing"),("gymnastics","n.","ژیمناستیک","artistic gymnastics"),("heptathlon","n.","هفت‌گانه","women heptathlon"),("marathon","n.","ماراتن","london marathon"),("pentathlon","n.","پنج‌گانه","modern pentathlon"),("regatta","n.","مسابقه قایقرانی","sailing regatta"),("squash","n.","اسکواش","play squash"),("triathlon","n.","سه‌گانه","ironman triathlon"),
# Group 44
("tournament","n.","مسابقات","grand slam tournament"),("velodrome","n.","پیست دوچرخه‌سواری","indoor velodrome"),("yachting","n.","قایقرانی","yachting competition"),("athlete","n.","ورزشکار","professional athlete"),("championship","n.","قهرمانی","world championship"),("doping","n.","دوپینگ","blood doping"),("endurance","n.","استقامت","cardio endurance"),("fitness","n.","تناسب اندام","physical fitness"),("handicap","n.","ناتوانی","mental handicap"),("javelin","n.","نیزه","throw javelin"),("medley","n.","مختلط","swimming medley"),("podium","n.","سکو","victory podium"),("qualifier","n.","مرحله مقدماتی","olympic qualifier"),("sprint","n.","دو سرعت","100m sprint"),("workout","n.","تمرین","intense workout"),
# Group 45: Astronomy & Space
("asteroid","n.","سیارک","asteroid belt"),("aurora","n.","شفق","aurora borealis"),("black hole","n.","سیاهچاله","supermassive black hole"),("celestial","adj.","آسمانی","celestial body"),("comet","n.","دنباله‌دار","halley's comet"),("constellation","n.","صورت فلکی","zodiac constellation"),("cosmology","n.","کیهان‌شناسی","modern cosmology"),("eclipse","n.","خورشیدگرفتگی","solar eclipse"),("galaxy","n.","کهکشان","spiral galaxy"),("gravitational","adj.","گرانشی","gravitational lens"),("interstellar","adj.","میان‌ستاره‌ای","interstellar travel"),("meteorite","n.","شهاب‌سنگ","iron meteorite"),("nebula","n.","سحابی","orion nebula"),("observatory","n.","رصدخانه","astronomical observatory"),("orbit","n.","مدار","elliptical orbit"),
# Group 46
("parallax","n.","اختلاف منظر","stellar parallax"),("planetary","adj.","سیاره‌ای","planetary system"),("pulsar","n.","تپ‌اختر","neutron pulsar"),("quasar","n.","اختروش","distant quasar"),("satellite","n.","ماهواره","communications satellite"),("supernova","n.","ابرنواختر","supernova explosion"),("telescope","n.","تلسکوپ","hubble telescope"),("terraforming","n.","زمین‌سازی","mars terraforming"),("universe","n.","جهان","observable universe"),("asterism","n.","ستاره‌ک","winter asterism"),("aphelion","n.","اوج","summer aphelion"),("perihelion","n.","حضیض","january perihelion"),("syzygy","n.","مقابله","planetary syzygy"),("zenith","n.","سمت‌الرأس","solar zenith"),("zodiac","n.","منطقةالبروج","signs of zodiac"),
# Group 47: Botany & Agriculture
("angiosperm","n.","نهاندانه","flowering angiosperm"),("chlorophyll","n.","کلروفیل","chlorophyll pigment"),("cultivar","n.","رقم","hybrid cultivar"),("deciduous","adj.","خزان‌کننده","deciduous forest"),("dicotyledon","n.","دولپه‌ای","dicotyledon plant"),("endemic","adj.","بوم‌زاد","endemic species"),("evergreen","adj.","همیشه‌سبز","evergreen tree"),("fertilization","n.","باروری","cross fertilization"),("fibrous","adj.","فیبری","fibrous root"),("germination","n.","جوانه‌زنی","seed germination"),("herbaceous","adj.","علفی","herbaceous plant"),("inflorescence","n.","گل‌آذین","terminal inflorescence"),("latitude","n.","عرض جغرافیایی","northern latitude"),("legume","n.","حبوبات","nitrogen-fixing legume"),("mulch","n.","مالچ","organic mulch"),
# Group 48
("perennial","adj.","چندساله","perennial plant"),("photosynthesis","n.","فتوسنتز","rate of photosynthesis"),("pistil","n.","مادگی","flower pistil"),("pollen","n.","گرده","bee pollen"),("pollination","n.","گرده‌افشانی","cross pollination"),("rhizome","n.","ریزوم","bamboo rhizome"),("sepal","n.","کاسبرگ","green sepal"),("stamen","n.","پرچم","flower stamen"),("stomata","n.","روزنه","leaf stomata"),("symbiosis","n.","هم‌زیستی","mutual symbiosis"),("taproot","n.","ریشه اصلی","deep taproot"),("topiary","n.","هرس هنری","garden topiary"),("transpiration","n.","تعرق","plant transpiration"),("tuber","n.","غده","potato tuber"),("xylem","n.","آوند چوبی","xylem tissue"),
# Group 49: Zoology & Animals
("amphibian","n.","دوزیست","amphibian species"),("arboreal","adj.","درختی","arboreal primate"),("arthropod","n.","بندپا","marine arthropod"),("bioluminescence","n.","زیست‌تابی","deep-sea bioluminescence"),("camouflage","n.","استتار","natural camouflage"),("carnivore","n.","گوشت‌خوار","apex carnivore"),("cephalopod","n.","سرپایان","intelligent cephalopod"),("crustacean","n.","سخت‌پوست","decapod crustacean"),("diurnal","adj.","روزفعال","diurnal animal"),("echolocation","n.","پژواکیابی","bat echolocation"),("endotherm","n.","گرم‌خون","avian endotherm"),("estivation","n.","تابستان‌خوابی","snail estivation"),("gestation","n.","دوران بارداری","elephant gestation"),("hibernation","n.","زمستان‌خوابی","bear hibernation"),("invertebrate","n.","بی‌مهره","marine invertebrate"),
# Group 50
("marsupial","n.","کیسه‌دار","australian marsupial"),("migration","n.","مهاجرت","seasonal migration"),("mollusk","n.","نرم‌تن","gastropod mollusk"),("nocturnal","adj.","شب‌فعال","nocturnal predator"),("omnivore","n.","همه‌چیزخوار","opportunistic omnivore"),("plankton","n.","پلانکتون","microscopic plankton"),("predator","n.","شکارچی","ambush predator"),("reptile","n.","خزنده","scaly reptile"),("scavenger","n.","لاشه‌خوار","urban scavenger"),("species","n.","گونه","endangered species"),("vertebrate","n.","مهره‌دار","terrestrial vertebrate"),("viviparous","adj.","زنده‌زا","viviparous reproduction"),("ungulate","n.","سم‌دار","hoofed ungulate"),("vertebra","n.","مهره","cervical vertebra"),("taxonomy","n.","ردیف‌بندی","linnaean taxonomy"),
# Group 51: History & Civilization
("antiquity","n.","باستان","classical antiquity"),("archaeology","n.","باستان‌شناسی","underwater archaeology"),("barbarian","n.","بربر","germanic barbarian"),("caliphate","n.","خلافت","abbasid caliphate"),("cuneiform","n.","میخی","sumerian cuneiform"),("dynasty","n.","دودمان","ming dynasty"),("empire","n.","امپراتوری","byzantine empire"),("feudalism","n.","فئودالیسم","european feudalism"),("hieroglyph","n.","هیروگلیف","egyptian hieroglyph"),("medieval","adj.","قرون وسطی","medieval castle"),("monolith","n.","یکپارچه","stone monolith"),("mummy","n.","مومیایی","egyptian mummy"),("pharaoh","n.","فرعون","ancient pharaoh"),("reformation","n.","اصلاحات","protestant reformation"),("renaissance","n.","رنسانس","italian renaissance"),
# Group 52
("sultanate","n.","سلطنت","ottoman sultanate"),("tabernacle","n.","خیمه","biblical tabernacle"),("tributary","n.","خراجگزار","roman tributary"),("vassal","n.","رعیت","feudal vassal"),("ziggurat","n.","زیگورات","mesopotamian ziggurat"),("colony","n.","مستعمره","greek colony"),("civilization","n.","تمدن","mesoamerican civilization"),("artefact","n.","باستان‌یافته","bronze artefact"),("assimilation","n.","همسان‌سازی","roman assimilation"),("catacomb","n.","سردابه","roman catacomb"),("crusade","n.","جنگ صلیبی","third crusade"),("demography","n.","جمعیت‌شناسی","historical demography"),("diaspora","n.","پراکندگی","jewish diaspora"),("hegemony","n.","هژمونی","athenian hegemony"),("inquisition","n.","تفتیش عقاید","spanish inquisition"),
# Group 53: Diplomacy & International Relations
("ambassador","n.","سفیر","french ambassador"),("appeasement","n.","مماشات","policy of appeasement"),("bilateral","adj.","دوجانبه","bilateral agreement"),("consulate","n.","کن‌سولگری","general consulate"),("convention","n.","کنوانسیون","geneva convention"),("diplomacy","n.","دیپلماسی","shuttle diplomacy"),("embassy","n.","سفارت","british embassy"),("extradition","n.","استرداد","extradition treaty"),("legation","n.","نمایندگی","diplomatic legation"),("mediation","n.","میانجیگری","international mediation"),("multilateral","adj.","چندجانبه","multilateral forum"),("negotiation","n.","مذاکره","peace negotiations"),("nonproliferation","n.","منع گسترش","nuclear nonproliferation"),("protocol","n.","پروتکل","diplomatic protocol"),("ratification","n.","تصویب","treaty ratification"),
# Group 54
("reparation","n.","غرامت","war reparations"),("sanction","n.","تحریم","economic sanctions"),("sovereignty","n.","حاکمیت","national sovereignty"),("treaty","n.","پیمان","peace treaty"),("ultimatum","n.","ضرب‌الاجل","issue ultimatum"),("consensus","n.","اجماع","diplomatic consensus"),("delegation","n.","هیئت","trade delegation"),("accreditation","n.","اعتبارنامه","diplomatic accreditation"),("annexation","n.","الحاق","territorial annexation"),("asylum","n.","پناهندگی","political asylum"),("coexistence","n.","همزیستی","peaceful coexistence"),("demarcation","n.","تعیین مرز","border demarcation"),("enclave","n.","برون‌بوم","ethnic enclave"),("intervention","n.","مداخله","humanitarian intervention"),("mandate","n.","قیمومت","un mandate"),
# Group 55: Finance & Banking
("amortize","v.","استهلاک کردن","amortize the loan"),("annuity","n.","سالیانه","retirement annuity"),("appreciation","n.","افزایش ارزش","capital appreciation"),("arbitrage","n.","آربیتراژ","risk arbitrage"),("assessment","n.","ارزیابی","tax assessment"),("collateral","n.","وثیقه","loan collateral"),("depreciation","n.","استهلاک","currency depreciation"),("derivative","n.","مشتقه","financial derivative"),("dividend","n.","سود سهام","stock dividend"),("equity","n.","سهام","private equity"),("escrow","n.","ضمانت","in escrow"),("fiduciary","adj.","امانی","fiduciary duty"),("foreclosure","n.","تملیک","mortgage foreclosure"),("hedge","n.","پوشش ریسک","hedge fund"),("indemnity","n.","غرامت","insurance indemnity"),
# Group 56
("insolvency","n.","ورشکستگی","corporate insolvency"),("liquidation","n.","تصفیه","asset liquidation"),("marginal","adj.","حاشیه‌ای","marginal cost"),("maturity","n.","سررسید","bond maturity"),("mortgage","n.","رهن","housing mortgage"),("overdraft","n.","اضافه برداشت","bank overdraft"),("portfolio","n.","سبد","investment portfolio"),("premium","n.","صرف","insurance premium"),("refinance","v.","بازپرداخت","refinance the loan"),("solvency","n.","توانگری","financial solvency"),("speculation","n.","سفته‌بازی","market speculation"),("subsidy","n.","یارانه","government subsidy"),("tariff","n.","تعرفه","protective tariff"),("underwrite","v.","تضمین کردن","underwrite the issue"),("yield","n.","بازده","bond yield"),
# Group 57: Maritime & Naval
("anchorage","n.","لنگرگاه","safe anchorage"),("ballast","n.","بالاست","ship ballast"),("barge","n.","بارج","cargo barge"),("buoy","n.","بویه","navigation buoy"),("catamaran","n.","کاتاماران","luxury catamaran"),("deadweight","n.","وزن مرده","deadweight tonnage"),("dockyard","n.","کارخانه کشتی‌سازی","naval dockyard"),("dredge","v.","لایروبی","dredge the harbor"),("flotilla","n.","ناوگروه","naval flotilla"),("frigate","n.","ناوچه","missile frigate"),("harbor","n.","بندر","natural harbor"),("keel","n.","شناگاه","keel laying"),("lighthouse","n.","فانوس دریایی","coastal lighthouse"),("mooring","n.","پهلوگیری","secure mooring"),("nautical","adj.","دریایی","nautical mile"),
# Group 58
("navigate","v.","دریانوردی","navigate the strait"),("pier","n.","اسکله","concrete pier"),("piracy","n.","دزدی دریایی","somali piracy"),("schooner","n.","اسکونر","wooden schooner"),("shipwright","n.","کشتی‌ساز","master shipwright"),("sonar","n.","سونار","active sonar"),("submarine","n.","زیردریایی","nuclear submarine"),("tanker","n.","نفت‌کش","oil tanker"),("tonnage","n.","تناژ","gross tonnage"),("trawler","n.","ترالر","fishing trawler"),("tugboat","n.","یدک‌کش","powerful tugboat"),("vessel","n.","کشتی","merchant vessel"),("wharf","n.","اسکله","loading wharf"),("yacht","n.","قایق تفریحی","luxury yacht"),("maritime","adj.","دریایی","maritime law"),
# Group 59: Meteorology & Climate
("anemometer","n.","بادسنج","digital anemometer"),("anticyclone","n.","پادچرخند","strong anticyclone"),("barometer","n.","فشارسنج","mercury barometer"),("blizzard","n.","کولاک","severe blizzard"),("circulation","n.","گردش","atmospheric circulation"),("condensation","n.","میعان","cloud condensation"),("convection","n.","همرفت","thermal convection"),("cyclone","n.","چرخند","tropical cyclone"),("drought","n.","خشکسالی","severe drought"),("evaporation","n.","تبخیر","rate of evaporation"),("front","n.","جبهه","cold front"),("humidity","n.","رطوبت","relative humidity"),("hurricane","n.","طوفان","category hurricane"),("isobar","n.","همفشار","weather isobar"),("lightning","n.","صاعقه","thunderstorm lightning"),
# Group 60
("monsoon","n.","مونسون","indian monsoon"),("precipitation","n.","بارش","annual precipitation"),("barometric","adj.","فشاری","barometric pressure"),("squall","n.","تندباد","sudden squall"),("stratosphere","n.","استراتوسفر","upper stratosphere"),("tempest","n.","طوفان","tempestuous wind"),("thermometer","n.","دماسنج","digital thermometer"),("thunderstorm","n.","رعد و برق","severe thunderstorm"),("tornado","n.","گردباد","tornado warning"),("tropopause","n.","محدوده هوا","tropopause altitude"),("troposphere","n.","تروپوسفر","lower troposphere"),("typhoon","n.","تایفون","pacific typhoon"),("weather","n.","هوا","inclement weather"),("windward","adj.","بادگیر","windward side"),("vortex","n.","گردابه","polar vortex"),
# Group 61: Mining & Materials
("alloy","n.","آلیاژ","aluminum alloy"),("asbestos","n.","آزبست","toxic asbestos"),("basalt","n.","بازالت","volcanic basalt"),("bauxite","n.","بوکسیت","bauxite mining"),("ceramic","n.","سرامیک","dental ceramic"),("concrete","n.","بتن","reinforced concrete"),("copper","n.","مس","wrought copper"),("corundum","n.","کوراندوم","synthetic corundum"),("deposit","n.","ذخیره","mineral deposit"),("excavation","n.","حفاری","underground excavation"),("granite","n.","گرانیت","polished granite"),("graphite","n.","گرافیت","graphite electrode"),("limestone","n.","سنگ آهک","quarried limestone"),("manganese","n.","منگنز","manganese ore"),("marble","n.","مرمر","sculpted marble"),
# Group 62
("metallurgy","n.","متالورژی","extractive metallurgy"),("nickel","n.","نیکل","stainless nickel"),("ore","n.","سنگ معدن","iron ore"),("petroleum","n.","نفت","crude petroleum"),("platinum","n.","پلاتین","pure platinum"),("polymer","n.","پلیمر","synthetic polymer"),("quartz","n.","کوارتز","rose quartz"),("resin","n.","رزین","epoxy resin"),("sediment","n.","رسوب","sedimentary layer"),("silica","n.","سیلیس","fused silica"),("slag","n.","سرباره","steel slag"),("smelting","n.","گدازگری","copper smelting"),("solder","n.","لحیم","tin solder"),("timber","n.","چوب","structural timber"),("zinc","n.","روی","galvanized zinc"),
# Group 63: Photography & Optics
("aperture","n.","دیافراگم","wide aperture"),("bokeh","n.","بوکه","creamy bokeh"),("chromatic","adj.","رنگی","chromatic aberration"),("composition","n.","ترکیب‌بندی","photo composition"),("contrast","n.","کنتراست","high contrast"),("convergence","n.","همگرایی","lens convergence"),("diaphragm","n.","دیافراگم","adjustable diaphragm"),("diffraction","n.","پراش","light diffraction"),("distortion","n.","اعوجاج","barrel distortion"),("exposure","n.","نوردهی","long exposure"),("focal","adj.","کانونی","focal length"),("lens","n.","لنز","telephoto lens"),("microscope","n.","میکروسکوپ","electron microscope"),("monocular","n.","تک‌چشمی","compact monocular"),("negatives","n.","منفی","film negatives"),
# Group 64
("papillary","adj.","پاپیلاری","papillary lens"),("photography","n.","عکاسی","digital photography"),("polarization","n.","قطبی‌شدن","lens polarization"),("prism","n.","منشور","triangular prism"),("resolution","n.","وضوح","high resolution"),("shutter","n.","شاتر","mechanical shutter"),("spectrum","n.","طیف","visible spectrum"),("telephoto","adj.","دور‌نگار","telephoto lens"),("ultraviolet","adj.","فرابنفش","ultraviolet light"),("viewfinder","n.","نمایاب","digital viewfinder"),("vignette","n.","سایه‌روشن","photo vignette"),("wavelength","n.","طول موج","shorter wavelength"),("zoom","n.","زوم","optical zoom"),("macro","adj.","ماکرو","macro photography"),("birefringence","n.","دوشکستی","crystal birefringence"),
# Group 65: Religion & Theology
("absolution","n.","آمرزش","divine absolution"),("apocalypse","n.","آخرالزمان","biblical apocalypse"),("atheism","n.","بی‌خدایی","militant atheism"),("canon","n.","قانون","biblical canon"),("catechism","n.","کاتکیسم","catholic catechism"),("clergy","n.","روحانیون","secular clergy"),("confession","n.","اعتراف","auricular confession"),("congregation","n.","جماعت","church congregation"),("covenant","n.","عهد","old covenant"),("crucifixion","n.","تصلیب","the crucifixion"),("deity","n.","خدا","pagan deity"),("doctrine","n.","دکترین","religious doctrine"),("ecclesiastical","adj.","کلیسایی","ecclesiastical authority"),("excommunication","n.","تکفیر","papal excommunication"),("heresy","n.","بدعت","accused of heresy"),
# Group 66
("incarnation","n.","تجسد","divine incarnation"),("liturgy","n.","مناجات","divine liturgy"),("martyrdom","n.","شهادت","early christian martyrdom"),("monastery","n.","صومعه","buddhist monastery"),("ordination","n.","کشیشی","priestly ordination"),("pilgrimage","n.","زیارت","hajj pilgrimage"),("polytheism","n.","چندخدایی","ancient polytheism"),("prophecy","n.","پیشگویی","messianic prophecy"),("redemption","n.","رستگاری","christian redemption"),("relic","n.","یادگار","sacred relic"),("sacrament","n.","آیین","sacrament of baptism"),("salvation","n.","نجات","eternal salvation"),("scripture","n.","کتاب مقدس","hindu scripture"),("seminary","n.","حوزه علمیه","theological seminary"),("theology","n.","الهیات","systematic theology"),
# Group 67: Education & Pedagogy
("accreditation","n.","اعتباربخشی","university accreditation"),("andragogy","n.","آموزش بزرگسالان","principles of andragogy"),("assimilation","n.","جذب","cognitive assimilation"),("curriculum","n.","برنامه درسی","core curriculum"),("didactic","adj.","آموزنده","didactic approach"),("dissertation","n.","پایان‌نامه","doctoral dissertation"),("epistemology","n.","شناخت‌شناسی","educational epistemology"),("pedagogy","n.","آموزش","progressive pedagogy"),("lexicography","n.","فرهنگ‌نویسی","lexicography research"),("matriculation","n.","ثبت نام","university matriculation"),("metacognition","n.","فراشناخت","metacognitive skills"),("orthography","n.","املا","english orthography"),("pedagogue","n.","معلم","greek pedagogue"),("syllabus","n.","سرفصل","course syllabus"),("tuition","n.","شهریه","tuition fee"),
# Group 68
("undergraduate","n.","کارشناسی","undergraduate degree"),("vocation","n.","حرفه","vocational training"),("academy","n.","آکادمی","military academy"),("assessment","n.","ارزشیابی","formative assessment"),("baccalaureate","n.","دیپلم","international baccalaureate"),("calisthenics","n.","نرمش","morning calisthenics"),("discipline","n.","رشته","academic discipline"),("faculty","n.","دانشکده","arts faculty"),("graduate","n.","فارغ‌التحصیل","graduate student"),("interdisciplinary","adj.","بین‌رشته‌ای","interdisciplinary approach"),("lecture","n.","سخنرانی","public lecture"),("mentor","n.","راهنما","faculty mentor"),("scholarship","n.","بورسیه","merit scholarship"),("seminar","n.","سمینار","weekly seminar"),("tenure","n.","تصدی","academic tenure"),
# Group 69: Library & Publishing
("anthology","n.","گزیده","poetry anthology"),("bibliography","n.","کتاب‌شناسی","annotated bibliography"),("catalogue","n.","کاتالوگ","library catalogue"),("copyright","n.","حق نشر","copyright law"),("folio","n.","برگ","manuscript folio"),("foreword","n.","پیش‌گفتار","foreword by author"),("imprint","n.","نشان","publisher imprint"),("manuscript","n.","نسخه خطی","illuminated manuscript"),("monograph","n.","تک‌نوشت","scholarly monograph"),("periodical","n.","نشریه","academic periodical"),("plagiarism","n.","سرقت ادبی","academic plagiarism"),("pseudonym","n.","نام مستعار","write under pseudonym"),("publication","n.","انتشار","scientific publication"),("publisher","n.","ناشر","major publisher"),("anthologist","n.","گزیده‌نگار","noted anthologist"),
# Group 70
("serial","n.","مجموعه","serial publication"),("thesaurus","n.","هم‌معنا","online thesaurus"),("tome","n.","جلد","weighty tome"),("typesetting","n.","حروف‌چینی","digital typesetting"),("volume","n.","جلد","library volume"),("appendix","n.","ضمیمه","see appendix"),("compilation","n.","تألیف","poetry compilation"),("dissertation","n.","رساله","doctoral dissertation"),("draft","n.","پیش‌نویس","rough draft"),("editorial","adj.","ویراستاری","editorial board"),("index","n.","نمایه","subject index"),("installment","n.","قسمت","serial installment"),("preface","n.","دیباچه","author's preface"),("proofread","v.","ویرایش","proofread manuscript"),("addendum","n.","الحاقیه","report addendum"),
# Group 71: Medicine & Anatomy
("alimentary","adj.","گوارشی","alimentary canal"),("articular","adj.","مفصل","articular cartilage"),("bronchial","adj.","برونش","bronchial tube"),("cardiology","n.","قلب و عروق","interventional cardiology"),("cartilage","n.","غضروف","knee cartilage"),("cerebellum","n.","مخچه","cerebellar ataxia"),("cerebrum","n.","مخ","cerebral cortex"),("clavicle","n.","ترقوه","fractured clavicle"),("coagulation","n.","انعقاد","blood coagulation"),("coronary","adj.","کرونری","coronary artery"),("cranial","adj.","جمجمه‌ای","cranial nerve"),("dermis","n.","پوست","deep dermis"),("diaphragm","n.","دیافراگم","muscular diaphragm"),("epidermis","n.","روپوست","outer epidermis"),("femur","n.","استخوان ران","femoral fracture"),
# Group 72
("femur","n.","استخوان ران","femur fracture"),("fibula","n.","نازک‌نی","fibula bone"),("ganglion","n.","عقده","lymph ganglion"),("hemoglobin","n.","هموگلوبิน","oxygenated hemoglobin"),("hepatic","adj.","کبدی","hepatic artery"),("hormone","n.","هورمون","growth hormone"),("ligament","n.","رباط","torn ligament"),("lymphocyte","n.","لنفوسیت","b lymphocyte"),("medulla","n.","بصل النخاع","adrenal medulla"),("membrane","n.","غشا","cell membrane"),("neuron","n.","نورون","motor neuron"),("ovary","n.","تخمدان","polycystic ovary"),("pancreas","n.","لوزالمعده","pancreatic cancer"),("patella","n.","کشکک","kneecap patella"),("pelvis","n.","لگن","renal pelvis"),
# Group 73
("pericardium","n.","پیراشامه","cardiac pericardium"),("placenta","n.","جفت","uterine placenta"),("prosthesis","n.","پروتز","hip prosthesis"),("pulmonary","adj.","ریوی","pulmonary artery"),("retina","n.","شبکیه","retinal detachment"),("scapula","n.","کتف","scapular winging"),("sphincter","n.","اسفنگتر","anal sphincter"),("synapse","n.","سیناپس","neural synapse"),("tendon","n.","تاندون","achilles tendon"),("thorax","n.","قفسه سینه","thoracic cavity"),("thrombosis","n.","ترومبوز","venous thrombosis"),("thyroid","n.","تیروئید","hyperactive thyroid"),("vertebra","n.","مهره","cervical vertebra"),("viscera","n.","احشا","abdominal viscera"),("aorta","n.","آئورت","abdominal aorta"),
# Group 74: Psychology 2
("affect","n.","اثر","flat affect"),("aggression","n.","پرخاشگری","impulsive aggression"),("agnosia","n.","آگنوزی","visual agnosia"),("agoraphobia","n.","گذرهراسی","panic agoraphobia"),("anhedonia","n.","ناهنجاری","emotional anhedonia"),("aphasia","n.","آفازی","expressive aphasia"),("apraxia","n.","آپراکسی","constructional apraxia"),("astrology","n.","طالع‌بینی","western astrology"),("behaviorism","n.","رفتارگرایی","radical behaviorism"),("catharsis","n.","پالایش","emotional catharsis"),("claustrophobia","n.","تنگی هراسی","severe claustrophobia"),("compulsion","n.","اجبار","repetitive compulsion"),("conditioning","n.","شرطی‌سازی","operant conditioning"),("conversion","n.","تبدیل","conversion disorder"),("counseling","n.","مشاوره","grief counseling"),
# Group 75
("dementia","n.","زوال عقل","frontotemporal dementia"),("depersonalization","n.","شخصیت‌زدایی","depersonalization disorder"),("dissociation","n.","گسستگی","peritraumatic dissociation"),("dyslexia","n.","خوانش‌پریشی","developmental dyslexia"),("dysthymia","n.","دیس‌تایمی","chronic dysthymia"),("echolalia","n.","تکرارگویی","echolalic speech"),("empathy","n.","همدلی","affective empathy"),("etiology","n.","سبب‌شناسی","disease etiology"),("exhibitionism","n.","نمایش‌گری","sexual exhibitionism"),("extroversion","n.","برون‌گرایی","high extroversion"),("frustration","n.","سرخوردگی","frustration tolerance"),("gestalt","n.","گشتالت","gestalt therapy"),("hallucination","n.","توهم","auditory hallucination"),("hypnosis","n.","هیپنوتیزم","clinical hypnosis"),("hysteria","n.","هیستری","mass hysteria"),
# Group 76: Anthropology
("acculturation","n.","فرهنگ‌پذیری","forced acculturation"),("ancestor","n.","اجداد","common ancestor"),("animism","n.","جان‌باوری","tribal animism"),("anthropoid","adj.","انسان‌نما","anthropoid ape"),("archaic","adj.","کهن","archaic humans"),("craniometry","n.","جمجمه‌سنجی","forensic craniometry"),("cremation","n.","سوزاندن","traditional cremation"),("diffusionism","n.","گسترش‌گرایی","cultural diffusionism"),("ethnography","n.","مردم‌نگاری","visual ethnography"),("eugenics","n.","نژاد‌پروری","scientific eugenics"),("exogamy","n.","برون‌همسری","village exogamy"),("folklore","n.","فولکلور","irish folklore"),("genealogy","n.","تبارشناسی","family genealogy"),("hominid","n.","انسان‌سا","early hominid"),("indigenous","adj.","بومی","indigenous tribe"),
# Group 77
("lineage","n.","تبار","royal lineage"),("matriarchy","n.","مادرسالاری","matriarchal society"),("megalith","n.","سنگ‌مگال","stone megalith"),("mitochondrial","adj.","میتوکندریایی","mitochondrial dna"),("monogamy","n.","تک‌همسری","serial monogamy"),("neanderthal","n.","نئاندرتال","neanderthal skull"),("nomadic","adj.","کوچ‌نشین","nomadic lifestyle"),("paleolithic","adj.","پارینه‌سنگی","paleolithic era"),("polygamy","n.","چندهمسری","polygamous marriage"),("primitive","adj.","ابتدایی","primitive culture"),("shaman","n.","شامان","siberian shaman"),("sorcery","n.","جادو","black sorcery"),("taboo","n.","تابو","cultural taboo"),("totem","n.","توتم","tribal totem"),("tribe","n.","قبیله","native tribe"),
# Group 78: Economics 2
("aggregate","adj.","کل","aggregate demand"),("allocative","adj.","تخصیصی","allocative efficiency"),("austerity","n.","ریاضت","budget austerity"),("balance","n.","تراز","balance of payments"),("cartel","n.","کارتل","international cartel"),("conglomerate","n.","شرکت چندملیتی","media conglomerate"),("consumption","n.","مصرف","private consumption"),("deflation","n.","کاهش قیمت","persistent deflation"),("demographic","adj.","جمعیتی","demographic dividend"),("depression","n.","رکود بزرگ","economic depression"),("deregulation","n.","مقررات‌زدایی","financial deregulation"),("disinflation","n.","کاهش تورم","gradual disinflation"),("distribution","n.","توزیع","income distribution"),("duopoly","n.","انحصار دوگانه","market duopoly"),("elasticity","n.","کشش","price elasticity"),
# Group 79
("externalities","n.","اثرات جانبی","negative externalities"),("fiscal","adj.","مالی","fiscal policy"),("hyperinflation","n.","تورم شدید","german hyperinflation"),("indicator","n.","شاخص","economic indicator"),("inequality","n.","نابرابری","income inequality"),("inflation","n.","تورم","core inflation"),("interest","n.","بهره","interest rate"),("investment","n.","سرمایه‌گذاری","foreign investment"),("liquidity","n.","نقدینگی","market liquidity"),("macroeconomics","n.","اقتصاد کلان","keynesian macroeconomics"),("microeconomics","n.","اقتصاد خرد","neoclassical microeconomics"),("monetarism","n.","پول‌گرایی","monetarist theory"),("monopoly","n.","انحصار","natural monopoly"),("oligopoly","n.","انحصار چندگانه","corporate oligopoly"),("privatization","n.","خصوصی‌سازی","large-scale privatization"),
# Group 80: Geology 2
("anticline","n.","ناودیس","geologic anticline"),("bedrock","n.","سنگ بستر","granite bedrock"),("biostratigraphy","n.","چینه‌نگاری زیستی","biostratigraphic correlation"),("carboniferous","adj.","کربونیفر","carboniferous period"),("cretaceous","adj.","کرتاسه","cretaceous limestone"),("crustal","adj.","پوسته‌ای","crustal deformation"),("denudation","n.","فرسودگی","surface denudation"),("diagenesis","n.","سنگ‌شدگی","sediment diagenesis"),("eon","n.","دوران","geologic eon"),("epoch","n.","دوره","geologic epoch"),("era","n.","عصر","mesozoic era"),("fossilization","n.","سنگوارگی","rapid fossilization"),("geomorphology","n.","ژئومورفولوژی","fluvial geomorphology"),("glaciation","n.","یخبندان","quaternary glaciation"),("igneous","adj.","آذرین","igneous rock"),
# Group 81
("Jurassic","adj.","ژوراسیک","jurassic sandstone"),("lithosphere","n.","سنگ‌کره","continental lithosphere"),("magma","n.","ماگما","magma chamber"),("mantle","n.","گوشته","upper mantle"),("mesozoic","adj.","میان‌زیستی","mesozoic era"),("metamorphic","adj.","دگرگونی","metamorphic rock"),("orogeny","n.","کوه‌زایی","alpine orogeny"),("paleontology","n.","دیرینه‌شناسی","vertebrate paleontology"),("permafrost","n.","خاک منجمد","siberian permafrost"),("plateau","n.","فلات","tibetan plateau"),("sedimentary","adj.","رسوبی","sedimentary basin"),("seismic","adj.","لرزه‌ای","seismic activity"),("stratigraphy","n.","چینه‌شناسی","sequence stratigraphy"),("tectonic","adj.","زمین‌ساخت","tectonic plate"),("topography","n.","توپوگرافی","karst topography"),
# Group 82: Engineering
("aerodynamics","n.","آیرودینامیک","vehicle aerodynamics"),("actuator","n.","محرک","hydraulic actuator"),("annealing","n.","بازپخت","steel annealing"),("bearing","n.","بلبرینگ","ball bearing"),("cantilever","n.","طناب","steel cantilever"),("cavitation","n.","کاویتاسیون","pump cavitation"),("centrifugal","adj.","گریز از مرکز","centrifugal pump"),("compression","n.","فشردگی","axial compression"),("conduction","n.","رسانش","heat conduction"),("ductility","n.","چکش‌خواری","metal ductility"),("electrolysis","n.","الکترولیز","water electrolysis"),("fatigue","n.","خستگی","metal fatigue"),("friction","n.","اصطکاک","coefficient of friction"),("gyroscope","n.","ژیروسکوپ","fiber optic gyroscope"),("hydraulics","n.","هیدرولیک","fluid hydraulics"),
# Group 83
("kinematics","n.","سینماتیک","robot kinematics"),("lathe","n.","تراش","cnc lathe"),("leverage","n.","اهرم","mechanical leverage"),("lubrication","n.","روغن‌کاری","engine lubrication"),("machining","n.","ماشین‌کاری","precision machining"),("metallurgy","n.","متالورژی","extractive metallurgy"),("nozzle","n.","نازل","rocket nozzle"),("pneumatic","adj.","پنوماتیک","pneumatic system"),("propulsion","n.","پیشرانه","rocket propulsion"),("solenoid","n.","سولنویید","linear solenoid"),("stator","n.","استاتور","motor stator"),("tensile","adj.","کششی","tensile strength"),("torsion","n.","پیچش","torsion spring"),("turbine","n.","توربین","gas turbine"),("valve","n.","شیر","control valve"),
# Group 84: Law advanced
("abrogate","v.","لغو کردن","abrogate treaty"),("adjudicate","v.","داوری کردن","adjudicate dispute"),("annul","v.","باطل کردن","annul marriage"),("arbitrate","v.","داوری","arbitrate conflict"),("codicil","n.","الحاقیه","add codicil"),("collateral","adj.","وثیقه","collateral estoppel"),("contravene","v.","نقض کردن","contravene regulation"),("copyright","n.","کپی‌رایت","copyright infringement"),("depose","v.","شهادت دادن","depose witness"),("disclaim","v.","سلب کردن","disclaim interest"),("empanel","v.","تشکیل هیئت منصفه","empanel jury"),("enjoin","v.","منع کردن","enjoin violation"),("escheat","n.","بازگشت","right of escheat"),("exculpate","v.","تبرئه کردن","exculpatory evidence"),("extradite","v.","استرداد","extradite fugitive"),
# Group 85
("garnish","v.","مطالبه","garnish wages"),("indemnify","v.","غرامت دادن","indemnify loss"),("injunction","n.","دستور قضایی","preliminary injunction"),("judicature","n.","قوه قضاییه","supreme judicature"),("jurisprudence","n.","فقه","medical jurisprudence"),("laches","n.","اهمال","doctrine of laches"),("mandamus","n.","دستور الزام","writ of mandamus"),("mistrial","n.","محاکمه باطل","declare mistrial"),("novation","n.","جانشینی","obligation novation"),("probate","n.","تحریر","probate court"),("remand","v.","اعاده","remand custody"),("restitution","n.","اعاده","restitution order"),("sequester","v.","مصادره","sequester assets"),("subpoena","n.","احضاریه","issue subpoena"),("tort","n.","شبه‌جرم","civil tort"),
# Group 86: Communication & Media
("broadcast","n.","پخش","live broadcast"),("censorship","n.","سانسور","media censorship"),("circulation","n.","تیراژ","newspaper circulation"),("columnist","n.","ستون‌نویس","syndicated columnist"),("correspondent","n.","خبرنگار","war correspondent"),("documentary","n.","مستند","feature documentary"),("editorial","n.","سرمقاله","editorial board"),("journalism","n.","روزنامه‌نگاری","investigative journalism"),("newsletter","n.","خبرنامه","electronic newsletter"),("paparazzi","n.","پاپاراتزی","paparazzi photographer"),("photojournalism","n.","عکاسی خبری","war photojournalism"),("podcast","n.","پادکست","popular podcast"),("propaganda","n.","تبلیغات","propaganda machine"),("publicist","n.","روابط عمومی","celebrity publicist"),("tabloid","n.","تابلویید","tabloid journalism"),
# Group 87
("telecast","n.","پخش تلویزیونی","live telecast"),("wireless","adj.","بی‌سیم","wireless communication"),("anchor","n.","مجری","news anchor"),("blog","n.","وبلاگ","personal blog"),("bulletin","n.","بولتن","news bulletin"),("circulation","n.","انتشار","daily circulation"),("deadline","n.","آخرین مهلت","press deadline"),("disseminate","v.","گسترش","disseminate news"),("exclusive","n.","اختصاصی","media exclusive"),("headline","n.","تیتر","front page headline"),("legacy","adj.","سنتی","legacy media"),("media","n.","رسانه","mass media"),("newsroom","n.","خبرگزاری","digital newsroom"),("press","n.","مطبوعات","freedom of press"),("ratings","n.","رتبه‌بندی","tv ratings"),
# Group 88: Statistics & Data
("arithmetic","n.","حساب","modular arithmetic"),("bellwether","n.","شاخص","bellwether stock"),("bimodal","adj.","دو مدی","bimodal distribution"),("census","n.","سرشماری","population census"),("central","adj.","مرکزی","central tendency"),("coefficient","n.","ضریب","correlation coefficient"),("cohort","n.","گروه همگروه","birth cohort"),("collinearity","n.","هم‌خطی","detect collinearity"),("confidence","n.","اطمینان","confidence interval"),("correlation","n.","همبستگی","rank correlation"),("covariate","n.","هم‌وردا","adjust covariate"),("demeanor","n.","رفتار","statistical demeanor"),("deviation","n.","انحراف","standard deviation"),("dispersion","n.","پراکندگی","measure dispersion"),("distribution","n.","توزیع","normal distribution"),
# Group 89
("heteroscedastic","adj.","ناهمسانی","heteroscedastic data"),("histogram","n.","تنگ‌نما","frequency histogram"),("kurtosis","n.","کشیدگی","excess kurtosis"),("likelihood","n.","احتمال","maximum likelihood"),("mean","n.","میانگین","geometric mean"),("median","n.","میانه","sample median"),("percentile","n.","صدک","90th percentile"),("quartile","n.","چارک","lower quartile"),("regression","n.","رگرسیون","linear regression"),("skewness","n.","چولگی","negative skewness"),("standardize","v.","استاندارد","standardize data"),("statistic","n.","آمار","descriptive statistic"),("variance","n.","واریانس","analysis variance"),("bivariate","adj.","دو متغیره","bivariate analysis"),("multivariate","adj.","چندمتغیره","multivariate regression"),
# Group 90: Computing 2
("analog","adj.","آنالوگ","analog signal"),("ascii","n.","اسکی","ascii encoding"),("bandwidth","n.","پهنای باند","network bandwidth"),("boolean","adj.","بولی","boolean logic"),("buffer","n.","بافر","ring buffer"),("checksum","n.","مجموع کنترلی","file checksum"),("compiler","n.","کامپایلر","cross compiler"),("concurrency","n.","هم‌روندی","concurrent execution"),("daemon","n.","دیو","system daemon"),("database","n.","پایگاه داده","relational database"),("debugger","n.","اشکال‌زدا","kernel debugger"),("encryption","n.","رمزگذاری","asymmetric encryption"),("firmware","n.","سفت‌افزار","embedded firmware"),("garbage","n.","زباله","garbage collection"),("hash","n.","درهم‌سازی","hash table"),
# Group 91
("interrupt","n.","وقفه","hardware interrupt"),("kernel","n.","هسته","linux kernel"),("latency","n.","تأخیر","low latency"),("metadata","n.","فراداده","file metadata"),("middleware","n.","میان‌افزار","message middleware"),("multithreading","n.","چندنخی","multithreaded programming"),("namespace","n.","فضای نام","global namespace"),("parsing","n.","تجزیه","xml parsing"),("pipeline","n.","خط لوله","ci pipeline"),("recursion","n.","بازگشتی","infinite recursion"),("scalability","n.","مقیاس‌پذیری","horizontal scalability"),("semaphore","n.","سمفور","binary semaphore"),("serialization","n.","رشته‌سازی","data serialization"),("throughput","n.","توان","network throughput"),("token","n.","نشانه","authentication token"),
# Group 92: Natural Sciences
("biodiversity","n.","تنوع زیستی","marine biodiversity"),("carbon","n.","کربن","carbon cycle"),("chlorofluorocarbon","n.","کلروفلوئوروکربن","cfc emissions"),("climatic","adj.","اقلیمی","climatic change"),("decomposer","n.","تجزیه‌گر","soil decomposer"),("detritus","n.","آوار","organic detritus"),("ecology","n.","بوم‌شناسی","landscape ecology"),("ecotone","n.","اکوتون","forest ecotone"),("evapotranspiration","n.","تعرق","actual evapotranspiration"),("food web","n.","شبکه غذایی","marine food web"),("greenhouse","n.","گلخانه‌ای","greenhouse gas"),("keystone","n.","کلیدی","keystone species"),("mycorrhiza","n.","قارچ ریشه","arbuscular mycorrhiza"),("ozone","n.","ازن","ozone depletion"),("photosynthesis","n.","فتوسنتز","net photosynthesis"),
# Group 93
("phytoplankton","n.","فیتوپلانکتون","marine phytoplankton"),("pollination","n.","گرده‌افشانی","insect pollination"),("rainforest","n.","جنگل بارانی","tropical rainforest"),("riparian","adj.","کناررودی","riparian zone"),("savanna","n.","ساوانا","african savanna"),("succession","n.","توالی","ecological succession"),("sustainability","n.","پایداری","environmental sustainability"),("symbiosis","n.","همزیستی","mutualistic symbiosis"),("taxonomy","n.","طبقه‌بندی","biological taxonomy"),("watershed","n.","حوضه آبریز","watershed management"),("wetland","n.","تالاب","coastal wetland"),("biome","n.","زیست‌بوم","terrestrial biome"),("canopy","n.","تاج پوشش","forest canopy"),("detritivore","n.","آوارخوار","soil detritivore"),("endemic","adj.","بوم‌زاد","endemic plant"),
# Group 94: Philosophy & Ethics 2
("absolutism","n.","مطلق‌گرایی","moral absolutism"),("agnosticism","n.","ندانم‌گرایی","philosophical agnosticism"),("altruism","n.","نوع‌دوستی","evolutionary altruism"),("consequentialism","n.","نتیجه‌گرایی","utilitarian consequentialism"),("constructivism","n.","ساخت‌گرایی","social constructivism"),("deontology","n.","وظیفه‌گرایی","kantian deontology"),("determinism","n.","جبرگرایی","hard determinism"),("empiricism","n.","تجربه‌گرایی","british empiricism"),("epicureanism","n.","اپیکوریسم","epicurean philosophy"),("epiphenomenalism","n.","پدیدارگرایی","epiphenomenal consciousness"),("essentialism","n.","ذات‌گرایی","gender essentialism"),("existentialism","n.","اگزیستانسیالیسم","sartrian existentialism"),("hedonism","n.","لذت‌گرایی","psychological hedonism"),("humanism","n.","انسان‌گرایی","secular humanism"),("idealism","n.","آرمان‌گرایی","german idealism"),
# Group 95
("libertarianism","n.","آزادی‌خواهی","left libertarianism"),("materialism","n.","ماده‌گرایی","dialectical materialism"),("naturalism","n.","طبیعت‌گرایی","methodological naturalism"),("nihilism","n.","پوچ‌گرایی","moral nihilism"),("objectivism","n.","عینیت‌گرایی","rand objectivism"),("pantheism","n.","همه‌خدایی","spinozistic pantheism"),("phenomenalism","n.","پدیده‌گرایی","berkeley phenomenalism"),("positivism","n.","اثبات‌گرایی","logical positivism"),("pragmatism","n.","عمل‌گرایی","american pragmatism"),("rationalism","n.","عقل‌گرایی","continental rationalism"),("realism","n.","واقع‌گرایی","philosophical realism"),("reductionism","n.","فروکاست‌گرایی","scientific reductionism"),("relativism","n.","نسبی‌گرایی","cultural relativism"),("skepticism","n.","شک‌گرایی","philosophical skepticism"),("solipsism","n.","خودتنهاانگاری","methodological solipsism"),
# Group 96: More Adjectives
("abject","adj.","بدبخت","abject poverty"),("abrasive","adj.","ساینده","abrasive personality"),("abstract","adj.","انتزاعی","abstract concept"),("accidental","adj.","تصادفی","accidental discovery"),("accountable","adj.","مسئول","politically accountable"),("accumulated","adj.","انباشته","accumulated wealth"),("acerbic","adj.","ترش","acerbic wit"),("acoustic","adj.","صوتی","acoustic guitar"),("acrobatic","adj.","آکروباتیک","acrobatic maneuver"),("adaptable","adj.","سازگار","highly adaptable"),("addictive","adj.","اعتیادآور","highly addictive"),("adept","adj.","ماهر","technically adept"),("adjacent","adj.","مجاور","adjacent room"),("administrative","adj.","اداری","administrative assistant"),("adorable","adj.","دوست‌داشتنی","adorable puppy"),
# Group 97
("adventurous","adj.","ماجراجو","adventurous spirit"),("aerial","adj.","هوایی","aerial view"),("aesthetic","adj.","زیبایی‌شناختی","aesthetic pleasure"),("affable","adj.","خوش‌برخورد","affable manner"),("affectionate","adj.","مهربان","affectionate gesture"),("affirmative","adj.","ایجابی","affirmative response"),("agile","adj.","چابک","agile methodology"),("agonizing","adj.","دردناک","agonizing decision"),("agreeable","adj.","خوشایند","agreeable weather"),("ajar","adj.","نیمه‌باز","door ajar"),("akin","adj.","مشابه","akin to"),("alarming","adj.","نگران‌کننده","alarming rate"),("alert","adj.","هشیار","alert and focused"),("alien","adj.","بیگانه","alien concept"),("alive","adj.","زنده","alive and well"),
# Group 98
("alluring","adj.","فریبنده","alluring smile"),("almighty","adj.","قادر مطلق","almighty god"),("aloof","adj.","دور","aloof demeanor"),("alternate","adj.","جایگزین","alternate route"),("amateur","adj.","مبتدی","amateur photographer"),("amazing","adj.","شگفت‌انگیز","amazing discovery"),("ambiguous","adj.","مبهم","ambiguous statement"),("ambitious","adj.","جاه‌طلب","ambitious goal"),("amiable","adj.","خوش‌خلق","amiable host"),("amicable","adj.","دوستانه","amicable divorce"),("ample","adj.","فراوان","ample opportunity"),("amusing","adj.","سرگرم‌کننده","amusing anecdote"),("ancient","adj.","باستانی","ancient civilization"),("angry","adj.","عصبانی","angry protest"),("animated","adj.","سرزنده","animated discussion"),
# Group 99
("annoying","adj.","آزاردهنده","annoying habit"),("annual","adj.","سالیانه","annual report"),("anonymous","adj.","ناشناس","anonymous donor"),("antarctic","adj.","جنوبگان","antarctic ice"),("anticipated","adj.","مورد انتظار","highly anticipated"),("anxious","adj.","مضطرب","anxious waiting"),("apathetic","adj.","بی‌تفاوت","apathetic electorate"),("apparent","adj.","آشکار","apparent contradiction"),("appealing","adj.","جذاب","visually appealing"),("applicable","adj.","قابل اجرا","applicable law"),("appreciative","adj.","قدردان","appreciative audience"),("apprehensive","adj.","نگران","apprehensive about"),("approachable","adj.","دست‌یافتنی","approachable manager"),("appropriate","adj.","مناسب","appropriate action"),("approximate","adj.","تقریبی","approximate value"),
# Group 100
("aquatic","adj.","آبی","aquatic ecosystem"),("arable","adj.","قابل کشت","arable land"),("arctic","adj.","شمالگان","arctic circle"),("ardent","adj.","پر شور","ardent supporter"),("arduous","adj.","طاقت‌فرسا","arduous journey"),("aromatic","adj.","معطر","aromatic herbs"),("arrogant","adj.","متکبر","arrogant attitude"),("articulate","adj.","خوش‌بیان","articulate speaker"),("artificial","adj.","مصنوعی","artificial intelligence"),("artistic","adj.","هنری","artistic expression"),("ashamed","adj.","شرمنده","ashamed admission"),("aspiring","adj.","آرزومند","aspiring actor"),("assertive","adj.","جسور","assertive communication"),("assorted","adj.","متنوع","assorted colors"),("astonishing","adj.","حیرت‌انگیز","astonishing result"),
# Group 101: More Nouns
("abbreviation","n.","اختصار","common abbreviation"),("abolition","n.","لغو","abolition of slavery"),("abomination","n.","نفرت","act of abomination"),("abrasion","n.","خراش","skin abrasion"),("abruption","n.","جدایی","placental abruption"),("absorption","n.","جذب","drug absorption"),("abstention","n.","ممتنع","vote abstention"),("abundance","n.","فراوانی","abundance of caution"),("abyss","n.","پرتهافکنی","deep abyss"),("academic","n.","دانشگاهی","distinguished academic"),("academy","n.","آکادمی","national academy"),("accent","n.","لهجه","foreign accent"),("acceptance","n.","پذیرش","social acceptance"),("access","n.","دسترسی","internet access"),("acclaim","n.","تحسین","critical acclaim"),
# Group 102
("accommodation","n.","اسکان","reasonable accommodation"),("accompaniment","n.","همراهی","musical accompaniment"),("accomplishment","n.","دستاورد","great accomplishment"),("account","n.","حساب","bank account"),("accountability","n.","پاسخگویی","transparency accountability"),("accounting","n.","حسابداری","financial accounting"),("accumulation","n.","انباشت","capital accumulation"),("accuracy","n.","دقت","historical accuracy"),("accusation","n.","اتهام","false accusation"),("achievability","n.","قابلیت دستیابی","goal achievability"),("achievement","n.","موفقیت","outstanding achievement"),("acknowledgment","n.","تشکر","formal acknowledgment"),("acquisition","n.","اکتساب","language acquisition"),("acquittal","n.","تبرئه","complete acquittal"),("actuality","n.","واقعیت","in actuality"),
# Group 103
("adaptability","n.","سازگاری","organizational adaptability"),("addiction","n.","اعتیاد","substance addiction"),("adherence","n.","پایبندی","strict adherence"),("adjunct","n.","وابسته","research adjunct"),("adjustment","n.","تعدیل","structural adjustment"),("administration","n.","مدیریت","business administration"),("admiration","n.","تحسین","mutual admiration"),("admission","n.","پذیرش","college admission"),("adolescence","n.","نوجوانی","early adolescence"),("adoption","n.","پذیرش","child adoption"),("adulation","n.","تملق","public adulation"),("advancement","n.","پیشرفت","career advancement"),("advantage","n.","مزیت","competitive advantage"),("adventure","n.","ماجراجویی","great adventure"),("adversity","n.","مصیبت","face adversity"),
# Group 104
("advocacy","n.","حمایت","advocacy group"),("aesthetics","n.","زیبایی‌شناسی","modern aesthetics"),("affection","n.","محبت","deep affection"),("affirmation","n.","تأکید","self affirmation"),("affliction","n.","رنج","human affliction"),("aftermath","n.","عواقب","aftermath of war"),("aggregate","n.","مجموع","in the aggregate"),("aggression","n.","تجاوز","military aggression"),("agility","n.","چابکی","mental agility"),("agitation","n.","تهییج","political agitation"),("agnosticism","n.","ندانم‌گرایی","philosophical agnosticism"),("agony","n.","عذاب","sheer agony"),("agreement","n.","توافق","trade agreement"),("aide","n.","دستیار","presidential aide"),("ailment","n.","بیماری","chronic ailment"),
# Group 105
("airfare","n.","کرایه هواپیما","cheap airfare"),("airfield","n.","فرودگاه","military airfield"),("airlift","n.","پل هوایی","humanitarian airlift"),("airspace","n.","فضای هوایی","territorial airspace"),("alarm","n.","خطر","false alarm"),("alert","n.","هشدار","terror alert"),("alienation","n.","بیگانگی","social alienation"),("alignment","n.","هم‌راستایی","strategic alignment"),("allocation","n.","تخصیص","budget allocation"),("allotment","n.","سهمیه","land allotment"),("allowance","n.","کمک هزینه","travel allowance"),("allusion","n.","اشاره","literary allusion"),("alteration","n.","تغییر","genetic alteration"),("altercation","n.","مشاجره","verbal altercation"),("alternative","n.","جایگزین","viable alternative"),
# Group 106
("altitude","n.","ارتفاع","high altitude"),("amalgamation","n.","ادغام","corporate amalgamation"),("amazement","n.","شگفتی","in amazement"),("ambiance","n.","جو","restaurant ambiance"),("ambiguity","n.","ابهام","strategic ambiguity"),("ambition","n.","جاه‌طلبی","driving ambition"),("amelioration","n.","بهبود","social amelioration"),("amendment","n.","اصلاحیه","constitutional amendment"),("ammunition","n.","مهمات","live ammunition"),("amnesty","n.","عفو","general amnesty"),("amplitude","n.","دامنه","signal amplitude"),("amusement","n.","سرگرمی","place of amusement"),("analogy","n.","قیاس","drawn analogy"),("analysis","n.","تحلیل","in-depth analysis"),("anarchy","n.","هرج و مرج","state of anarchy"),
# Group 107: Additional Verbs
("abandon","v.","رها کردن","abandon hope"),("abolish","v.","لغو کردن","abolish slavery"),("abstain","v.","خودداری","abstain from voting"),("accelerate","v.","سرعت بخشیدن","accelerate growth"),("accentuate","v.","برجسته کردن","accentuate features"),("accommodate","v.","اسکان دادن","accommodate guests"),("accompany","v.","همراهی کردن","accompany the singer"),("accomplish","v.","انجام دادن","accomplish goal"),("accuse","v.","متهم کردن","accuse falsely"),("achieve","v.","دستیافتن","achieve success"),("acknowledge","v.","تصدیق کردن","acknowledge receipt"),("acquire","v.","به دست آوردن","acquire knowledge"),("adapt","v.","سازگار شدن","adapt to change"),("adhere","v.","پایبند بودن","adhere strictly"),("adjust","v.","تعدیل کردن","adjust accordingly"),
# Group 108
("administer","v.","مدیریت کردن","administer medication"),("admire","v.","تحسین کردن","admire courage"),("admit","v.","پذیرفتن","admit mistake"),("adopt","v.","پذیرفتن","adopt policy"),("advance","v.","پیشرفت کردن","advance career"),("advertise","v.","تبلیغ کردن","advertise product"),("advise","v.","توصیه کردن","advise clients"),("advocate","v.","حمایت کردن","advocate reform"),("affirm","v.","تأکید کردن","affirm commitment"),("afford","v.","توانایی","afford luxury"),("aggregate","v.","جمع کردن","aggregate data"),("agitate","v.","تهییج کردن","agitate crowd"),("agree","v.","موافقت کردن","agree entirely"),("aid","v.","کمک کردن","aid development"),("aim","v.","هدف گرفتن","aim precisely"),
# Group 109
("alert","v.","هشدار دادن","alert authorities"),("allege","v.","ادعا کردن","allege fraud"),("allocate","v.","تخصیص دادن","allocate resources"),("alter","v.","تغییر دادن","alter course"),("alternate","v.","جابجا شدن","alternate shifts"),("amaze","v.","شگفت زده کردن","amaze audience"),("amend","v.","اصلاح کردن","amend constitution"),("amplify","v.","تقویت کردن","amplify signal"),("analyze","v.","تحلیل کردن","analyze data"),("anchor","v.","لنگر انداختن","anchor ship"),("announce","v.","اعلام کردن","announce decision"),("annoy","v.","آزار دادن","annoy neighbors"),("anticipate","v.","پیش‌بینی کردن","anticipate needs"),("apologize","v.","عذرخواهی","apologize sincerely"),("appear","v.","ظاهر شدن","appear suddenly"),
# Group 110
("applaud","v.","تشویق کردن","applaud effort"),("apply","v.","اعمال کردن","apply pressure"),("appoint","v.","منصوب کردن","appoint director"),("appreciate","v.","قدردانی","appreciate help"),("approach","v.","نزدیک شدن","approach cautiously"),("approve","v.","تأیید کردن","approve proposal"),("argue","v.","بحث کردن","argue forcefully"),("arise","v.","برخاستن","arise early"),("arrange","v.","ترتیب دادن","arrange meeting"),("arrest","v.","دستگیر کردن","arrest suspect"),("articulate","v.","بیان کردن","articulate clearly"),("ascend","v.","صعود کردن","ascend quickly"),("ask","v.","پرسیدن","ask politely"),("assemble","v.","جمع کردن","assemble team"),("assess","v.","ارزیابی کردن","assess risk"),
# Group 111
("assign","v.","تخصیص دادن","assign task"),("assist","v.","کمک کردن","assist customer"),("associate","v.","مرتبط کردن","associate with"),("assume","v.","فرض کردن","assume responsibility"),("assure","v.","اطمینان دادن","assure safety"),("attach","v.","ضمیمه کردن","attach file"),("attempt","v.","تلاش کردن","attempt rescue"),("attend","v.","شرکت کردن","attend conference"),("attract","v.","جذب کردن","attract attention"),("attribute","v.","نسبت دادن","attribute success"),("audit","v.","حسابرسی","audit accounts"),("augment","v.","افزایش دادن","augment income"),("authorize","v.","مجوز دادن","authorize payment"),("automate","v.","خودکار کردن","automate process"),("avail","v.","استفاده کردن","avail opportunity"),
# Group 112: Additional Adverbs
("abnormally","adv.","غیرعادی","abnormally high"),("absolutely","adv.","کاملاً","absolutely necessary"),("abundantly","adv.","فراوان","abundantly clear"),("accordingly","adv.","مطابق","act accordingly"),("accurately","adv.","دقیقاً","measure accurately"),("actively","adv.","فعالانه","actively involved"),("actually","adv.","در واقع","actually happened"),("adequately","adv.","به‌اندازه","adequately prepared"),("admittedly","adv.","مسلماً","admittedly difficult"),("adversely","adv.","ناخواسته","adversely affected"),("advisably","adv.","توصیه‌پذیر","act advisably"),("aggressively","adv.","تهاجمی","aggressively pursue"),("allegedly","adv.","ظاهراً","allegedly involved"),("altogether","adv.","کلاً","altogether different"),("annually","adv.","سالانه","reported annually"),
# Group 113
("apparently","adv.","ظاهراً","apparently unaware"),("appropriately","adv.","مناسب","dress appropriately"),("approximately","adv.","تقریباً","approximately equal"),("arbitrarily","adv.","خودسرانه","chosen arbitrarily"),("automatically","adv.","خودکار","automatically update"),("barely","adv.","به سختی","barely visible"),("categorically","adv.","قطعی","categorically deny"),("certainly","adv.","مسلماً","certainly true"),("clearly","adv.","واضح","clearly defined"),("collectively","adv.","دستجمعی","collectively responsible"),("comparatively","adv.","نسبتاً","comparatively small"),("completely","adv.","کاملاً","completely different"),("consequently","adv.","در نتیجه","consequently failed"),("considerably","adv.","قابل توجه","considerably better"),("consistently","adv.","مداوم","consistently good"),
# Group 114
("constantly","adv.","مداوم","constantly changing"),("continually","adv.","پیوسته","continually improving"),("continuously","adv.","به طور مداوم","continuously monitor"),("conversely","adv.","برعکس","conversely stated"),("correctly","adv.","درست","correctly identified"),("critically","adv.","بحرانی","critically important"),("decisively","adv.","قطعی","decisively win"),("definitely","adv.","قطعاً","definitely worth"),("deliberately","adv.","عمداً","deliberately chosen"),("dramatically","adv.","دراماتیک","dramatically change"),("effectively","adv.","موثر","effectively manage"),("efficiently","adv.","کارآمد","operate efficiently"),("enormously","adv.","بسیار","enormously helpful"),("entirely","adv.","کاملاً","entirely different"),("equally","adv.","به طور مساوی","equally important"),
# Group 115
("essentially","adv.","اساساً","essentially the same"),("eventually","adv.","در نهایت","eventually succeed"),("evidently","adv.","مشخصاً","evidently pleased"),("exactly","adv.","دقیقاً","exactly right"),("excessively","adv.","بیش از حد","excessively high"),("exclusively","adv.","انحصاری","exclusively available"),("explicitly","adv.","صریحاً","explicitly stated"),("extremely","adv.","فوق‌العاده","extremely difficult"),("fortunately","adv.","خوشبختانه","fortunately survived"),("frequently","adv.","مکرراً","frequently asked"),("fundamentally","adv.","اساساً","fundamentally change"),("generally","adv.","عموماً","generally accepted"),("gradually","adv.","تدریجاً","gradually improve"),("heavily","adv.","سنگین","heavily influenced"),("highly","adv.","بسیار","highly recommended"),
# Group 116
("immediately","adv.","بلافاصله","immediately respond"),("immensely","adv.","بسیار","immensely popular"),("increasingly","adv.","به طور فزاینده","increasingly important"),("indeed","adv.","در حقیقت","indeed remarkable"),("inevitably","adv.","ناگزیر","inevitably lead"),("initially","adv.","ابتداً","initially proposed"),("instantly","adv.","فوراً","instantly recognizable"),("intensely","adv.","شدیداً","intensely competitive"),("invariably","adv.","همیشه","invariably correct"),("largely","adv.","عمدتاً","largely responsible"),("literally","adv.","لفظاً","literally speaking"),("mainly","adv.","عمدتاً","mainly concerned"),("markedly","adv.","به طور محسوس","markedly different"),("merely","adv.","صرفاً","merely suggested"),("namely","adv.","یعنی","namely"),
# Group 117
("necessarily","adv.","الزاماً","necessarily true"),("notably","adv.","به ویژه","notably absent"),("noticeably","adv.","محسوس","noticeably improved"),("obviously","adv.","واضحاً","obviously wrong"),("occasionally","adv.","گاه‌گاه","occasionally visit"),("openly","adv.","آشکارا","openly critical"),("optionally","adv.","اختیاری","optionally available"),("overly","adv.","بیش از حد","overly optimistic"),("particularly","adv.","به خصوص","particularly interesting"),("perfectly","adv.","کاملاً","perfectly clear"),("permanently","adv.","دائماً","permanently closed"),("persistently","adv.","مداوم","persistently denied"),("practically","adv.","عملاً","practically impossible"),("precisely","adv.","دقیقاً","precisely measured"),("predominantly","adv.","عمدتاً","predominantly white"),
# Group 118
("predominantly","adv.","غالباً","predominantly male"),("primarily","adv.","عمدتاً","primarily focused"),("profoundly","adv.","عمیقاً","profoundly affected"),("progressively","adv.","پیشرونده","progressively worse"),("prominently","adv.","برجسته","prominently displayed"),("promptly","adv.","سریعاً","promptly responded"),("properly","adv.","به درستی","properly installed"),("proportionally","adv.","متناسب","proportionally distributed"),("publicly","adv.","علنی","publicly available"),("purely","adv.","صرفاً","purely academic"),("quickly","adv.","سریع","quickly became"),("quietly","adv.","آرام","quietly whispered"),("radically","adv.","بنیادین","radically changed"),("randomly","adv.","تصادفی","randomly selected"),("rapidly","adv.","سریع","rapidly growing"),
# Group 119
("readily","adv.","آماده","readily available"),("really","adv.","واقعاً","really impressive"),("recently","adv.","اخیراً","recently discovered"),("regularly","adv.","منظم","regularly scheduled"),("relatively","adv.","نسبتاً","relatively simple"),("remarkably","adv.","شگفت‌آور","remarkably accurate"),("repeatedly","adv.","مکرراً","repeatedly warned"),("reportedly","adv.","به گزارش","reportedly said"),("respectively","adv.","به ترتیب","respectively named"),("roughly","adv.","تقریباً","roughly equivalent"),("routinely","adv.","روتین","routinely performed"),("seemingly","adv.","به نظر می‌رسد","seemingly endless"),("separately","adv.","جداگانه","separately listed"),("seriously","adv.","جدی","seriously injured"),("severely","adv.","شدید","severely damaged"),
# Group 120
("sharply","adv.","تیز","sharply criticized"),("shortly","adv.","به زودی","shortly after"),("significantly","adv.","به طور معنی‌دار","significantly different"),("similarly","adv.","به طور مشابه","similarly structured"),("simply","adv.","ساده","simply stated"),("simultaneously","adv.","همزمان","simultaneously occurred"),("slightly","adv.","کمی","slightly different"),("slowly","adv.","آهسته","slowly changing"),("smoothly","adv.","روان","smoothly operating"),("solely","adv.","صرفاً","solely responsible"),("specially","adv.","مخصوصاً","specially designed"),("specifically","adv.","مشخصاً","specifically mentioned"),("steadily","adv.","پایدار","steadily increasing"),("strictly","adv.","سختگیرانه","strictly prohibited"),("strongly","adv.","قویاً","strongly recommend"),
# Group 121
("substantially","adv.","به طور قابل توجه","substantially different"),("successfully","adv.","موفق","successfully completed"),("suddenly","adv.","ناگهان","suddenly appeared"),("sufficiently","adv.","به اندازه","sufficiently prepared"),("suitably","adv.","مناسب","suitably qualified"),("summarily","adv.","خلاصه","summarily dismissed"),("superficially","adv.","سطحی","superficially similar"),("supposedly","adv.","ظاهراً","supposedly safe"),("surely","adv.","مطمئناً","surely you know"),("surprisingly","adv.","غافلگیرانه","surprisingly easy"),("systematically","adv.","سیستماتیک","systematically organized"),("technically","adv.","فنی","technically correct"),("temporarily","adv.","موقتاً","temporarily suspended"),("tenderly","adv.","مهربان","tenderly cared"),("terribly","adv.","وحشتناک","terribly sorry"),
# Group 122
("thoroughly","adv.","کاملاً","thoroughly cleaned"),("tightly","adv.","سفت","tightly controlled"),("totally","adv.","کاملاً","totally different"),("traditionally","adv.","سنتی","traditionally served"),("truly","adv.","واقعاً","truly remarkable"),("typically","adv.","معمولاً","typically requires"),("ultimately","adv.","نهایتاً","ultimately responsible"),("unanimously","adv.","اتفاق آراء","unanimously approved"),("unavoidably","adv.","ناگزیر","unavoidably delayed"),("uncomfortably","adv.","ناراحت","uncomfortably warm"),("unconditionally","adv.","بدون قید و شرط","unconditionally accept"),("undeniably","adv.","غیرقابل انکار","undeniably true"),("undoubtedly","adv.","بی‌شک","undoubtedly correct"),("unexpectedly","adv.","غیرمنتظره","unexpectedly high"),("unfortunately","adv.","متأسفانه","unfortunately missed"),
# Group 123
("uniformly","adv.","یکنواخت","uniformly distributed"),("universally","adv.","جهانی","universally accepted"),("unnecessarily","adv.","غیرضروری","unnecessarily complex"),("unpleasantly","adv.","ناخوشایند","unpleasantly surprised"),("unquestionably","adv.","غیرقابل بحث","unquestionably important"),("urgently","adv.","فوری","urgently needed"),("usefully","adv.","مفید","usefully applied"),("usually","adv.","معمولاً","usually better"),("utterly","adv.","کاملاً","utterly ridiculous"),("vaguely","adv.","مبهم","vaguely familiar"),("vastly","adv.","بسیار","vastly superior"),("verbally","adv.","شفاهی","verbally agreed"),("vertically","adv.","عمودی","vertically integrated"),("vigorously","adv.","پر انرژی","vigorously oppose"),("violently","adv.","خشونت‌آمیز","violently opposed"),
# Group 124
("virtually","adv.","عملاً","virtually impossible"),("visibly","adv.","قابل مشاهده","visibly shaken"),("visually","adv.","بصری","visually appealing"),("vividly","adv.","زنده","vividly remember"),("voluntarily","adv.","داوطلبانه","voluntarily agreed"),("warmly","adv.","گرم","warmly welcomed"),("wholly","adv.","کاملاً","wholly owned"),("widely","adv.","گسترده","widely recognized"),("willingly","adv.","با میل","willingly accept"),("wisely","adv.","عاقلانه","wisely chosen"),("wonderfully","adv.","عالی","wonderfully crafted"),("worryingly","adv.","نگران‌کننده","worryingly high"),("worthily","adv.","شایسته","worthily earned"),("wrongly","adv.","اشتباهاً","wrongly accused"),("yearly","adv.","سالانه","yearly review"),
# Group 125: Extra verbs
("jeopardize","v.","به خطر انداختن","jeopardize health"),("leverage","v.","اهرم کردن","leverage technology"),("localize","v.","بومی‌سازی","localize content"),("mediate","v.","میانجیگری","mediate peace"),("mobilize","v.","بسیج کردن","mobilize support"),("modify","v.","اصلاح کردن","modify behavior"),("monitor","v.","نظارت","monitor closely"),("negotiate","v.","مذاکره","negotiate deal"),("neutralize","v.","خنثی کردن","neutralize threat"),("normalize","v.","عادی کردن","normalize relations"),("obligate","v.","موظف کردن","obligate contract"),("obstruct","v.","ممانعت","obstruct justice"),("occupy","v.","اشغال","occupy territory"),("orchestrate","v.","هماهنگ کردن","orchestrate campaign"),("outweigh","v.","برتری","outweigh benefits"),
# Group 126
("overcome","v.","غلبه کردن","overcome adversity"),("overlook","v.","نادیده گرفتن","overlook mistake"),("overthrow","v.","سرنگون کردن","overthrow dictator"),("overwhelm","v.","غرق کردن","overwhelm emotion"),("participate","v.","شرکت","participate actively"),("persuade","v.","متقاعد","persuade voters"),("pioneer","v.","پیشگام","pioneer research"),("polarize","v.","قطبی","polarize opinion"),("precede","v.","مقدم بودن","precede event"),("prescribe","v.","تجویز","prescribe medicine"),("preserve","v.","حفظ","preserve nature"),("proclaim","v.","اعلام","proclaim victory"),("prohibit","v.","منع","prohibit smoking"),("propel","v.","به پیش راندن","propel forward"),("prosecute","v.","تعقیب","prosecute offender"),
# Group 127
("publicize","v.","تبلیغ","publicize event"),("purchase","v.","خرید","purchase property"),("pursue","v.","دنبال","pursue goal"),("qualify","v.","واجد شرایط","qualify for"),("quantify","v.","کمی کردن","quantify impact"),("rally","v.","جمع کردن","rally support"),("ratify","v.","تصویب","ratify treaty"),("recruit","v.","استخدام","recruit staff"),("rectify","v.","اصلاح","rectify error"),("rehabilitate","v.","بازپروری","rehabilitate offender"),("reimburse","v.","بازپرداخت","reimburse expenses"),("reinforce","v.","تقویت","reinforce message"),("reiterate","v.","تکرار","reiterate point"),("relinquish","v.","واگذار","relinquish control"),("replenish","v.","پر کردن","replenish stock"),
# Group 128
("reprimand","v.","توبیخ","reprimand employee"),("reproduce","v.","تولید مثل","reproduce quickly"),("repudiate","v.","انکار","repudiate claim"),("rescind","v.","لغو","rescind order"),("resemble","v.","شبیه بودن","resemble father"),("retaliate","v.","تلافی","retaliate attack"),("retract","v.","پس گرفتن","retract statement"),("reunite","v.","متحد کردن","reunite family"),("revitalize","v.","احیاء","revitalize economy"),("safeguard","v.","حفاظت","safeguard interest"),("scrutinize","v.","موشکافی","scrutinize detail"),("simulate","v.","شبیه‌سازی","simulate environment"),("stabilize","v.","تثبیت","stabilize economy"),("stimulate","v.","تحریک","stimulate demand"),("strategize","v.","برنامه‌ریزی","strategize effectively"),
# Group 129
("substantiate","v.","اثبات","substantiate claim"),("substitute","v.","جایگزین","substitute ingredient"),("supplement","v.","مکمل","supplement income"),("suppress","v.","سرکوب","suppress dissent"),("surpass","v.","پیشی گرفتن","surpass expectation"),("synchronize","v.","همگام","synchronize data"),("tolerate","v.","تحمل","tolerate pain"),("transform","v.","دگرگون","transform society"),("unify","v.","متحد","unify country"),("utilize","v.","استفاده","utilize resource"),("validate","v.","اعتبارسنجی","validate result"),("vindicate","v.","تأیید","vindicate position"),("withhold","v.","خودداری","withhold information"),("withstand","v.","مقاومت","withstand pressure"),("yield","v.","تولید","yield result"),
]

# Process all entries (flat list of tuples)
for en, pos, fa, ex in BULK:
    W(en, pos, fa, ex)

# Now insert into the file
with open(FILE, 'r', encoding='utf-8') as f:
    content = f.read()

target = "];\n\nconst WORDS_PER_DAY"
if target in content:
    idx = content.rfind(target)
    before = content[:idx]
    after = content[idx:]
    
    new_words = ",\n".join(words)
    new_content = before + new_words + "\n" + after
    
    with open(FILE, 'w', encoding='utf-8') as f:
        f.write(new_content)
    
    initial_count = content.count("['")
    added = len(words)
    print(f"Added {added} new words")
    print(f"Estimated total: ~{initial_count + added}")
else:
    print(f"Could not find insertion point")
    print(content[-300:])
